### ISSUE TITLE
Error 001 thrown when methodmap present 

### ISSUE THREAD

**Issue by GabeHirakawa** [alliedmodders/sourcemod#1000]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Linux
  * Game/AppID (with version if applicable): N/A
  * Current SourceMod version: 1.10
  * Current SourceMod snapshot: 6405

# Description
When creating a methodmap in your include file, the compiler will throw the following error on the last included file (in this case smjansson)

> smjansson.inc(12) : error 001: expected token: ";", but found "<newline>"

I have placed a test repo and links to builds below.

# Explanation
I originally posted this in Discord but essentially the issue is as follows: 
When using 1.10-6405 to compile a plugin with includes present, it will throw the following error on the last inluded file (in this instance, smjansson):

> smjansson.inc(12) : error 001: expected token: ";", but found "<newline>"

It's worth noting that I'm using JoinedSenses' version of SMJansson found [here](https://github.com/JoinedSenses/SMJansson/blob/master/pawn/scripting/include/smjansson.inc). When looking at the line the error occurred on, it occurs within the comments of the include file.

When speaking with JoinedSenses about this issue he had mentioned to me that he was using 6380 to test his Fork. In order to confirm that this isn't an issue with my own code, I ran a build on 6380 myself and found that it was successful. After many different combinations I found that when you create a methodmap within an include, it causes the compiler to throw the above listed error.

# Problematic Code (or Steps to Reproduce)
[master](https://github.com/GabeHirakawa/SMJanssonTest) is SM 1.10-6380
[test/sm-6405](https://github.com/GabeHirakawa/SMJanssonTest/tree/test/sm-6405) is SM 1.10-6405
[test/sm-6405-methodmap](https://github.com/GabeHirakawa/SMJanssonTest/tree/test/sm-6405-methodmap) contains the methodmap
You can confirm these tests by attempting to compile each branch. The first 2 will compile, the last one will fail.

# Logs
[Passed running 6380](https://travis-ci.org/GabeHirakawa/SMJanssonTest/builds/528383854)
[Passed running 6405 wo/methodmap](https://travis-ci.org/GabeHirakawa/SMJanssonTest/builds/528384570)
[Failed running 6405 w/methodmap](https://travis-ci.org/GabeHirakawa/SMJanssonTest/builds/528400240)

**Comment by Bara** [comment]
methodmaps needs a `;` at the end. The provided error from the compiler is pretty annoying and irritating.

in your example:
```
methodmap TestSMjansson
{
    public TestSMjansson() {}
};
```

**Comment by Bara** [comment]
I think this should be reported in [sourcepawn](https://github.com/alliedmodders/sourcepawn).

**Comment by asherkin** [comment]
> methodmaps needs a `;` at the end.

That is incorrect, see alliedmodders/sourcepawn#319

**Comment by Fyren** [comment]
There's two separate things happening here.

First, because the code given in the original comment has `#pragma semicolon 1`, the semicolon is required by spcomp.  However, the commit message for the change linked in the previous comment and the actual code appear to be at ends.  The code uses `TerminatorPolicy::Semicolon` where the commit message seems to say it ought to be `NewlineOrSemicolon`.  I guess this is a bug.

Second, the error message reports the wrong file name.  This is definitely a bug.

**Comment by Fyren** [comment]
Both should be fixed in 1.10 6409.

**Comment by GabeHirakawa** [comment]
Looks like I can confirm that. Thanks!
