### ISSUE TITLE
1.10 - build 6405 CSGO CS_OnBuyCommand don't work

### ISSUE THREAD

**Issue by e54385991** [alliedmodders/sourcemod#1001]
* OS:Windows Server 2016
  * GameAPPID:CS:GO/730
  * Current SourceMod version:1.10
  * Current SourceMod snapshot: 6405
  * Current Metamod: Source snapshot:1127

  - [√ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [√ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

# Problematic Code (or Steps to Reproduce)

public Action CS_OnBuyCommand(int client, const char[] weapon)
{
	PrintToServer("Buy:%s",weapon);
       return Plugin_Handled;
}

No effect..

**Comment by e54385991** [comment]
1.10 - build 6394 CS_OnBuyCommand workfine.

**Comment by KyleSanderson** [comment]
Missing issue template ( :-( ): can you try to fill it out so we can have a chance to reproduce this?
