### ISSUE TITLE
L4D1 & 2 using the wrong file path for matchmaking_ds

### ISSUE THREAD

**Issue by Psykotikism** [alliedmodders/sourcemod#1006]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Win & Lin
  * Game/AppID (with version if applicable): 500 & 550
  * Current SourceMod version: 1.10
  * Current SourceMod snapshot: 6407
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.

# Description
Both Left 4 Dead games have their matchmaking_ds files inside {mod folder}/bin, and currently SM is set up to look for that file inside {mod folder}/bin/{platform}.

Maybe you guys could make an exception for L4D1&2 to define PLATFORM_FOLDER as "" for those games? Just a suggestion.

For convenience, the file path is defined here: https://github.com/alliedmodders/sourcemod/blob/master/core/logic_bridge.cpp#L633

# Problematic Code (or Steps to Reproduce)
N/A

# Logs
* N/A

**Comment by asherkin** [comment]
Thanks for the report. Please add some detail on how this is affecting you such as explaining what is not working or including error logs you are getting from it not being found.

**Comment by Psykotikism** [comment]
Here are the logs on my L4D2 server upon start-up. I have also attached the plugin and the gamedata file associated with it so you can test for yourself.
[l4d-changemission.zip](https://github.com/alliedmodders/sourcemod/files/3165449/l4d-changemission.zip)

**Comment by asherkin** [comment]
It looks like this might be wrong for all games on Linux, I suspect the paths here are specific to macOS (or possibly just the client distributions in general).
