### ISSUE TITLE
Wrong formating to "Vote Delay Minutes" when delay above 60s

### ISSUE THREAD

**Issue by PlayBoy31** [alliedmodders/sourcemod#1007]
##

[delay formating.zip](https://github.com/alliedmodders/sourcemod/files/3169320/delay.formating.zip)

 Description
set sm_vote_delay above 60s, 900 for example

# Problematic Code (or Steps to Reproduce)
Reply to command after CheckVoteDelay() when delay > 60 on basevotes.sp or funvotes.sp are wrong.

`ReplyToCommand(client, "[SM] %t", "Vote Delay Minutes", delay % 60);`

must be replaced by:

ReplyToCommand(client, "[SM] %t", "Vote Delay Minutes", **(delay / 60)** % 60);

otherwise, seconds are only displayed when its above minute ...

Issue is present on **basevotes.sp** and on **funvotes.sp**

fixed files attached to this issue

[delay formating.zip](https://github.com/alliedmodders/sourcemod/files/3169321/delay.formating.zip)

**Comment by KyleSanderson** [comment]
Can you issue a Pull Request instead of the zip? I'm on a handset and can't review...

**Comment by PlayBoy31** [comment]
> 
> 
> Can you issue a Pull Request instead of the zip? I'm on a handset and can't review...

done

**Comment by KyleSanderson** [comment]
thx let's move there
