### ISSUE TITLE
TF2_AddCondition duration is ignored

### ISSUE THREAD

**Issue by M4thx** [alliedmodders/sourcemod#1013]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System: Linux (Arch Linux) 
  * Game/AppID (with version if applicable): TF2 / 232250
  * Current SourceMod version: 1.10
  * Current SourceMod snapshot: 6410
  * Current Metamod: Source snapshot: 1127
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Conditions applied by TF2_AddCondition are always infinite, despite the duration parameter being set to a finite value.

Worked fine on build 6394, can't test next builds because the download isn't available.

# Problematic Code (or Steps to Reproduce)
Simple plugin that tries to apply a temporary condition, which ends up staying forever.
  ```
#include <sourcemod>
#include <tf2>

public void OnPluginStart()
{
  RegConsoleCmd("sm_addcond", Command_AddCond);
}

public Action Command_AddCond(int client, int args)
{
  TF2_AddCondition(client, TFCond_Ubercharged, 0.5); // Duration will be ignored
}

  ```

**Comment by asherkin** [comment]
Just to clarify, you're testing indicates this broke between 1.10.0.6394 and 1.10.0.6410?

**Comment by M4thx** [comment]
Yes.

**Comment by asherkin** [comment]
Thanks, looks like a casualty of #965, there is a `sp_ctof` call missing that was previously done using a cast.
