### ISSUE TITLE
ReplyToCommand set to source console instead of chat

### ISSUE THREAD

**Issue by PlayBoy31** [alliedmodders/sourcemod#1023]
If we have a bind to open the admin menu then we use a command from the menu the source is set as console instead of chat and the reply is display on console instead of chat which is very annoying

for my case, i limit time between votes with vote delay and i open admin menu from a bind.

**Comment by asherkin** [comment]
This behaviour is correct, your bind is running a console command - if you want to force the command source to chat you could bind `say /admin` instead of `sm_admin`.
