### ISSUE TITLE
SQL threadable executing prepared queries

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcemod#1032]
It will be nice if we have in SourceMod support to run prepared queries in another thread. For simple queries and transactions in SM we have `Database.Query` / `SQL_TQuery` / `Database.Execute` / `SQL_Execute`, but don't have something similar for prepared queries.

**Comment by asherkin** [comment]
Native prepared queries have a lot of problems as they're represented as an object on the server-side - which means the shared state can easily be lost, resulting in hard to recover from errors. This is why almost all SQL libraries have moved towards "fake" prepared queries that just give you the auto-escaping, which is what we implemented with the `FormatQuery` native.

**Comment by CrazyHackGUT** [comment]
Why this issue is closed as "completed", if this issue is not solved?

**Comment by asherkin** [comment]
GitHub didn't have close reasons until March 10, 2022, almost 3 years after this was closed, all old issues defaulted to "as completed".
