### ISSUE TITLE
CreateFragmentsFromFille

### ISSUE THREAD

**Issue by zorkenJB** [alliedmodders/sourcemod#1037]
Hello,  last day my server crash 3 time in 5 minute, console is spammed with this
CreateFragmentsFromFile: '.txt' doesn't exist.
and crash...
I updated sourcemod+metamod, same..
I search on google this probleme and the fix was sv_allowupload 0, i use this and same, crash..

  * Operating System version: linux
  * Game/AppID (with version if applicable): csgo
  * Current SourceMod version: newest
  * Current SourceMod snapshot: newest
  * Current Metamod: Source snapshot: newest

**Comment by Bara** [comment]
Install this plugin: https://forums.alliedmods.net/showthread.php?p=2656975
