### ISSUE TITLE
Segmentation fault at old_bf_write::WriteByte(int) and UTIL_SendHudText

### ISSUE THREAD

**Issue by Thordin** [alliedmodders/sourcemod#1040]
# Environment
  * Operating System version: Ubuntu 18.04 x64
  * Game/AppID (with version if applicable): 440 5097991/24 5097991
  * Current SourceMod version: 1.9.0
  * Current SourceMod snapshot: 6281
  * Current Metamod: Source snapshot: 970

# Description

Segmentation fault at old_bf_write::WriteByte(int) and UTIL_SendHudText.

I have no idea which plugin this may have come from. This is the first time I've seen this crash so I can't really reproduce it.

# Problematic Code (or Steps to Reproduce)

This randomly happened on a deathrun server.

# Logs
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xe906ce32 in old_bf_write::WriteByte(int) () from tf/addons/sourcemod/bin/sourcemod.2.tf2.so
[Current thread is 1 (Thread 0xf7d1b700 (LWP 10217))]
#0  0xe906ce32 in old_bf_write::WriteByte(int) () from tf/addons/sourcemod/bin/sourcemod.2.tf2.so
#1  0xe905c425 in UTIL_SendHudText(int, hud_text_parms const&, char const*) () from tf/addons/sourcemod/bin/sourcemod.2.tf2.so
#2  0x00000001 in ?? ()
#3  0x00000000 in ?? ()

```

**Comment by asherkin** [comment]
I'm afraid one-off crashes, without a crash dump and without reproduction steps are completely un-actionable. This was probably caused by unrelated memory corruption or a failure to allocate memory.
