### ISSUE TITLE
bug | !unmute @ all not worked

### ISSUE THREAD

**Issue by Drmohammad11** [alliedmodders/sourcemod#1051]
hi guys!

!mute @ all > worked: muted all players for 30 min
!unmute @ all > do not work

tnx

**Comment by Drmohammad11** [comment]
why ??

**Comment by Drmohammad11** [comment]
can you help me??
this is bug and not work.

**Comment by Glubbable** [comment]
Because you ignored the template that is auto-generated for you when submitting an issue.
Ontop of that, just saying something does not work, is not helpful at all.

**Comment by Drmohammad11** [comment]
> Because you ignored the template that is auto-generated for you when submitting an issue.
> Ontop of that, just saying something does not work, is not helpful at all.

sorry. :((
