### ISSUE TITLE
Func ReplaceString() problem with UTF8

### ISSUE THREAD

**Issue by PlayBoy31** [alliedmodders/sourcemod#1057]
Hello,

There is a strange issue with ReplaceString() function

with this code:

> #define STRING_MESSAGE_SIZE 191
> 
> Message is set as : "в доме"
> 
> ReplaceString(Message, STRING_MESSAGE_SIZE, "´", "");

The ReplaceString function detect that there is a "´" in "в доме" whereas it shouldn't

**Comment by asherkin** [comment]
SourceMod's String API only supports standard ASCII by design, see also #978

**Comment by PlayBoy31** [comment]
What can i do ? is there a way to convert all to ascii ?

have SM dev in target to implement full UTF8 support ? in this case when?

**Comment by KyleSanderson** [comment]
The vast majority of games do not support full UTF8 (which is why we haven't, security problems)... There are tricks to get it in there (and SM does have partial coverage through DBI) but it's not on any road-map currently to have it in the language natively.

**Comment by asherkin** [comment]
You can write your own multibyte-safe ReplaceString using the IsCharMB function.
