### ISSUE TITLE
Segfault when setting up SDKCall with SDKType_Vector and SDKPass_ByValue on 1.10

### ISSUE THREAD

**Issue by nosoop** [alliedmodders/sourcemod#1059]
## Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

## Environment
  * Operating System version: Ubuntu 16.04 Linux
  * Current SourceMod snapshot: 1.10.0.6434 (b8fd7db)

## Description

SourceMod crashes ~~on startup~~ when setting up a parameter of type `SDKType_Vector` and `SDKPass_ByValue` pass method.  This is a regression in 1.10.

Reported error is `SIGSEGV /SEGV_MAPERR accessing 0x8` on [this line](https://github.com/alliedmodders/sourcemod/blob/ae0a03d43853624b4a6de41b3d673b72c616bbdd/extensions/sdktools/vdecoder.cpp#L77), which suggests that the `info->fields` isn't being initialized.

## Problematic Code (or Steps to Reproduce)
  ```sp
#pragma semicolon 1
#include <sourcemod>

#include <sdktools>

#pragma newdecls required

Handle g_SDKCallGetProjectileFireSetup;

public void OnPluginStart() {
	// using hardcoded vtable offset here for the sake of example,
	// shouldn't matter since it's not being called
	
	// CTFWeaponBase::GetProjectileFireSetup(CTFPlayer*, Vector, Vector*, QAngle*, bool, float)
	StartPrepSDKCall(SDKCall_Entity);
	PrepSDKCall_SetVirtual(400);
	PrepSDKCall_AddParameter(SDKType_CBasePlayer, SDKPass_Pointer);
	PrepSDKCall_AddParameter(SDKType_Vector, SDKPass_ByValue); // crashes here
	PrepSDKCall_AddParameter(SDKType_Vector, SDKPass_Pointer,
			.encflags = VENCODE_FLAG_COPYBACK);
	PrepSDKCall_AddParameter(SDKType_QAngle, SDKPass_Pointer,
			.encflags = VENCODE_FLAG_COPYBACK);
	PrepSDKCall_AddParameter(SDKType_Bool, SDKPass_Plain);
	PrepSDKCall_AddParameter(SDKType_Float, SDKPass_Plain);
	if ((g_SDKCallGetProjectileFireSetup = EndPrepSDKCall()) == INVALID_HANDLE) {
		SetFailState("gamedata oopsie");
	}
}

  ```

## Logs

[Accelerator link.](https://crash.limetech.org/s3jcy2dki7xf)

**Comment by naydef** [comment]
We've been setting up a Slender Fortress server on Windows machine today. We updated to SM 1.10.6451 and the server started to crash on startup. After investigating the issue for several hours, the issue was tracked down to these 7 lines of code: 
https://github.com/Kenzzer/Slender-Fortress-New-Versions/blob/b17949759b73f50397a398184a300d48acd56786/addons/sourcemod/scripting/sf2.sp#L1170
I believe the crashes are related to this issue, so I kindly request this issue gets necessary attention.

### Crash url:
https://crash.limetech.org/7vvq3sc63dkn

**Comment by asherkin** [comment]
Thanks, the longer stack trace is helpful here - I think I've found the source of the bug and will send a PR.

**Comment by asherkin** [comment]
I think this should be fixed in master now, could you give it a test and report back?

**Comment by nosoop** [comment]
Latest SM build does not seem to cause the crash related to the original issue.  Thanks!

**Comment by naydef** [comment]
Latest SM build fixed the issue.

Cheers!
