### ISSUE TITLE
Allow Traversal of BSP Files

### ISSUE THREAD

**Issue by hydrogen-mvm** [alliedmodders/sourcemod#1061]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 7
  * Game/AppID (with version if applicable): 232250 (TF2 SRCDS)
  * Current SourceMod version: 1.9
  * Current SourceMod snapshot: 1.9.0.6281
  * Current Metamod: Source snapshot: 1.10.7-dev
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
On occasion I want to look and see what files are packed inside a bsp file. Naturally with OpenDirectory with use_valve_fs=true I thought I could do that, but it doesn't print any of the files inside the bsp file.

However, strangely enough, FileExists works correctly with files packed inside a bsp file. I would think that if FileExists can check if a file exists inside a bsp file (or anything in the Valve file system hierarchy) then OpenDirectory should be able to enumerate the contents inside a bsp file. Is that not how it works in the source engine or is this a Sourcemod bug?

You can download the bsp file that I used to test this with from here:

https://demos.potato.tf/prejudging/maps/mvm_outlands_rc2.bsp

Thanks.

# Problematic Code (or Steps to Reproduce)
  ```
public void OnPluginStart()
{
	DirectoryListing Directory = OpenDirectory("materials/hud", true);
	char Buffer[128];
	while (Directory.GetNext(Buffer, sizeof(Buffer)))
		if (StrContains(Buffer, "leaderboard_class_", false) == 0 && StrContains(Buffer, "pyro", false) != -1)
			PrintToServer(Buffer);
	
	char IconFile[] = "materials/hud/leaderboard_class_pyro_gaspasser_tind.vmt";
	PrintToServer("===============");
	PrintToServer("Checking for existence of file: %s", IconFile);
	PrintToServer("File exists: %d", FileExists(IconFile));
	PrintToServer("File exists (Valve FS): %d", FileExists(IconFile, true));
	delete Directory;
}
  ```

# Logs
```
Printing folder contents:
leaderboard_class_pyro.vtf
leaderboard_class_pyro_flare.vtf
leaderboard_class_pyro.vmt
leaderboard_class_pyro_d.vmt
leaderboard_class_pyro_flare.vmt
leaderboard_class_pyro_flare_giant.vmt
leaderboard_class_pyro_giant.vmt
===============
Checking for existence of file: materials/hud/leaderboard_class_pyro_gaspasser_tind.vmt
File exists: 0
File exists (Valve FS): 1
```

My expectation is I would think "leaderboard_class_pyro_gaspasser_tind.vmt" would appear somewhere in the listings of OpenDirectory. If this is not how it works, then maybe a doc edit mentioning this limitation would prevent others from also getting stumped by this?

**Comment by hydrogen-mvm** [comment]
Slightly related issue but it looks like KeyValues.ImportFromFile by default always looks at the Valve file system. I'm parsing that .vmt file (the one listed above) with the KeyValues API and it's always grabbing the one packed inside the bsp over the one in my main server directory (tf/materials/hud). Is this intentional or should there be an optional parameter to allow toggling the valve file system on/off? (If that's even possible to implement.)

**Comment by psychonic** [comment]
This is a limitation of the Valve filesystem provider. Files packed inside of maps are not supported for directory iteration on most or all engine versions.

**Comment by psychonic** [comment]
> Slightly related issue but it looks like KeyValues.ImportFromFile by default always looks at the Valve file system. 

This is because we use Valve's KeyValues class, which uses their filesystem provider. As a workaround on some engine versions, you can convert to an absolute path, and pass that through.
