### ISSUE TITLE
TF2_DisguisePlayer is broken and blocking player disguise

### ISSUE THREAD

**Issue by EfeDursun125** [alliedmodders/sourcemod#1064]
TF2_DisguisePlayer is not working

TF2_DisguisePlayer(client, TFTeam_Blue, TFClass_Sniper, 0);

Spy not digsuising and FakeClientCommand(client "disguise -1 6"); not working and if TF2_DisguisePlayer always repeating blocks player disguise

Windows 10 Pro
SourceMod : 1.9 - build 6281
MetaMod:S : 1.10 - build 970

**Comment by Andrej730** [comment]
It's kind of outdated now but anyway.

The code I tried is below.
1) For `disguise` command the syntax is a bit different. For example, the command to disguise as an enemy sniper is `disguise 2 -1`. More detailed description here - https://wiki.teamfortress.com/wiki/Scripting#Disguising

2) I tried TF2_DisguisePlayer and it's actually working fine.

3) When I tried `FakeClientCommandEx(client, "disguise 2 -1");` I got `Unknown command: disguise` on client. So it's seems that there is an issue with using `FakeClientCommand` with `disguise` command.

```SourcePawn
public Action Command_MyDisguise(int client, int args)
{
	if (client == 0) {
		char arg1[32];
		
		if (GetCmdArg(1, arg1, sizeof(arg1))) {
			FakeClientCommand(StringToInt(arg1), "disguise 2 -1");
		} else {
			FakeClientCommand(1, "disguise 2 -1");					
		}
		
		return Plugin_Handled;
	}

	int player_team;
	player_team = GetClientTeam(client);

	if (player_team < 2) {
		ReplyToCommand(client, "[SM] Join a team first.");	
		return Plugin_Handled;
	}

	if (TF2_IsPlayerInCondition(client, TFCond_Disguised)){
		TF2_RemovePlayerDisguise(client);
		ReplyToCommand(client, "[SM] You're not so disguised now.");
		return Plugin_Handled;
	}

	TF2_DisguisePlayer(client, player_team == 2 ? TFTeam_Blue : TFTeam_Red , TFClass_Scout, 0);
	ReplyToCommand(client, "[SM] You're now disguised as a scout..");
	return Plugin_Handled;

}
```

**Comment by nosoop** [comment]
re: `disguise` command, [it's sent as an `impulse` command](https://wiki.teamfortress.com/wiki/Cheats#impulse).  The server (and SourceMod) doesn't receive it as a command string:

```
] cmd disguise 2 7
Unknown command: disguise
] disguise 2 7 // works
```

**Comment by Kenzzer** [comment]
Is it possible to get an update on this issue ? It doesn't seem like it was a bug in the fist place.

**Comment by EfeDursun125** [comment]
I forgot even this existed, it was a bug after the sourcemod update back in 2019.
