### ISSUE TITLE
[BUG] crash server with command-line +sm_basepath !!

### ISSUE THREAD

**Issue by Drmohammad11** [alliedmodders/sourcemod#1075]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: windows server 2008 r2
  * Game/AppID (with version if applicable):  csgo/730
  * Current SourceMod version: 1.9 - build 6282
  * Current Metamod: Source version: 1.10 - build 971
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

# Problematic Code (or Steps to Reproduce)
  ```
  1- add command-line "+sm_basepath"
   2- run server and see crashe!!
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.
Unknown command "sm_basepath"
Setting mapgroup to 'match'
L 09/05/2019 - 10:03:00: server_cvar: "sv_password" "PROTECTED"
maxplayers set to 64
L 09/05/2019 - 10:03:00: server_cvar: "tv_enable" "1"
NET_CloseAllSockets
[QCache] Hooking recvfrom - SUCCESS.
[QCache] Hooking sendto - SUCCESS.
Missing shutdown function for Sys_InitAuthentication() : Sys_ShutdownAuthentication()

**Comment by Kailo97** [comment]
Solved with https://github.com/alliedmodders/hl2sdk/pull/61

**Comment by Headline** [comment]
Thanks!
