### ISSUE TITLE
Add new native TR_GetHitBox()

### ISSUE THREAD

**Issue by Einyux** [alliedmodders/sourcemod#1080]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).

# Description

In **CGameTrace** there's this member:

```
// NOTE: this member is overloaded.
// If hEnt points at the world entity, then this is the static prop index.
// Otherwise, this is the hitbox index.
int			hitbox;					// box hit by trace in studio
```

https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/gametrace.h#L73

It would be nice to have access to this member in SourceMod. 
It can be used when creating decals using TE:

```
"CTEDecal"
{
	"name"		"Entity Decal"
	"index"		"22"

	"SendTable"
	{
		"m_vecOrigin"		"vector"
		"m_vecStart"		"vector"
		"m_nEntity"		"int"
		"m_nHitbox"		"int"      // <=====
		"m_nIndex"		"int"
	}
}
```

-----
If needed, I can propose a PR.
Thanks.

**Comment by KyleSanderson** [comment]
A PR would definitely speed it up

**Comment by KyleSanderson** [comment]
Thank you for your contribution :)
