### ISSUE TITLE
"A copy of the JIT License is available in JIT.txt."

### ISSUE THREAD

**Issue by DJPlaya** [alliedmodders/sourcemod#1086]
### Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).

The Sourcemod License says "A copy of the JIT License is available in JIT.txt." but that File dosent exist, and JIT isent a License Type.
Might be a Typo, did you mean the MIT License?

**Comment by dvander** [comment]
In fact, we used to have a separate license for the SourcePawn VM. It was closed-source until SourceMod 1.1.

Anyway, that was a trillion years ago, so feel free to submit a PR removing this ancient text.

**Comment by DJPlaya** [comment]
#Done
