### ISSUE TITLE
SourceMod sometimes resets global translation target and don't restores him

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcemod#1087]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows
  * Game/AppID (with version if applicable): 440 / 232250
  * Current SourceMod version: 1.10.0
  * Current SourceMod snapshot: 6443
  * Current Metamod: Source snapshot: 1128
  - [X] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [X] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [X] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
When we call `LogMessage()` (for example), SourceMod overrides "global target" for translations.
https://github.com/alliedmodders/sourcemod/blob/22635d8d354f42d8e295617d74ea95d3ef28c68b/core/logic/smn_filesystem.cpp#L850-L866
Seems like it used for correct formatting for server console.
But SM does not restore old global translation target, and this information has never mentioned in include files or wiki (or i just can't find this).

# Problematic Code (or Steps to Reproduce)
sourcecode
```pawn
#include <sourcemod>

#pragma newdecls  required
#pragma semicolon 1

public void OnPluginStart()
{
    LoadTranslations("test_log_message.phrases");
}

public void OnClientPutInServer(int iClient)
{
    CreateTimer(5.0, OnClientFullyLoaded, GetClientUserId(iClient));
}

public Action OnClientFullyLoaded(Handle hTimer, int iClient)
{
    if ((iClient = GetClientOfUserId(iClient)) == 0)
    {
        return;
    }

    SetGlobalTransTarget(iClient);

    char szBuffer[64];
    FormatEx(szBuffer, sizeof(szBuffer), "%t", "Menu Item 1");

    Menu hMenu = new Menu(NullMenuHandler, MenuAction_End);
    hMenu.SetTitle("%t", "Menu Header");
    hMenu.AddItem(NULL_STRING, szBuffer);

    // for example, write now any log message
    LogMessage("Client %L connected", iClient);

    // now, we have reseted translation target to `LANG_SERVER`.
    FormatEx(szBuffer, sizeof(szBuffer), "%t", "Menu Item 1");
    hMenu.AddItem(NULL_STRING, szBuffer);

    hMenu.Display(iClient, 0);
}

public int NullMenuHandler(Menu hMenu, MenuAction eAction, int iParam1, int iParam2)
{
    hMenu.Close();
}
```

lang file
```
"Phrases"
{
    "Menu Header"
    {
        "en"  "Test"
        "ru"  "Magic"
    }

    "Menu Item 1"
    {
        "en"  "You expected something another, yes?"
        "ru"  "Whoa"
    }
}
```

# Expected menu
```
Magic
1. Whoa
2. Whoa
```

# Current behavior (menu)
```
Magic
1. Whoa
2. You expected something another, yes?
```

**Comment by KyleSanderson** [comment]
This is expected.

**Comment by asherkin** [comment]
The code here is correct, the global translation target is not expected to be restored - the bug here is in your code using the `%t` format specifier instead of `%T` in a format function that does not specify a client.

**Comment by CrazyHackGUT** [comment]
So, for what reason SM has native `SetGlobalTransTarget()`? I thought, for do not repeating `iClient` index in format functions, if this is possible.

**Comment by asherkin** [comment]
It is so consumers of `VFormat` can support the short-form version when they themselves are client based, e.g. `PrintToChatAll`.

https://github.com/alliedmodders/sourcemod/blob/81dc80fbd14b7eba3c20bc22a60629fc874015de/plugins/include/halflife.inc#L371-L390
