### ISSUE TITLE
FormatTime() adds mysterious 19 hours in window sv

### ISSUE THREAD

**Issue by Locomotivers** [alliedmodders/sourcemod#1093]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment 1 Window
  * Operating System version: Window 10 
  * Game/AppID (with version if applicable): csgo/730
  * Current SourceMod version:  1.10.0
  * Current SourceMod snapshot:  6466
  * Current Metamod: Source snapshot: 1.11.0-git1128
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Environment 2 Linux
  * Operating System version:  Debian 9 (Strech)
  * Game/AppID (with version if applicable): csgo/730
  * Current SourceMod version:  1.10.0
  * Current SourceMod snapshot:  6466
  * Current Metamod: Source snapshot: 1.11.0-git1128
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
So I was working on a plugin utilizing [FormatTime()](https://sm.alliedmods.net/new-api/sourcemod/FormatTime) and happen to notice it adds up 19 hours on Window server. I tested the Linux environment as well and it prints out just fine. I included both results in below.

# Problematic Code (or Steps to Reproduce)
  ```
  #include <sourcemod>

#pragma semicolon 1
#pragma newdecls required

public void OnPluginStart()
{
	RegConsoleCmd("sm_test", Cmd_Test, "test");
}

public Action Cmd_Test(int client, int args){
	int timeZero = 0;
	int timeOne = 1;
	
	char buffer[12];
	
	FormatTime(buffer, sizeof(buffer), "%T", timeZero);
	PrintToChat(client, "This is what timeZero reports: %s", buffer); //Expected return 00:00:00
	
	FormatTime(buffer, sizeof(buffer), "%T", timeOne);
	PrintToChat(client, "This is what timeOne reports: %s", buffer); //Expected return 00:00:01
	
	FormatTime(buffer, sizeof(buffer), "%T", GetTime());
	PrintToChat(client, "This is what GetTime() reports: %s", buffer); //Expected return current time in miltary time format
}
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

![WinSv](https://user-images.githubusercontent.com/7984445/65939242-54285c00-e3f3-11e9-983e-4e3112911dd1.png)

![Debian](https://user-images.githubusercontent.com/7984445/65939399-d3b62b00-e3f3-11e9-8903-a469afff583b.png)

**Comment by KyleSanderson** [comment]
what timezone is set on both servers?

**Comment by Locomotivers** [comment]
Ohh sorry Window is based on Eastern Time and Debian was set to UTC
Sorry for not mentioning on the post!

**Comment by KyleSanderson** [comment]
Presumably that explains the problem? :)

**Comment by Locomotivers** [comment]
I'm not unsure what is the problem. Can you explain for me?

**Comment by Fyren** [comment]
EDT is four hours ahead of UTC and EST is five hours ahead of UTC.

**Comment by Locomotivers** [comment]
Ahh makes sense a bit now I guess unix timestamp is based off UTC time. I will go ahead close this :( Thanks!
