### ISSUE TITLE
High SV Map

### ISSUE THREAD

**Issue by xMaZax** [alliedmodders/sourcemod#1098]
# Help us help you
  - [+] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [+] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [+] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian GNU/Linux 10 (buster)  1.1.1c-1
  * Game/AppID (with version if applicable):  730
  * Current SourceMod version:  1.10.0.6451, jit-x86 (build 1.10.0.6451)
  * Current SourceMod snapshot:  DEV
  * Current Metamod: Source snapshot: 1.10.7-dev
  - [+] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [+] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [+] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
I don't know what the problem is but I'll decide to leave issues here
Video: https://youtu.be/BktLOTdU_oI
Map: https://drive.google.com/file/d/15qnJY8_ADSb7UNhG5qCTL9-aRvflGOsn/view?usp=sharing

# Logs
vprof dump:
https://pastebin.com/dmJuPHiQ

**Comment by xMaZax** [comment]
I have just checked at myself this map on the local server and there too there is the same problem( I think it is a bug of VALVE (.

**Comment by Headline** [comment]
Hi, thanks for looking into it, probably a poorly optimized or large map. 

Have a good day!
