### ISSUE TITLE
/lib/libc.so.6: version `GLIBC_2.17' not found

### ISSUE THREAD

**Issue by rsdtt** [alliedmodders/sourcemod#1112]
centos 6.10
after update sourcemod 1.10
It is not easy to update GLIBC
if this not necessary, I hope that use lower version(like: GLIBC_2.2.5-2.10)

**Comment by asherkin** [comment]
Please fill out the issue template in full, it is important that you provide details of what game you are running. It'd also be helpful to know what SM version you were running previously that did work.

**Comment by rsdtt** [comment]
Failed to load plugin addons/sourcemod/bin/sourcemod_mm (/lib/libc.so.6: version `GLIBC_2.17' not found (required by /home/steam/steamcmd/cs_go/csgo/addons/sourcemod/bin/sourcepawn.jit.x86.so) (failed to load bin/sourcepawn.jit.x86.so)).

sourcemod-1.9.0-git6282-linux.tar.gz is work
sourcemod-1.10.0-git6453-linux.tar.gz not work

**Comment by rsdtt** [comment]
I have crash a server when I updating GLIBC :(
And I still have many server need to update

**Comment by KyleSanderson** [comment]
@rsdtt sorry man - we don't officially support CentOS 6 anymore (more of a GNU problem).

We just barely don't support CentOS 7 anymore with the default toolchain (glibc should still be okay for now - though). Can you update your distro to atleast CentOS 7 or hopefully CentOS 8?

**Comment by rsdtt** [comment]
I have reinstall my system to CentOS 7
