### ISSUE TITLE
IsEndOfFile returning incorrect values

### ISSUE THREAD

**Issue by hydrogen-mvm** [alliedmodders/sourcemod#1121]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 7 Professional
  * Game/AppID (with version if applicable): Team Fortress 2
  * Current SourceMod version: 1.9
  * Current SourceMod snapshot: 6281
  * Current Metamod: Source snapshot: 1.10.7
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
It seems like IsEndOfFile() bugs out and incorrectly returns false at the last read when a file is read with a chunk size that is evenly divisible by its file size.

In the test case below, I have a 20 byte file and read it in 10 byte chunks. The first time it returns 10 bytes and IsEndOfFile returns false, the second time it returns 10 bytes and IsEndOfFile returns false (WRONG, it should return true since 20 bytes were read in), the third time it returns 0 bytes and THEN IsEndOfFile returns true.

This caused a bizarre crash on my server (the return value of ReadString was assumed to be non-zero) and I was stumped until I narrowed it down to this. Unless I misunderstand the functionality of IsEndOfFile, it should return true after bytes 11-20 were read in, no?

Sorry I am not able to test using the latest SM versions because my environment was designed around SM 1.9. Hopefully the test case is small enough that someone can quickly test it on SM 1.10 to see if the problem persists there too.

# Problematic Code (or Steps to Reproduce)
  ```
public void OnPluginStart()
{
	char Buffer[32];
	File f = OpenFile("test.txt", "rb");
	while (!f.EndOfFile())
	{
		int Bytes = f.ReadString(Buffer, sizeof(Buffer), 10);
		PrintToServer("Bytes Read: %d", Bytes);
	}
	delete f;
}
  ```
Console output:
```
Bytes Read: 10
Bytes Read: 10
Bytes Read: 0 // This shouldn't even print, why does f.EndOfFile() return false when the next read will spit out 0 bytes?
```
You can generate a test file of any arbitrary size using the Python snippet below:
```
with open("test.txt", mode="w") as f:
     f.write("H"*20)
```
Here's the file I used in the above test:
```
HHHHHHHHHHHHHHHHHHHH
```

If it's any help, this happens even during "rb" so I have doubts it has to do with unicode magic.

**Comment by asherkin** [comment]
Thanks for the bug report - unfortunately this is the normal (and expected) C / OS behaviour for `feof` (the library call underpinning `EndOfFile`), the flag isn't set until you read *past* the end of the file.

> This indicator is generally set by a previous operation on the stream that attempted to read at or past the end-of-file.
> 
> Notice that stream's internal position indicator may point to the end-of-file for the next operation, but still, the end-of-file indicator may not be set until an operation attempts to read at that point.

**Comment by hydrogen-mvm** [comment]
Ah, okay, thanks for the implementation details.
