### ISSUE TITLE
Mysql many connections

### ISSUE THREAD

**Issue by Davidos15** [alliedmodders/sourcemod#1133]
Our team has more than 100 servers in CS: GO, and we encountered a very large number of connections (1500 connections) in Mysql and our server is very heavily loaded and terrible delays begin, can this be fixed somehow?

**Comment by Bara** [comment]
How about to optimize the plugins, if they are custom/private?

**Comment by Davidos15** [comment]
Sorry that there is little information, but for a large number of servers it is difficult. Here is the whole list of plugins from our servers.
[Duels.txt](https://github.com/alliedmodders/sourcemod/files/3892574/Duels.txt)
[KZ.txt](https://github.com/alliedmodders/sourcemod/files/3892575/KZ.txt)
[DM.txt](https://github.com/alliedmodders/sourcemod/files/3892576/DM.txt)
[Bhop.txt](https://github.com/alliedmodders/sourcemod/files/3892577/Bhop.txt)
[Executes.txt](https://github.com/alliedmodders/sourcemod/files/3892578/Executes.txt)
[Retake.txt](https://github.com/alliedmodders/sourcemod/files/3892579/Retake.txt)
[Arena.txt](https://github.com/alliedmodders/sourcemod/files/3892580/Arena.txt)
[Surf.txt](https://github.com/alliedmodders/sourcemod/files/3892581/Surf.txt)
[Public.txt](https://github.com/alliedmodders/sourcemod/files/3892582/Public.txt)
[AWP.txt](https://github.com/alliedmodders/sourcemod/files/3892583/AWP.txt)

**Comment by Headline** [comment]
can you show the output of `sm_dump_handles handles.txt`

It will create a text file named `handles.txt` in the game directory

**Comment by Davidos15** [comment]
We bought a more powerful server and now everything is fine.
