### ISSUE TITLE
SM 1.10 Extension Compilation Fails on am-string.h

### ISSUE THREAD

**Issue by hydrogen-mvm** [alliedmodders/sourcemod#1134]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Linux
  * Game/AppID (with version if applicable): TF2
  * Current SourceMod version: 1.10
  * Current SourceMod snapshot: N/A
  * Current Metamod: Source snapshot: 1.10
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
So I might be retarded and doing something stupid here... and I hope this is in fact the case. I am building the Sendproxy extension on Linux against SM 1.10 since it became the new stable branch. However, I am unsuccessful in getting it to build because of a missing header file.

![image](https://user-images.githubusercontent.com/29522123/69772512-21ce7d00-115e-11ea-925a-4f6acf02c3e7.png)

The extension builds successfully against the 1.9 branch, so I went digging through the two branches and saw that this commit introduced the problem:

https://github.com/alliedmodders/sourcemod/commit/5611ec54a21c3045cc1680b954631c6ca049c768#diff-a2685fd9803c85bab2667401ae369a41

The question I want to ask is: Is the repository missing an am-string.h file somewhere? I did all the checkouts and everything just like I did for SM 1.9 when preparing my build environment and I don't see this header file anywhere in my SM or MM folders.

A little guidance would be appreciated. Thanks!

The extension I'm trying to build is: https://github.com/Kenzzer/sendproxy which again builds perfectly fine in SM 1.9 but fails in SM 1.10 to the missing header file above. I just want to know where I went wrong.

**Comment by hydrogen-mvm** [comment]
Okay so I went digging further and found out that it's actually a separate repository:

https://github.com/alliedmodders/amtl/tree/eb7b6ba084e13c50f7c2c53b285e6e6af44accd9

I had to move the amtl folder (with the .h files) outside and copy am-string.h to the same place as IExtensionSys.h for it to successfully build.

I'm not sure if that's the right way to set this up???

**Comment by Headline** [comment]
I believe it was supposed to be `#include <am-string.h>`

**Comment by hydrogen-mvm** [comment]
Editing my AMBuildScript managed to do the trick without needing to move any folders around. Pasting here what I did in case it helps someone else:

![image](https://user-images.githubusercontent.com/29522123/69774073-d8ccf780-1162-11ea-8f9a-d73217b3ba15.png)

**Comment by hydrogen-mvm** [comment]
> 
> 
> I believe it was supposed to be `#include <am-string.h>`

That's not what's listed here though:

https://github.com/alliedmodders/sourcemod/blob/master/public/IExtensionSys.h#L37

**Comment by hydrogen-mvm** [comment]
Yeah sorry I'm dumb, that ended up being the proper fix:

https://github.com/SlidyBat/sendproxy/commit/f8f9f85366c7b528a5b666307c541d8d66374dc2

Anyone else who stumbles into this problem: Update your AMBuildScript for your extension.

Thanks and apologies for wasting everyone's time.
