### ISSUE TITLE
First index of int mouse[2] argument in OnPlayerRunCmd always shows 0

### ISSUE THREAD

**Issue by The-Doggy** [alliedmodders/sourcemod#1139]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: CentOS Linux release 7.7.1908
  * Game/AppID (with version if applicable): Half-Life 2: Deathmatch, AppID 232370, Version 5394425
  * Current SourceMod version: 1.10.0.6458
  * Current SourceMod snapshot: 1.11.6473
  * Current Metamod: Source snapshot: 1.11.1128
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Printing out the values of the mouse array during an OnPlayerRunCmd forward in Half-Life 2: Deathmatch (haven't tested any other games) will always show 0 for the first index however the second index seems to work as intended.

# Problematic Code (or Steps to Reproduce)
  ```
  #include <sdktools>

public Action OnPlayerRunCmd(int client, int& buttons, int& impulse, float vel[3], float angles[3], int& weapon, int& subtype, int& cmdnum, int& tickcount, int& seed, int mouse[2])
{
	PrintToChat(client, "CURRENT MOUSE = %i %i", mouse[0], mouse[1]);
	return Plugin_Continue;
}
  ```
Move mouse around while in game and the first value will never change from 0.

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.
![image](https://user-images.githubusercontent.com/19336809/70759456-591e6a00-1dab-11ea-9be6-8fdba1400159.png)

**Comment by SM9CC** [comment]
This is probably due to the game initializing mouse values during frame instead of tick.

As quoted by NCZ4 (NoCheatz) dev:

> This detection is not safe at all because the client game process mouse on frame rather than on tick.
			A client with higher FPS than tickrate will send legitimate 0 mouse values because mouse accum are processed and 0ed between ticks in this case.

**Comment by asherkin** [comment]
> This is probably due to the game initializing mouse values during frame instead of tick.

Pretty sure it is just the `CUserCmd` struct being outdated in the SDK - this happens quite regularly as the mouse values are near the end.

**Comment by SM9CC** [comment]
> 
> 
> > This is probably due to the game initializing mouse values during frame instead of tick.
> 
> Pretty sure it is just the `CUserCmd` struct being outdated in the SDK - this happens quite regularly as the mouse values are near the end.

Ah right.

**Comment by asherkin** [comment]
This seems to have been fixed at some point, the test plugin is working fine now.
