### ISSUE TITLE
SourceMod won't work on Blade Symphony after Harmonious Prelude update

### ISSUE THREAD

**Issue by samzanemesis** [alliedmodders/sourcemod#1140]
Hello

I'm the lead developer of Blade Symphony, our players are complaining that they aren't able to use SourceMod anymore in the game after we have deployed the Harmonius Prelude, with the CSGO branch, can anyone help us reintegrate SM support into Blade Symphony?

What needs to be done from our side to help integration?

I am providing the SourceMod developers privately debug symbols of our development builds

**Comment by asherkin** [comment]
Forgot this issue was open - I think the bulk of this should be fixed now but there is probably still some SDKTools gamedata needed.
