### ISSUE TITLE
dbi.mysql incompatability 

### ISSUE THREAD

**Issue by mgeerse** [alliedmodders/sourcemod#1150]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * **Operating System version:** 
(Ubuntu 18.04 64bit / Linux 4.15.0-70-generic)
  * **Game/AppID (with version if applicable):** 
740 CS:GO
  * **Current SourceMod & Metamod version:** 
SourceMod Version: 1.10.0.6456
SourcePawn Engine: 1.10.0.6456, jit-x86 (build 1.10.0.6456)
Metamod:Source Version Information
Metamod:Source version 1.11.0-dev+1126

  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Hello, I've first asked the plugin maker about this issue. He has referred me to here instead, saying that it's a problem related to the incompatibility of my database with dbi.mysql sourcemod driver.

The problem is that a player with a special name, such as `𝐌𝐎𝐑𝐆𝐀𝐃𝐎` or `𝓼𝔁𝓵𝓽𝔂` cannot be stored in a database. 

# Problematic Code (or Steps to Reproduce)

  ```
Database db;
char query[256];
Format(query, sizeof(buffer), "INSERT INTO steam_names(names) VALUES('%s'), GetPlayerName(client));
db.AddQuery(query);
db.Execute();
  ```
So in reality, when you want to store a playername into your database that is similar to `𝐌𝐎𝐑𝐆𝐀𝐃𝐎` or `𝓼𝔁𝓵𝓽𝔂`, it will not work. The name gets converted to `\xF0\x9F\x93\x97^1...` which I think represents a utf8mb4 string which is 4 bytes long instead of 3 from utf8. 

The new utf8mb4 is introduced in MySQL version 5.5.3, but I'm unsure against which driver SourceMod is build.

# Logs
The logs from the plugin looks as follows:
```
L 12/28/2019 - 00:50:35: Info (map "de_mirage") (file "/home/container/csgo/addons/sourcemod/logs/errors_20191228.log")
L 12/28/2019 - 00:50:35: [levelsranks.smx] SQL_Callback Error (8546): Incorrect string value: '\xF0\x9F\xA4\xA7' for column 'name' at row 1
```

I hope to have informed you enough.

**Comment by asherkin** [comment]
SM 1.10 has had support for the utf8mb4 charset for over 2 years.

**Comment by mgeerse** [comment]
Hello @asherkin, I've spoken in person with the plugin developer and he has confirmed to me once again that the problem lies within the dbi.mysql compatability.

He has given me a dev version that sets the table to utf8mb4, but this also doesn't work. As he claims it, the problem lies with sourcemod. Don't shoot the messenger. 

[!code]https://cdn.discordapp.com/attachments/660538495462539291/660563458294546489/unknown.png)[/img]

**Comment by peace-maker** [comment]
Are the tables created using the utf8mb4 charset? Check the `CREATE TABLE` statements.

**Comment by mgeerse** [comment]
Yes they are. The client, connection and server are all using utf8mb4. The database, table and column are also set to use utf8mb4. So far I have not found a fix

**Comment by peace-maker** [comment]
Are they set in your live database as well? Sorry, but the problem is on your end. We even use new api only available in the MySQL 5.5 client library, where utf8mb4 was introduced, so accidentally compiling against an older version wouldn't work.

**Comment by mgeerse** [comment]
Everything that is adjustable I have adjusted to utf8mb4

/etc/mysqld/my.cnf:
```
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_general_ci
```

Field | Type | Collation | Null | Key | Default | Extra | Privileges | Comment |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
steam | varchar(22) | utf8mb4_general_ci | NO | PRI | NULL |   | select,insert,update,references |  
name | varchar(32) | utf8mb4_general_ci | NO |   |   |   | select,insert,update,references | 

Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time | Update_time | Check_time | Collation | Checksum | Create_options | Comment |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
lvl_retakes_base | InnoDB | 10 | Dynamic | 2356 | 111 | 262144 | 0 | 0 | 0 | NULL | 2019-12-31 01:46:23 | 2020-01-01 13:13:34 | NULL | utf8mb4_general_ci | NULL |   |  

  | Database | Collation |  
-- | -- | -- | --
  | lvl_retakes_base | utf8mb4_general_ci | 


Just hitting a brick wall again and again

**Comment by peace-maker** [comment]
Maybe your fields are too small and the name gets truncated mid multibyte char. 32 vs. 128.

This issue tracker isn't the right place for such questions though.

**Comment by mgeerse** [comment]
This issue was originally made because the plugin author asked me to, but I've indeed gone off topic. I've had a lot of help on the SourceMod discord without any luck. Thanks for your time anyway, I really do appreciate it.

**Comment by crashzk** [comment]
Sorry to revive this topic, but managed to solve @mgeerse, I'm having this problem even following all the information here, nothing to solve.
