### ISSUE TITLE
GetSteamAccountID(client, false) returns 0 when GetClientAuthId(client, AuthId_Steam3, steamid, sizeof(steamid), false); returns a non-zero number

### ISSUE THREAD

**Issue by bottiger1** [alliedmodders/sourcemod#1157]
As explained in the title, I am setting verify to false for both functions. But GetSteamAccountID returns 0 for unverified clients while GetClientAuthId returns a non zero value.

> liljimy100<3297><STEAM_ID_PENDING><> GetSteamAccountID was 0. GetClientAuthId [U:1:999357900]

**Comment by asherkin** [comment]
https://github.com/alliedmodders/sourcemod/blob/00b7ac5a39f9b6ffddfabc18e310ca1184fedbc1/core/PlayerManager.cpp#L2241

It isn't passing the `validated` param through to `GetSteamId` here, I suspect that is the cause.

**Comment by bottiger1** [comment]
https://github.com/alliedmodders/sourcemod/pull/1158
