### ISSUE TITLE
ConVar handles leak

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1166]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 9 / Windows
  * Game/AppID (with version if applicable): 500, 550
  * Current SourceMod version: 1.10.6460
  * Current SourceMod snapshot: 1.10.6460
  * Current Metamod: Source snapshot:
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Problematic Code (or Steps to Reproduce)
  ```
	// Test
	ConVar t = CreateConVar("TTTTT", "0.1");
	PrintToServer("T0 %d %d", t, FindConVar("TTTTT")); // SAME
	PrintToServer("T1 %d", FindConVar("tTTTT")); // ALWAYS DIFFERENT
	PrintToServer("T2 %d", FindConVar("TtTTT")); // ALWAYS DIFFERENT
	PrintToServer("T3 %d", FindConVar("TTtTT")); // ALWAYS DIFFERENT

	// Real cvar registered as: Smoker_escape_range
	PrintToServer("A %d", FindConVar("smoker_escape_range")); // ALWAYS DIFFERENT
	PrintToServer("B %d", FindConVar("smoker_escape_range")); // ALWAYS DIFFERENT
	PrintToServer("C %d", FindConVar("smoker_escape_range")); // ALWAYS DIFFERENT
	PrintToServer("D %d", FindConVar("Smoker_escape_range")); // ALWAYS SAME
	PrintToServer("E %d", FindConVar("Smoker_escape_range")); // ALWAYS SAME
	PrintToServer("F %d", FindConVar("Smoker_escape_range")); // ALWAYS SAME
  ```

# Description
Most people write cvar names to server.cfg in all lower case. The same is true for 3rd party plugins. 
This causes ConVar leaks on each map start for some specific cvars. Example: 
"Smoker_escape_range" - this is how it is registered (first letter is in uppercase) 
https://developer.valvesoftware.com/wiki/List_of_L4D2_Cvars

When FindConVar() searches for an already registered global handle, looks like it doesn't ignore case sensitivity and each time creates a new ConVar handle.

So, after 1 day my dump of ConVars grows 1000 -> 2000, causing multiple server lags.

**Comment by Headline** [comment]
Can you please paste the output of the test plugin directly

**Comment by dragokas** [comment]
sure,

```
T0 136578465 136578465
T1 136644233
T2 136709525
T3 136775055
A 136840840
B 136906378
C 136971626
D 137037466
E 137037466
F 137037466
```

**Comment by asherkin** [comment]
Thanks! This is a good find and a great bug report.

**Comment by dragokas** [comment]
sure, 6 hours to debug everything and understand the concrete reason :D

**Comment by SM9CC** [comment]
Thank you! Hopefully this is an easy fix.
