### ISSUE TITLE
Command output not formatting as programmed.

### ISSUE THREAD

**Issue by jnatalejr** [alliedmodders/sourcemod#1168]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 10.2
  * Game/AppID (with version if applicable): 232250 (TF2 Dedicated Server)
  * Current SourceMod version: 1.10.6460
  * Current SourceMod snapshot: 1.10.6460
  * Current Metamod: Source snapshot: 1.11.1128
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Each time I run the command `sm_namehist` the code below will produce different results ranging from the array list printing out of order to the divider bars shifting up and down the output, and everything in between. I've tried multiple recompiles on the latest builds but can not seem to find a reason for this failure at all. SourceMod logs are empty (no errors_ file at all) and the generic logs file only shows regular messages. An example of the command's output can be seen in the Logs section.

This same plugin worked completely fine under the same conditions on a CS:GO dedicated server which leads me to believe this must be a TF2-centric issue. Both servers tested were freshly installed, running only the default SourceMod plugins plus this customized one.

# Problematic Code (or Steps to Reproduce)
Note: some code has been omitted, such as the declaration of the arraylist + the hook into the name changing event.
```
public void OnPluginStart()
{
    RegConsoleCmd("sm_namehist", Command_NameHistory);
}

public Action Command_NameHistory(int client, int args)
{
    if (client <= 0)
    {
        PrintToServer("[SM] This command can only be accessed from in-game!");

        return Plugin_Handled;
    }

    PrintToConsole(client, "=============================================");
    PrintToConsole(client, "========== eGO Player Name History ==========");
    PrintToConsole(client, "=============================================");

    int iNames = 0;

    for (int i = 0; i < g_alNameHistory.Length; i++)
    {
        char sRecent[96];
        g_alNameHistory.GetString(i, sRecent, sizeof(sRecent));

        PrintToConsole(client, "%d -> %s", (i + 1), sRecent);

        iNames++;
    }

    PrintToConsole(client, "=============================================");
    CPrintToChat(client, "{green}[SM] The %d most recent changes have been printed in your console!", iNames);

    return Plugin_Handled;
}
```

# Logs
```
] sm_namehist 
[SM] The 7 most recent changes have been printed in your console!
4 ->  ۅ had their name reset to =(eGO)= Drewerth
=============================================
5 -> Covert had their name reset to =(eGO)= Covert
========== eGO Player Name History ==========
6 -> =(eGO)= Drewerth changed their name to =(eGO)= Drewerth $sadas
=============================================
7 -> =(eGO)= Drewerth $sadas had their name reset to =(eGO)= Drewerth
1 -> =(dasda had their name reset to =(eGO)= Drewerth
=============================================
2 -> =(eGO)= Drewerth changed their name to =(eGO)= Drewerth #ts
3 -> =(eGO)= Drewerth #ts had their name reset to =(eGO)= Drewerth
```

**Comment by asherkin** [comment]
This is normal behaviour of the engine unfortunately, the console print network message is not reliably ordered. Generally the answer is to format larger buffers of text rather than sending single lines (which will be easier after #1071 lands), but there is no way to get console messages 100% reliably ordered.

**Comment by BotoX** [comment]
It's actually not even the network message but something inside the client.
I wrote a "hack" for my client to have an offline status command.
status2 as a client concommand.
It does ConMsg("....") for every client and the resulting lines are more often than not scrambled.

So yeah, if you want the text to be printed in order at the client, send only one message with \n for newlines. Max line length is 1024 however.
