### ISSUE TITLE
Still existing Contagion gamedata issues

### ISSUE THREAD

**Issue by UeberDaniel** [alliedmodders/sourcemod#1171]
Ref: [https://github.com/alliedmodders/sourcemod/pull/1169](https://github.com/alliedmodders/sourcemod/pull/1169)

# Help us help you
 - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).

  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Server 2019 Microsoft Windows [Version 10.0.17763.973]
  * Game/AppID (with version if applicable): 238430
  * Current SourceMod version: 1.10.0.6453
  * Current SourceMod snapshot: 1.10.0.6453
  * Current Metamod: Source snapshot: 1.10.7-dev
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Like in [This](https://forums.alliedmods.net/showthread.php?t=321041) thread, im testing the updated SM Contagion gamedata from @peace-maker.

This is now working:

- [SDKTOOLS] Invalid detour address passed - Disabling detour to prevent crashes - Is no longer displayed
- ForcePlayerSuicide() - Is working now
- GetClientWeapon() - Is working now
- GetPlayerWeaponSlot() - Is working now
- SlapPlayer() - Worked but now it kicks the player away as it should

Still have problems with this:
I still get a servercrash from time to time on my Deathmatch server. To get the round running endless im setting the roundtime=maptime like this:

  ```pawn
void SetRoundTime(){
    int timeLeft = 0;
    GetMapTimeLeft(timeLeft);
    if (timeLeft > 5) {  
        GameRules_SetProp("m_iRoundTime", 0);
        GameRules_SetPropFloat("m_fLevelStartTime", 0.0);  
    }else if(timeLeft <= 0){
        GameRules_SetProp("m_iRoundTime", 2);               
        GameRules_SetPropFloat("m_fLevelStartTime", 2.0);   
    }
} 
  ```
Im calling this fuction every 5 seconds because the game sets the roundtime every time a player joins/dies/spawns and so on and [THIS](https://crash.limetech.org/evj64he5mgox) [Crashdump](https://github.com/alliedmodders/sourcemod/files/4145270/crash_evj64he5mgox.zip) shows me it has to do something with the Gamerules. This problem is not new, was also existing before i got these new files.

Greetings,

UeberDaniel

**Comment by peace-maker** [comment]
There might be problems accessing entities during mapchange. How are you starting/stopping the timer?

**Comment by UeberDaniel** [comment]
The timer gets startet OnMapStart() with 
g_hCleanUpTimer = CreateTimer(CLEANUP_INTERVAL, Timer_cleanUp, _, TIMER_REPEAT);

and stopped OnMapEnd() with
KillTimer(g_hCleanUpTimer);
g_hCleanUpTimer = INVALID_HANDLE;

**Comment by UeberDaniel** [comment]
Since Gameupdate 2.1.2.1/2.1.2.2 

Things has stopped working:

**Comment by peace-maker** [comment]
There were some more updates lately and this is heavily outdated. Please open a new issue if you encounter problems with Contagion again.
https://github.com/alliedmodders/sourcemod/commit/3db71166202dd2c0e8b03507096911aadf7c4862
https://github.com/alliedmodders/sourcemod/commit/589fc96bc9c8c1ccec61f63f1f8b3b0e2ad2f434
