### ISSUE TITLE
SMCParser: add valve file system support

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1182]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 9
  * Game/AppID (with version if applicable): 500
  * Current SourceMod version: 1.10.6454
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Unlike, OpenFile(), SMCParser.ParseFile() doesn't have arguments to switch to using valve file system.
Please, add support.
https://sm.alliedmods.net/new-api/textparse/SMCParser/ParseFile

# Problematic Code (or Steps to Reproduce)
See: https://github.com/alliedmodders/sourcemod/issues/1181

# Use case
Mission manager plugins

**Comment by psychonic** [comment]
Are there actually third-parties shipping SMC files in VPKs/maps? Or are you trying to read KV file?

**Comment by dragokas** [comment]
yes,

vpk -> /missions/xxx.txt

**Comment by asherkin** [comment]
> yes,
> 
> vpk -> /missions/xxx.txt

SMC is a custom file format developed for SourceMod, those are not SMC files.

**Comment by dragokas** [comment]
What you mean. That file is in KV format.

Here is example of plugin that uses SMC Parser to parse that files from vpk:
https://forums.alliedmods.net/showthread.php?p=2600137

**Comment by dragokas** [comment]
Since SMC Parser doesn't support valve file system, that author forced to copy txt files to normal directory first. This is not OK.

**Comment by psychonic** [comment]
The SMC parser can work with some KeyValues files because the SMC format is similar to the Valve KeyValues formet. It is not compatible with all of them, and the KeyValues parser/API should be used with KeyValues files.
