### ISSUE TITLE
Mapchooser: Reducing the value "sm_mapvote_exclude" requires server reboot

### ISSUE THREAD

**Issue by stickz** [alliedmodders/sourcemod#1206]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Ubuntu 18.04
  * Game/AppID (with version if applicable): 17710
  * Current SourceMod version: 1.10.0
  * Current SourceMod snapshot: 6453
  * Current Metamod: Source snapshot: 1.10.7-dev

# Description
When I reduce the value of `"sm_mapvote_exclude"` in `mapchooser.cfg`, I have to reboot my server for the changes to take effect. The length of the old map ArrayList is not updated.

# Problematic Code (or Steps to Reproduce)
```
public void OnMapEnd()
{
      	char map[PLATFORM_MAX_PATH];
	GetCurrentMap(map, sizeof(map));
	RemoveStringFromArray(g_OldMapList, map);
	g_OldMapList.PushString(map);
				
	if (g_OldMapList.Length > g_Cvar_ExcludeMaps.IntValue)
	{
		g_OldMapList.Erase(0);
	}
}
```
# Solution
```
while (g_OldMapList.Length > g_Cvar_ExcludeMaps.IntValue)
{
      g_OldMapList.Erase(0);
}
```
**See pull request** #1197.

**Comment by wanted241** [comment]
https://github.com/alliedmodders/sourcemod/pull/1197
