### ISSUE TITLE
Feature update: PrintToChat/PrintCenterText/PrintHintText

### ISSUE THREAD

**Issue by Nullent** [alliedmodders/sourcemod#1210]
Hi everyone,
these functions currently have a useless exception: ("Could not send a usermessage").
What about change it to `true/false` on return and stop sending this exception. This will not break anything and will give us more opportunities

**Comment by asherkin** [comment]
It isn't useless - errors are used to indicate misuse of the API that can be avoided by the calling code, return values are used to indicate failures that could not be predicted.

It might help if you included some detail about what problem you're having with this error, please [read about what we expect in issue reports](https://github.com/alliedmodders/sourcemod/blob/master/.github/CONTRIBUTING.md#issue-reports).

**Comment by whyAries** [comment]
> It isn't useless - errors are used to indicate misuse of the API that can be avoided by the calling code

I'm afraid the calling code won 't let us know why protobuf or bitbuffer returned NULL and an exception later, unless you read the entire stack trace: https://github.com/alliedmodders/sourcemod/blob/ecad8f25a838f4ec0c2f9cfe956d18008470db3d/core/HalfLife2.cpp#L521-L524
https://github.com/alliedmodders/sourcemod/blob/ecad8f25a838f4ec0c2f9cfe956d18008470db3d/core/smn_halflife.cpp#L341-L344

This applies to all functions from the header. You can always specify why `true/false` was returned in the function documentation.
**This does not apply to other exceptions**

**Comment by asherkin** [comment]
There is only one case you're not allowed to send a usermessage, and that is from inside a usermessage hook.

**Comment by whyAries** [comment]
> There is only one case you're not allowed to send a usermessage, and that is from inside a usermessage hook.

And so I ask that the functions : PrintToChat/PrintCenterText/PrintHintText return: true - if success or false, but not this:
https://github.com/alliedmodders/sourcemod/blob/ecad8f25a838f4ec0c2f9cfe956d18008470db3d/core/smn_halflife.cpp#L343

**Comment by Headline** [comment]
The failure of the call is solely based on the one condition asherkin mentioned above. This is programmer error and avoidable
