### ISSUE TITLE
CCSPlayer::SwitchTeam( 1 ) - invalid team index

### ISSUE THREAD

**Issue by neatek** [alliedmodders/sourcemod#1215]
# Help us help you
  - [ok] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ok] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ok] I can always reproduce the issue with the provided description below.

# Environment
Server CS:Source / Windows 64

Build Label:           5394425   # Uniquely identifies each build
Network PatchVersion:  5394425   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
Server version:        5394425
Server AppID:           232330

SourceMod Version Information:
    SourceMod Version: 1.10.0.6478
    SourcePawn Engine: 1.10.0.6478, jit-x86 (build 1.10.0.6478)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Mar  5 2020 10:59:39
    Built from: https://github.com/alliedmodders/sourcemod/commit/a8b9da9a
    Build ID: 6478:a8b9da9a
    http://www.sourcemod.net/

Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/6c8495f
Build ID: 971:6c8495f
Loaded As: Valve Server Plugin
Compiled on: Mar 28 2019
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/ 

# Description
CCSPlayer::SwitchTeam( 1 ) - invalid team index 
Server is clear, with fresh install of sourcemod / mm
Also, when i switch player from 2 or 3 team to 1 (spec), player have 1 health... (with ChangeClientTeam) 

# Problematic Code (or Steps to Reproduce)
  ```
CS_SwitchTeam(client, 1); (CCSPlayer::SwitchTeam( 1 ) - invalid team index.)
  ```
  ```
ChangeClientTeam(client, 1); (1health after change team to 1)
  ```

# Logs
CCSPlayer::SwitchTeam( 1 ) - invalid team index.
CCSPlayer::SwitchTeam( 1 ) - invalid team index.
CCSPlayer::SwitchTeam( 1 ) - invalid team index.
CCSPlayer::SwitchTeam( 1 ) - invalid team index.

![wtf](https://user-images.githubusercontent.com/3075678/76789327-a60c4500-67cd-11ea-9bd9-817f750e6be9.jpg)
No logs in Sourcemod/logs. Only in Console i see this error/warning

https://forums.alliedmods.net/showthread.php?p=2687234#post2687234

**Comment by PlayBoy31** [comment]
SwitchTeam is only between team 2 or 3
team 0 = unassigned
team 1 = spectator
