### ISSUE TITLE
OnClientCommand parse multibyte incorrectly

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1248]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 10
  * Game/AppID (with version if applicable): 500, 730
  * Current SourceMod version: 1.11.6526
  * Current SourceMod snapshot: 1.11.6526
  * Current Metamod: Source snapshot: 1.10.7-dev
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
When you enter cyrillic command to console, OnClientCommand always put 1-st byte to 0 argument, and all other bytes to 1-st agument.

# Problematic Code (or Steps to Reproduce)
  ```
public Action OnClientCommand(int client, int args)
{
	char cmd[64];
	char arg[128];
	
	GetCmdArg(0, cmd, sizeof cmd);
	
	PrintToChatAll("Length of cmd: %i", strlen(cmd)); // always 1 byte
	PrintToChatAll("cmd: %s", cmd);
	
	if ( args )
	{
		GetCmdArgString(arg, sizeof arg);
		
		PrintToChatAll("Length of arg: %i", strlen(arg));
		PrintToChatAll("arg: %s", arg);
		
		// fixing the command
		Format(cmd, sizeof cmd, "%s%s", cmd, arg);
	}
	
	PrintToChatAll("Fixed cmd: %s", cmd);

	return Plugin_Continue;
}
  ```

# Logs
Example when you enter in console:
```
Привет
```
Output:
![mb](https://user-images.githubusercontent.com/19956568/80307747-b273bc80-87d3-11ea-8829-ba9c69085c86.png)

**Comment by ambaca** [comment]
...I would say, this is in-game problem. It can't handle all symbols. It maybe work as ANSI format.

**Comment by asherkin** [comment]
![image](https://user-images.githubusercontent.com/865360/126084131-c006dde9-1f3b-4371-827a-0a1aa919ccbb.png)

Unfortunately this definitely seems to be an engine issue and there is nothing we can do about it. I also set a breakpoint in `IServerGameClients::ClientCommand` and inspected the `CCommand` values and it is all the same there before it has even reached SM.
