### ISSUE TITLE
[REQ] FindSendPropInfo with array support ? To get array PropFieldType

### ISSUE THREAD

**Issue by ambaca** [alliedmodders/sourcemod#1258]
# Description
Feature request: FindSendPropInfo with array support ?
- Easier way to check array PropFieldType

# Problematic Code (or Steps to Reproduce)
  ```sourcepawn
	char cls[64];
	char prop[] = "m_hMyWeapons";

	if(HasEntProp(client, Prop_Send, "m_hMyWeapons"))
	{
		GetEntityNetClass(client, cls, sizeof(cls));		
		offset = FindSendPropInfo(cls, prop, type, num_bits, local_offset);

		
		switch(type)
		{
			case PropField_Unsupported:
			{
				arraysize = GetEntPropArraySize(client, Prop_Send, prop);
				
				// How get PropFieldType from array ?
				//offset = FindSendPropInfo(cls, prop, type, num_bits, local_offset);

				for(int y = 0; y < arraysize; y++)
				{
					// Hacky hacky, "m_b*", "m_f*", "m_h*" etc. etc.
					if(StrContains(prop, "m_f", true) == 0)
					{
						float m_fnewvalue = GetEntPropFloat(client, Prop_Send, prop, y);
						...
					}
					else if(StrContains(prop, "m_i", true) == 0)
					{
						int newvalue = GetEntProp(client, Prop_Send, prop, _, y);
						...
					}
				}
			}
		}
		
	}
  ```

**Comment by psychonic** [comment]
I'm not sold on using name-based heuristics for this. Valve are not always consistent with correct naming to types.

At minimum, the sample would have to be adjusted a bit. m_f is usually used for flag values (bitfield integers) where m_fl would be float. And m_n would need to be added for unsigned integers.

**Comment by ambaca** [comment]
Thanks for answer.
But this was a bad code example of mine, what I really wanted:
- Request to get PropFieldType from netprop Array.

Is there already native for this ?
It this hard to implement ?
