### ISSUE TITLE
Black Mesa

### ISSUE THREAD

**Issue by Geromo94** [alliedmodders/sourcemod#1261]
Hello, i am install sourcemod in Black Mesa (Steam)
But command in adminmenu — kill player, kick player it's not working. 
Nothing happens. Please help :c

--------------------------------------------
Build Label:            100001   # Uniquely identifies each build
Network PatchVersion:   100001   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
Server version:         100001
Server AppID:           346680
Client version:         100001
Client AppID:           362890
--------------------------------------------
Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/6c8495f
Loaded As: Valve Server Plugin
Build ID: 971:6c8495f
Compiled on: Mar 28 2019
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/
--------------------------------------------
 SourceMod Version Information:
    SourcePawn Engine: 1.10.0.6488, jit-x86 (build 1.10.0.6488)
    SourceMod Version: 1.10.0.6488
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Apr 30 2020 16:35:23
    Built from: https://github.com/alliedmodders/sourcemod/commit/afb40f1d
    Build ID: 6488:afb40f1d
    http://www.sourcemod.net/

**Comment by PlayBoy31** [comment]
Works for me, have you correctly bind the slots keys to navigate on menus ?

**Comment by Geromo94** [comment]
[SM] Listing 17 plugins:
  01 "Admin File Reader" (1.10.0.6488) by AlliedModders LLC
  02 "Admin Help" (1.10.0.6488) by AlliedModders LLC
  03 "Admin Menu" (1.10.0.6488) by AlliedModders LLC
  04 "Anti-Flood" (1.10.0.6488) by AlliedModders LLC
  06 "Basic Chat" (1.10.0.6488) by AlliedModders LLC
  05 "Basic Ban Commands" (1.10.0.6488) by AlliedModders LLC
  07 "Basic Comm Control" (1.10.0.6488) by AlliedModders LLC
  08 "Basic Commands" (1.10.0.6488) by AlliedModders LLC
  10 "Basic Votes" (1.10.0.6488) by AlliedModders LLC
  11 "Client Preferences" (1.10.0.6488) by AlliedModders LLC
  09 "Basic Info Triggers" (1.10.0.6488) by AlliedModders LLC
  12 "Fun Commands" (1.10.0.6488) by AlliedModders LLC
  13 "Fun Votes" (1.10.0.6488) by AlliedModders LLC
  17 "Sound Commands" (1.10.0.6488) by AlliedModders LLC
  14 "Player Commands" (1.10.0.6488) by AlliedModders LLC
  15 "Reserved Slots" (1.10.0.6488) by AlliedModders LLC
  16 "SM Advanced Teleport" (1.0) by LightningZLaser
------------------------------------------------------------------
[SM] Displaying 7 extensions:
[01] Automatic Updater (1.10.0.6488): Updates SourceMod gamedata files
[02] Webternet (1.10.0.6488): Extension for interacting with URLs
[04] SDK Tools (1.10.0.6488): Source SDK Tools
[03] Top Menus (1.10.0.6488): Creates sorted nested menus
[05] BinTools (1.10.0.6488): Low-level C/C++ Calling API
[06] Client Preferences (1.10.0.6488): Saves client preference settings
[07] SQLite (1.10.0.6488): SQLite Driver

**Comment by Headline** [comment]
Closing this as stale - if this is still an issue please reopen!
