### ISSUE TITLE
Issues from the recent builds [spcomp.exe especially, CS:GO Sv. OnClientPutInServer crash]

### ISSUE THREAD

**Issue by ClaudiuHKS** [alliedmodders/sourcemod#1286]
# Help us help you
  - [✔] Have checked my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [✔] Can always reproduce the issue with the description below.

# Environment
  * OS: ``Microsoft Windows 10 Enterprise Insider Preview 10.0.19631``
  * Game/ AppID: ``730`` cl ``740`` sv ``CS:GO`` game
  * SourceMod version: ``1.11``
  * SourceMod snapshot: ``1.11.0-manual``, always the newest from the list (that works & can be downloaded for ``Windows``)
  * MetaMod: Source snapshot: ``1.11.1130``
  - [✖] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens. ``I don't use stable versions.``
  - [✔] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [✔] I have updated MetaMod: Source to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Guys, since ``spcomp.exe`` is ``464 Kb`` (Build # ``6545`` is ``453 Kb``), characters form ``.sp`` that are looking like ``ăîâșțĂÎÂȘȚ`` don't show correctly with ``UTF-8`` encoding (didn't try ``UTF-8-BOM`` ``.sp`` encoding yet and also don't wanna try). Just saying.
Also, with Build # ``6562``, the game server crashes when the client puts in server on Windows.
Wasn't able to test Build # ``6563`` and ``6565`` because lack of Windows release to be downloaded from [the Dev. branches](https://www.sourcemod.net/downloads.php?branch=dev).

Tested with ``CS:GO`` game [``730`` cl ``740`` sv Steam(tm) ``AppID``].

I note that I actually run Build # ``6559`` and works perfectly on [my public community dedicated CS:GO game server](https://www.gametracker.com/server_info/89.40.104.207:27015/).

I note that I actually run ``compile.exe`` & ``spcomp.exe`` from the Build # ``6545``.

**Comment by dvander** [comment]
Can you attach a test script and describe how to reproduce the problem?

**Comment by ClaudiuHKS** [comment]
[testscript.zip](https://github.com/alliedmodders/sourcemod/files/4712597/testscript.zip)

This is for the ``spcomp.exe`` issue. About the ``OnClientPutInServer`` crash I have no idea yet, I will come back with a message soon. I mean, I have no idea if it crashes with a specific plug-in or it crashes even without any plug-in at all too.

**Comment by ClaudiuHKS** [comment]
I am back.

Build # ``6559`` /csgo/addons/sourcemod/bin/* ``OK`` & /csgo/addons/sourcemod/extensions/* ``OK``
Build # ``6562`` /csgo/addons/sourcemod/bin/* ``FAIL`` & /csgo/addons/sourcemod/extensions/* ``OK``

This is how to reproduce a crash after OnClientPutInServer is called, with a ``PrintToChatAll`` call: [hattricks_connect_announcer.zip](https://github.com/alliedmodders/sourcemod/files/4712817/hattricks_connect_announcer.zip)

Note, I use ``bot_quota 6`` & ``bot_join_after_player 0`` in my testing game server. These two values are not the default values for these ConVars. Just saying.

I note that I have no idea if there are any other calls causing crashes. I have just found this one for now.

**Comment by dvander** [comment]
Thanks, I'll test this today.

**Comment by dvander** [comment]
The utf8 issue should be fixed. I'll test the crash as soon as I can.
