### ISSUE TITLE
Command "sm plugins reload X" does not respond

### ISSUE THREAD

**Issue by Ramu3404** [alliedmodders/sourcemod#1289]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Win10
  * Game/AppID (with version if applicable): CS:S
  * Current SourceMod version: 1.11.0.6484
  * Current Metamod: Source snapshot: 1.10.7-dev

# Description
Command "sm plugins reload X" does not respond properly like similar commands do (but still prints to server console)

# In-Game console log
> ] sm_rcon sm plugins list
> [SM] Listing 18 plugins:
>   01 "Admin File Reader" (1.11.0.6484) by AlliedModders LLC
>   02 "Admin Help" (1.11.0.6484) by AlliedModders LLC
>   03 "Admin Menu" (1.11.0.6484) by AlliedModders LLC
>   04 "Anti-Flood" (1.11.0.6484) by AlliedModders LLC
>   05 "Basic Ban Commands" (1.11.0.6484) by AlliedModders LLC
>   06 "Basic Chat" (1.11.0.6484) by AlliedModders LLC
>   07 "Basic Comm Control" (1.11.0.6484) by AlliedModders LLC
>   08 "Basic Commands" (1.11.0.6484) by AlliedModders LLC
>   09 "Basic Info Triggers" (1.11.0.6484) by AlliedModders LLC
>   10 "Basic Votes" (1.11.0.6484) by AlliedModders LLC
>   11 "Client Preferences" (1.11.0.6484) by AlliedModders LLC
>   12 "Fun Commands" (1.11.0.6484) by AlliedModders LLC
>   13 "Fun Votes" (1.11.0.6484) by AlliedModders LLC
>   14 "Nextmap" (1.11.0.6484) by AlliedModders LLC
>   15 "Player Commands" (1.11.0.6484) by AlliedModders LLC
>   16 "Reserved Slots" (1.11.0.6484) by AlliedModders LLC
>   17 "Sound Commands" (1.11.0.6484) by AlliedModders LLC
>   18 "myplugs\myanim.smx"
> 
> ] sm_rcon sm plugins unload myplugs/myanim
> [SM] Plugin myplugs\myanim.smx will be unloaded on the next frame.
> 
> ] sm_rcon sm plugins load myplugs/myanim
> [SM] Loaded plugin myplugs\myanim.smx successfully.
> 
> ] sm_rcon sm plugins reload myplugs/myanim

**Comment by peace-maker** [comment]
We could print a similar message to the `unload` command about the plugin being reloaded on the next frame.

**Comment by Ramu3404** [comment]
Thank you for fast reponse.
I am also having this problem when using ServerCommandEx thing, if it is going to work too then it is what i needed.
