### ISSUE TITLE
Add a Windows x64 build of libpcre for the regex extension

### ISSUE THREAD

**Issue by peace-maker** [alliedmodders/sourcemod#1294]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 64-bit
  * Game/AppID (with version if applicable): Insurgency
  * Current SourceMod version: master
  * Current SourceMod snapshot: master
  * Current Metamod: Source snapshot: master
  - [X] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [X] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [X] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

The regex extension is linking against prebuilt libpcre libraries. The library for Windows x64 is missing, so the extension can't be compiled for that OS combo. Please add a windows64 build and/or provide the build config used to produce those libraries.

**Comment by Headline** [comment]
Now that we can use the c++ standard library, can we drop this dependency and just rely on `std::regex`?

@dvander

**Comment by asherkin** [comment]
> Now that we can use the c++ standard library, can we drop this dependency and just rely on `std::regex`?

Doesn’t look like it, not without losing features and likely plugin breakage. std::regex doesn’t implement the PCRE syntax and seems to be a lot slower.

**Comment by KyleSanderson** [comment]
std::regex is detritus. I ended up using golang for a time-constrained assignment after using it for 20m and it just wouldn't find any named matches.
