### ISSUE TITLE
handle ADMFLAG_RCON in some way

### ISSUE THREAD

**Issue by eyal282** [alliedmodders/sourcemod#1305]
I won't start a pull request yet because it just won't work like that. For now I'll mention why rcon is bad when root exists:

Rcon is capable of executing commands that bypass immunity, like root does but undocumented. It is done with sm_rcon sm_ban target

Rcon is able to give non admins the rcon status

Rcon is able to execute all non menu commands.

The main issue is most servers wouldn't know what rcon means and it can cause issues when the second strongest flag can do 90% of what root does, without sufficient documentation on how it gives so many possibly unintended rights. Whether to mark rcon deprecated, remove it or document it is sometimes I'm not sure how to do.

**Comment by Headline** [comment]
the rcon flag cannot and should not be removed or deprecated, but adding a little warning in the comment linked below may be appropriate

https://github.com/alliedmodders/sourcemod/blob/611bad40369dd16aeecbc2b7370fc2397f9ae987/configs/admin_levels.cfg#L26
