### ISSUE TITLE
add native to uninherit an admin group

### ISSUE THREAD

**Issue by eyal282** [alliedmodders/sourcemod#1312]
My goal is to allow an admin to assign himself as the event manager which will assign him the admin group which I can add overrides from there. There is a native for inheriting, but no native to undo it.

https://sm.alliedmods.net/new-api/admin/AdminInheritGroup

**Comment by asherkin** [comment]
This would require a major re-work of the admin system - groups are not a list of things attached to an admin, when an admin inherits the permissions of a group they are added directly to the admin permissions.

The general pattern here is to drop the admin, then re-create it from config without adding the additional group.

**Comment by eyal282** [comment]
Not gonna happen or not gonna happen soon?

**Comment by dvander** [comment]
The gain seems pretty small compared to the workaround asherkin suggested, so probably "not gonna happen", unless you're offering to do the refactoring :)

**Comment by KyleSanderson** [comment]
ACK - this isn't a present bug, but an enhancement via PR is always welcome 😄
