### ISSUE TITLE
IGamePlayer::GetName with multibyte characters

### ISSUE THREAD

**Issue by shqke** [alliedmodders/sourcemod#1315]
Following https://forums.alliedmods.net/showthread.php?t=305561 
Game: Left 4 Dead 2
```Dump of assembler code for function _ZN7CPlayer7GetNameEv:
   0xe9519b50 <+0>:     push   %ebp
   0xe9519b51 <+1>:     mov    %esp,%ebp
   0xe9519b53 <+3>:     sub    $0x8,%esp
   0xe9519b56 <+6>:     mov    0x8(%ebp),%ecx
   0xe9519b59 <+9>:     mov    0x38(%ecx),%eax
   0xe9519b5c <+12>:    test   %eax,%eax
   0xe9519b5e <+14>:    je     0xe9519b72 <_ZN7CPlayer7GetNameEv+34>	// if (m_Info && ...
   0xe9519b60 <+16>:    mov    0x34(%ecx),%edx
   0xe9519b63 <+19>:    cmpl   $0x0,0xc(%edx)
   0xe9519b67 <+23>:    je     0xe9519b72 <_ZN7CPlayer7GetNameEv+34>
   0xe9519b69 <+25>:    mov    (%eax),%ecx				// ... m_pEdict->GetUnknown())
   0xe9519b6b <+27>:    mov    %eax,(%esp)
   0xe9519b6e <+30>:    call   *(%ecx)
   0xe9519b70 <+32>:    jmp    0xe9519b7f <_ZN7CPlayer7GetNameEv+47>	// return m_Info->GetName();
   0xe9519b72 <+34>:    mov    0x8(%ecx),%ecx
   0xe9519b75 <+37>:    test   %ecx,%ecx
   0xe9519b77 <+39>:    mov    $0xe95af817,%eax
=> 0xe9519b7c <+44>:    cmovne %ecx,%eax				// return m_Name.c_str();
   0xe9519b7f <+47>:    add    $0x8,%esp
   0xe9519b82 <+50>:    pop    %ebp
   0xe9519b83 <+51>:    ret
End of assembler dump.
```
^ Marked instruction only gets executed during initial connect, then #545 appears to be useless.

Could you tell why not return m_Name [here](https://github.com/alliedmodders/sourcemod/blob/master/core/PlayerManager.cpp#L2281)?
Could I make a PR to return m_Name or should I change IGamePlayer interface's method into `const char *GetName(fixed =  true)` (following change for sp include) with corresponding return values?

**Comment by asherkin** [comment]
I'm afraid it isn't clear what you're asking for here - please could you explain what you're trying to do, what you expect to happen, and what is actually happening instead (pretty much what the issue template asks for) rather than a dump of assembly.

**Comment by shqke** [comment]
Hi!
I was hoping psychonic would join as he was directly involved with a thread as well as with commit.
Whole issue has been described in [AM forum thread](https://forums.alliedmods.net/showthread.php?t=305561), link of which I've given in the beginning. Author of the thread has never got his issue solved and had to make workaround with a plugin, instead of getting it working in a sourcemod core.

Anyway, [quoting psychonic](https://forums.alliedmods.net/showpost.php?p=2580137&postcount=7):
> What I do know:
A user's name in Steam can be 32 characters, including multi-byte characters.
A user's name in L4D2 gets cut off at 32 bytes internally in the engine. (m_Name on CGameClient).
This same behavior occurs if you manually set their name.
If the above happens, the cut off can be in the middle of a character, causing the corruption you mention.
So far, none of the above has anything to do with SourceMod. The engine can have a corrupted name.
When SourceMod first gets the name and when it caches updates to the name, it does attempt to strip off any invalid characters at the end of the name. Using MAX_NAME_LENGTH (32) should never cause further corrupt because the engine already only holds 32 bytes of the name. Regardless, GetClientName should not be able to return a name with a trailing invalid character, unless you are on an old version (SM 1.7 or lower).

Issue is that [GetClientName](https://sm.alliedmods.net/new-api/clients/GetClientName) is actually able to return a name with trailing invalid character (and it's possible on latest version of SM that I'm currently using).

Seeing how many calls there are for [CPlayer::GetName](https://github.com/alliedmodders/sourcemod/blob/master/core/PlayerManager.cpp#L2279) (implementation of [IGamePlayer::GetName](https://github.com/alliedmodders/sourcemod/blob/master/public/IPlayerHelpers.h#L68)), I've figured it would be easier to check whether I'll get a fixed [CPlayer::m_Name](https://github.com/alliedmodders/sourcemod/blob/master/core/PlayerManager.h#L133) to be returned anytime in a test plugin. So I've set up a breakpoint where m_Name would be returned, and got only few calls which were due to [PlayerManager::OnClientSettingsChanged](https://github.com/alliedmodders/sourcemod/blob/master/core/PlayerManager.cpp#L1343) and yet NULL m_Info.

That's equivalent of whats happening:
```sp
void ChangeName(int client)
{
	char name[128];
	char newName[] = "😀😀😀😀😀😀😀😀";
	SetClientName(client, newName);
	GetClientName(client, name, sizeof(name));
	PrintToServer("strlen(newName) = %u, strlen(name) = %u", strlen(newName), strlen(name)); // prints "strlen(newName) = 32, strlen(name) = 31" 
}
```

Last byte gets cut off due to limited buffer size in the engine and sourcemod [proxies](https://github.com/alliedmodders/sourcemod/blob/master/core/PlayerManager.cpp#L2283) string from [IPlayerInfo::GetName](https://github.com/alliedmodders/hl2sdk/blob/l4d2/public/game/server/iplayerinfo.h#L105), instead of getting one that was internally [fixed here](https://github.com/alliedmodders/sourcemod/blob/master/core/PlayerManager.cpp#L2276).

Let me know if there's anything that needs further clarifying.

**Comment by asherkin** [comment]
Thanks! That all makes sense now.

I think using the internal name value in all cases makes sense, you’ve probably dug into this more than anyone in years, can you see any downsides to that approach?

The most important thing will be that it stays in sync with any changes notified to the engine from other sources, which I imaging we could possibly be missing some of with the direct info access today.

**Comment by shqke** [comment]
As long as bot name changes are not ignored [here](https://github.com/alliedmodders/sourcemod/blob/master/core/PlayerManager.cpp#L1336), it might be fine.

**Comment by KyleSanderson** [comment]
@asherkin I think we can just increase this to 128b and then write null from 124b to the end(?). WDYT?

**Comment by shqke** [comment]
Does existing NULL-termination seems insufficient?
As of size, wouldn't it make more sense to edit [const.h](https://github.com/alliedmodders/hl2sdk/blob/sdk2013/public/const.h#L41) instead (source code leak also has **MAX_PLAYER_NAME_LENGTH** constant set to 128 so sdks would match)?

**Comment by KyleSanderson** [comment]
UTF8 is 4 bytes (at most at the time of this writing - I believe 🙃) of characters to print a single formatted char. So, technically, you can escape formatting with a single character and crash c libraries. This is a huge gap everywhere, and is just a massive painpoint globally.

**Comment by shqke** [comment]
Did you mean a fixed length encoding (UTF32)? In UTF8 a single character is maximum of 4 bytes, yes, but 0 byte is still a NULL.

**Comment by asherkin** [comment]
> @asherkin I think we can just increase this to 128b and then write null from 124b to the end(?). WDYT?

I don't think so - the original truncation here is in the engine. This is a straightforward bug in `CPlayer::GetName`.

> As of size, wouldn't it make more sense to edit [const.h](https://github.com/alliedmodders/hl2sdk/blob/sdk2013/public/const.h#L41) instead (source code leak also has **MAX_PLAYER_NAME_LENGTH** constant set to 128 so sdks would match)?

No - only some engine branches have it as 128, such as CS:GO, which is [already correct](https://github.com/alliedmodders/hl2sdk/blob/csgo/public/const.h#L45).

**Comment by shqke** [comment]
Yeah, somehow I've linked a file for a wrong sdk branch (and assumed it was a CSGO one).

Should I make a PR then?

**Comment by dragokas** [comment]
Left 4 Dead 1 game is also affected.
