### ISSUE TITLE
bash sourcemod/tools/checkout-deps.sh fails to run

### ISSUE THREAD

**Issue by enderandrew** [alliedmodders/sourcemod#1324]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Debian 10
  * Game/AppID (with version if applicable): TF2
  * Current SourceMod version: 
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

Trying to download a build environment, checkout-deps.sh throws an error on ambuild2

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named ambuild2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ambuild2'
Cloning into 'ambuild'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 2647 (delta 35), reused 46 (delta 34), pack-reused 2584
Receiving objects: 100% (2647/2647), 1.53 MiB | 8.77 MiB/s, done.
Resolving deltas: 100% (1820/1820), done.
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
Installing AMBuild at the user level. Location can be: ~/.local/bin
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

# Problematic Code (or Steps to Reproduce)
  ```
  // TODO(you): code here to reproduce the problem
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by Headline** [comment]
Install the python3-setuptools package

sudo apt-get install python3-setuptools

**Comment by WildCard65** [comment]
Here's a reference on why setuptools is now required:
https://github.com/alliedmodders/ambuild/issues/68

Should @Headline suggestion not work for you, you can manually resolve this by installing 'pip' as it depends on setuptools.

**Comment by dvander** [comment]
We should add this to checkout-deps.sh, since it is a new dependency.

**Comment by enderandrew** [comment]
Even after installing python3-setuptools and pip, I'm still getting the error. Is this maybe an issue where the script is designed for python 2 instead of python 3?

From https://github.com/alliedmodders/ambuild
 * branch            master     -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
Installing AMBuild at the user level. Location can be: ~/.local/bin
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by dvander** [comment]
Yes, the script does assume Python 2.

**Comment by enderandrew** [comment]
After installing python-setuptools (as opposed to python3-setuptools) this script runs successfully.

**Comment by KyleSanderson** [comment]
Yeah that's a gap @enderandrew , thanks for raising this.

@WildCard65 do you think you can help out here with a PR to add this dependency to checkout-deps?

**Comment by WildCard65** [comment]
I'll attempt, but first off:

1) Should checkout-deeps stick with Python 2 or be changed to allow either.

2) If we do allow either, should we use 'get-pip.py' or install the
systems' preferred package.

get-pip.py would somewhat be the easiest as it's most likely platform
independent.

**Comment by WildCard65** [comment]
@dvander @KyleSanderson Some unfortunate news though, it seems both Debian and Ubuntu are planning on removing Python2 from newer versions, this could potentially introduce issues with checkout-deps if 'python' command is no longer available.

**Comment by dvander** [comment]
`python blah || true`
