### ISSUE TITLE
Simplify checkout-deps for AMbuild.

### ISSUE THREAD

**Issue by WildCard65** [alliedmodders/sourcemod#1331]
@dvander This issue serves as a primary reminder for me.

It's been some time since I created the pull request #1326 and since it's merging.

I have come to realize some things since then:
   1) PIP supports installation of packages straight from vcs (GIT confirmed to work)
   2) There is an edge case where installation of AMbuild can fail to install: PIP exists without setuptools.

A simple resolution to both points above is available (and supported by PIP): requirements.txt (commonly accepted file name)

This file serves to list dependencies of a Python package, in nothing but plain text.

Example:
```
wrapt
typing;python_version<"3.5"
setuptools>=0.40
```

Usage of the file is simple: ```pip install -r <path to requirements file>```

For SourceMod, this is all we would keep in it:
```
setuptools
git+https://github.com/alliedmodders/ambuild.git
```

This would eliminate the edge case and allow for a simpler check/install of AMbuild (pip would be in charge of that), existing behaviour should continue on as PIP should skip install if requirements are satisfied.

**Comment by peace-maker** [comment]
The current state seems to be enough to make CI happy.
