### ISSUE TITLE
Cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hXR16F** [alliedmodders/sourcemod#1339]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Ubuntu 18.04.4 LTS x86_64
  * Game/AppID (with version if applicable): Counter Strike: Global Offensive (740) - newest version
  * Current SourceMod version: 1.10 - build 6492
  * Current SourceMod snapshot: 1.11 - build 6621
  * Current Metamod: Source snapshot: 1.10 - build 971
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
It's giving me errors from plugins that require MySQL.
```
Authentication plugin 'sha256_password' cannot be loaded: /usr/local/mysql/lib/plugin/sha256_password.so: cannot open shared object file: No such file or directory
```
The folder `/usr/local/mysql/` doesn't exist. On our dedicated server we have web server and other games (FiveM, Garry's Mod) and everything is working except CS: GO.

# Problematic Code (or Steps to Reproduce)
Just run the server and have plugins that require access to MySQL.

# Logs
![console](https://user-images.githubusercontent.com/48186982/90983856-901b6100-e571-11ea-9218-b8cb99558c86.png)

**Comment by peace-maker** [comment]
That error is from your mysql server. Is the mysql server hosted on the same machine as the csgo server?

**Comment by hXR16F** [comment]
> That error is from your mysql server. Is the mysql server hosted on the same machine as the csgo server?

Yes, as I said before - we have web server running MySQL.

**Comment by asherkin** [comment]
SourceMod’s MySQL extension doesn’t support the authentication plugin you are using, you’ll need to re-create the user using the `native_password` scheme.

**Comment by hXR16F** [comment]
> SourceMod’s MySQL extension doesn’t support the authentication plugin you are using, you’ll need to re-create the user using the `native_password` scheme.

To which I should change? `mysql_native_password` doesn't do anything - still same error.

**Comment by KyleSanderson** [comment]
This has no relation to sourcemod @hXR16F . While community members have tried to help ultimately this is completely on you to implement. https://dba.stackexchange.com/questions/209514/what-is-mysql-native-password
