### ISSUE TITLE
[CS:GO] CS_TerminateRound doesn't grant score nor displays MVP.

### ISSUE THREAD

**Issue by eyal282** [alliedmodders/sourcemod#1340]
# Help us help you
  - [ x ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ x ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows?
  * Game/AppID (with version if applicable): 730, CS:GO.
  * Current SourceMod version: 1.10
  * Current SourceMod snapshot: 6488
  * Current Metamod: Source snapshot: 1.10.7-dev
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
CS_TerminateRound gives no cash, score, mvp or set round fun fact.

# Problematic Code (or Steps to Reproduce)
  ```
  // TODO(you): just CS_TerminateRound and see it doesn't give cash rewards, team score, set mvp
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by KyleSanderson** [comment]
This is well documented / expected.

**Comment by eyal282** [comment]
> This is well documented / expected.

If that's the case CS:GO is missing a native "CS_ForceWinRound" to be used on custom gamemodes

**Comment by KyleSanderson** [comment]
Not really, this has always been sendprop enabled.
