### ISSUE TITLE
AMBuildScript still references builder.target

### ISSUE THREAD

**Issue by ErikMinekus** [alliedmodders/sourcemod#1343]
@dvander the following lines still reference `builder.target`, which no longer exists:

~~https://github.com/alliedmodders/sourcemod/blob/master/AMBuildScript#L181~~ fixed in #1373
https://github.com/alliedmodders/sourcemod/blob/master/AMBuildScript#L228

**Comment by Headline** [comment]
Fixed by #1373

**Comment by ErikMinekus** [comment]
Unfortunately that PR did not fix the second occurrence.

**Comment by Headline** [comment]
Thanks for double checking - slipped past me
