### ISSUE TITLE
OnPlayerRunCmdPost returns 0 bits for some buttons

### ISSUE THREAD

**Issue by raziEiL** [alliedmodders/sourcemod#1350]
# Help us help you
  - [V ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [V ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [V ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Win 10
  * Game/AppID (with version if applicable): l4d2 Exe build: 14:46:56 Jul 16 2019 (7227) (550)
  * Current SourceMod version: 1.10
  * Current SourceMod snapshot: 1.10.0.6492
  * Current Metamod: Source snapshot: 1.11 - build 1143
  - [V] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [V] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [V] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
OnPlayerRunCmdPost returns 0 bits for IN_USE, IN_JUMP, IN_ATTACK2, IN_FORWARD, IN_BACK, IN_MOVELEFT, IN_MOVERIGHT buttons while player incapacitated but it shouldn't.

# Problematic Code (or Steps to Reproduce)
  ```sourcepawn
public Action OnPlayerRunCmd(int client, int &buttons, int &impulse, float vel[3], float angles[3], int &weapon, int &subtype, int &cmdnum, int &tickcount, int &seed, int mouse[2])
{
	if (client && buttons && !IsFakeClient(client))
		PrintToChat(client, "OnPlayerRunCmd: btns %d, incaped %d", buttons, GetEntProp(client, Prop_Send, "m_isIncapacitated"));
	return Plugin_Continue;
}

public void OnPlayerRunCmdPost(int client, int buttons, int impulse, const float vel[3], const float angles[3], int weapon, int subtype, int cmdnum, int tickcount, int seed, const int mouse[2])
{
	if (client && buttons && !IsFakeClient(client))
		PrintToChat(client, "OnPlayerRunCmdPost: btns %d, incaped %d", buttons, GetEntProp(client, Prop_Send, "m_isIncapacitated"));
}

  ```

# Logs
```
// Player is not incaped (IN_USE):
OnPlayerRunCmd: btns 32, incaped 0
OnPlayerRunCmdPost: btns 32, incaped 0
OnPlayerRunCmd: btns 32, incaped 0
OnPlayerRunCmdPost: btns 32, incaped 0

// Player is Incaped (IN_USE):
OnPlayerRunCmd: btns 32, incaped 1
OnPlayerRunCmd: btns 32, incaped 1
OnPlayerRunCmd: btns 32, incaped 1
OnPlayerRunCmd: btns 32, incaped 1
```

**Comment by asherkin** [comment]
> but it shouldn't.

Why shouldn’t it?

I’m afraid it is unclear what the bug report here is - these values come directly from the game function hook. Is there some evidence that SourceMod is misbehaving?

**Comment by raziEiL** [comment]
I have not looked at the source code of OnPlayerRunCmdPost if these values come directly from the game hook then everything is fine. Still learning something new about the game. Thanks!
