### ISSUE TITLE
sm_dump_datamaps crashes L4D2

### ISSUE THREAD

**Issue by Pinsplash** [alliedmodders/sourcemod#1354]
# Environment
  * Operating System version: https://gist.github.com/Pinsplash/604c266611680caa5e1d7e02e5924f30
  * Game/AppID (with version if applicable): Left 4 Dead 2 (2.2.0.1)
  * Current SourceMod version: 1.10.0.6497
  * Current MetaMod version: 1.10.7-dev

# Description
sm_dump_datamaps makes the game crash. The file is created successfully, it just crashes afterward. The error message "cannot load corrupted map" appears. Happens on any map. I can't remember this happening on any other game at any other time. I have SM installed on a listen server, as in, the same folder where I keep my actual L4D2.

# Logs
* I don't know any of these things sorry.

**Comment by asherkin** [comment]
This is expected behaviour - due to how `sm_dump_datamaps` functions it leaves the game in an inconsistent state. Some games will crash immediately, most games will crash if it is run a second time.
