### ISSUE TITLE
Transaction between 2 databases.

### ISSUE THREAD

**Issue by eyal282** [alliedmodders/sourcemod#1355]
I've asked Impact who referred me here: https://dev.mysql.com/doc/refman/8.0/en/xa.html. I don't know if that's enough to actually make those kind of transactions, assuming it actually works in Sourcemod. But I still think there should be new natives to allow transactions between 2 different databases.

**Comment by KyleSanderson** [comment]
@eyal282 this is out of scope unfortunately. I don't know why the issue template was completely ignored here but this is just not on our radar at this time.
