### ISSUE TITLE
makesig.idc error:Ran out of bytes to create unique signature.

### ISSUE THREAD

**Issue by YuanBaian** [alliedmodders/sourcemod#1356]
server.dll    sub_101BA880
//const char *CBaseAnimating::GetSequenceName( int iSequence )

Is there any way to get a signature

thanks

**Comment by KyleSanderson** [comment]
@YuanBaian you've skipped the template. can you fill this out to try and give an inkling of more information? While this should be immediately closed I'm hoping you can try to actually file an issue.
