### ISSUE TITLE
KeyValues: Section name "Black" is read with invalid letter case

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1383]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 10 x64
  * Game/AppID (with version if applicable): 550
  * Current SourceMod version: 1.10.0.6499
  * Current SourceMod snapshot: 1.10.0.6499
  * Current Metamod: Source snapshot: 1.10.7
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
When you read the section names from KeyValues file, the "black" name is read instead of "Black" (1-st letter is self-modified).
When you change the word "Black" to anything else (let's say, remove the letter "k", or prepend additional letter "B"), the section name read normally.

# Problematic Code (or Steps to Reproduce)
  ```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>

public void OnPluginStart()
{
	KeyValues kv;
	
	char sConfigPath[PLATFORM_MAX_PATH];
	BuildPath(Path_SM, sConfigPath, PLATFORM_MAX_PATH, "data/%s", "test.cfg");
	
	kv = new KeyValues("root");
	if( !kv.ImportFromFile(sConfigPath) )
		SetFailState("[SM] ERROR:Incorrectly formatted file, '%s'", sConfigPath);
	
	kv.Rewind();
	kv.JumpToKey("colors", false);
	
	char sColor[32], sValue[16];
	
	if( kv.GotoFirstSubKey(false) )
	{
		do
		{
			if( kv.GetSectionName(sColor, sizeof(sColor)) )
			{
				kv.GetString(NULL_STRING, sValue, sizeof(sValue));
				
				PrintToServer("color: %s, value: %s", sColor, sValue);
			}
		} while( kv.GotoNextKey(false) );
	}
}
  ```
**Config file:**
```
"root"
{
	"colors"
	{
		"Golden" "255 215 0"
		"Black" "0 0 0"
		"White" "255 255 255"
	}
}
```

# Logs
```
color: Golden, value: 255 215 0
color: black, value: 0 0 0
color: White, value: 255 255 255
```
[scripting.zip](https://github.com/alliedmodders/sourcemod/files/5596967/scripting.zip)

**Comment by dragokas** [comment]
Can you clarify, please, what other negative consequences can occur in some words?
Does only 1-st letter is affected?

Thank you.

**Comment by psychonic** [comment]
The game stores KV keys in a case-insensitive string pool. If any kv loaded by the game has a key of "black" seen before your "Black" one, you would get the result that you're seeing.

If you need explicit casing, you may want to use an SMC file instead of VDF.
