### ISSUE TITLE
csgo update broke buymenu (and cstrike ext I believe)

### ISSUE THREAD

**Issue by xSL0W** [alliedmodders/sourcemod#1405]
# Help us help you
  - [yes ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ yes] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ yes] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  debian 10
  * Game/AppID (with version if applicable):  730 (csgo)
  * Current SourceMod version:  
  *    SourceMod Version: 1.10.0.6501
    SourcePawn Engine: 1.10.0.6501, jit-x86 (build 1.10.0.6501)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Dec  4 2020 09:20:55
    Built from: https://github.com/alliedmodders/sourcemod/commit/051f42c
    Build ID: 6501:051f42c
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  *    Metamod:Source version 1.11.0-dev+1143
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: Valve Server Plugin
    Compiled on: Aug 19 2020 14:56:55
    Built from: https://github.com/alliedmodders/metamod-source/commit/b8d1fd4
    Build ID: 1143:b8d1fd4
    http://www.metamodsource.net/
  - [yes ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [no ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [no ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

# Problematic Code (or Steps to Reproduce)
Buy a weapon from buymenu. ( https://live.staticflickr.com/65535/50732359182_79fc7be539_o.gif )
and it will be dropped on the ground

https://forums.alliedmods.net/showthread.php?t=329306

**Comment by yourmnbbn** [comment]
Seems that it will cause this kind of problem when you have CS_OnBuyCommand forward in one of your plugins. I have the same problem too. When I removed the plugin using this forwards it works fine.

**Comment by xSL0W** [comment]
smoke#5694 posted a commit on discord. tested it and it works now.
https://github.com/komashchenko/sourcemod/commit/82ad25c1d7e11cae3e1a8183e9419c97dbac81f9

**Comment by asherkin** [comment]
Thanks for the report, and komashchenko for the fix. This is fixed in master and 1.10-dev now.
