### ISSUE TITLE
Server crash - [ RETAKE RULES ] Unable to find a card for this player

### ISSUE THREAD

**Issue by NockyCZ** [alliedmodders/sourcemod#1408]
Hi guys, i try make Retakes with Valve weapon selection (sv_skirmish_id 13)
But i have problem, when player is afk and does not select any weapon on start round from the menu, so server crash.
```
[ RETAKE RULES ] Unable to find a card for this player ( Nocky ).
PreMinidumpCallback: updating dump comment
crash_20201218234505_1.dmp[30920]: Uploading dump (out-of-process)
/tmp/dumps/crash_20201218234505_1.dmp
```

**Comment by asherkin** [comment]
This doesn't appear to have the background investigation work required for a bug report, please post on the [AlliedModders forum](https://forums.alliedmods.net/) instead.
