### ISSUE TITLE
KeyValues.GetString returns float for Hexed string

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1417]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 7 x64
  * Game/AppID (with version if applicable): 500
  * Current SourceMod version:  1.11.0.6653
  * Current SourceMod snapshot:  1.11.0.6653
  * Current Metamod: Source snapshot: 1.10.7
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
When you use GetString method on the value "0x02504983" it returns (10)float + 1.0 instead of a raw string.

# Problematic Code (or Steps to Reproduce)
  ```
#include <sourcemod>
#include <sdktools>

#define GAMEDATA_CONF	"test"

KeyValues kv;

public void OnPluginStart()
{
	char sPath[PLATFORM_MAX_PATH];
	BuildPath(Path_SM, sPath, sizeof(sPath), "gamedata/%s.txt", GAMEDATA_CONF);
	
	KeyValues kv = new KeyValues("Games");
	if( kv.ImportFromFile(sPath) )
	{
		char s[32];
		kv.GetString("value", s, sizeof(s));
		
		PrintToServer("value = %s", s);
	}
}
  ```
**test.txt**
```
"Games"
{
	"value"		"0x02504983"
}
```

# Logs
```
value = 38816132.000000
```

**Comment by asherkin** [comment]
The KeyValues class guesses the types at parse time, see #643.

**Comment by asherkin** [comment]
Looking at your example code - gamedata files are SMC files by the way, not KeyValues - the formats are similar but incompatible.
