### ISSUE TITLE
CSRoundEndReason is 1 larger than expected when fetched from event

### ISSUE THREAD

**Issue by nickdnk** [alliedmodders/sourcemod#1419]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Ubuntu 20.04
  * Game/AppID (with version if applicable): 730/740, CS:GO version 1216
  * Current SourceMod version: 1.10.0.6497
  * Current SourceMod snapshot: ?
  * Current Metamod: Source snapshot:
  // I haven't updated to the latest version as it's quite tedious for me to do, so I just wanted to ask here before trying that. If you cannot give an answer to this issue without me updating I will of course try that.
  - [-] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [-] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [-] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

When fetching the `round_end` event (https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#round_end)  and reading the `reason` property using `event.GetInt("reason")`, it returns an integer that's 1 larger than defined in https://sm.alliedmods.net/new-api/cstrike/__raw, i.e. when the bomb explodes, `CSRoundEnd_TargetBombed` becomes `1`, not `0`, `CSRoundEnd_TargetSaved` becomes `12` instead of `11` and so on.

Is this me being an idiot? Does `GetInt()` not work when the field is of type "byte" (there's no `GetByte()` method it seems). I'm pretty new to SourceMod/SourcePawn so this might be my fault.

# Problematic Code (or Steps to Reproduce)
  ```
// Hook the event
int reason = event.GetInt("reason");
LogMessage("%d", reason);

  ```

# Logs
n/a

**Comment by psychonic** [comment]
IIRC, this is due to the reasons being off by one between CS:S and CS:GO (and the include predating CS:GO). The SourceMod and CStrike extension natives and forwards that specifically deal with round end reason do account for this. For reading from the event, you do have to handle it manually.

**Comment by nickdnk** [comment]
Cool. Thanks for clearing it up. I'll just adjust my code to compensate for it. I just wanted to make sure I wasn't doing something wrong.
