### ISSUE TITLE
Weapons are getting dropped again after buy

### ISSUE THREAD

**Issue by hobsRKM** [alliedmodders/sourcemod#1421]
Last fix on  
Fix detour HandleCommand_Buy_Internal (#1406) fixed the issue of weapons getting dropped on buy on one of the plugin:weapon_restrict.smx

The issue is back again after csgo update of yesterday.

**Comment by asherkin** [comment]
I think this was fixed a while back, please re-open if you're still having an issue with the latest version of SM and the game.
