### ISSUE TITLE
Populated sm_nextmap causes looping on changelevel failures

### ISSUE THREAD

**Issue by nosoop** [alliedmodders/sourcemod#1429]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Linux
  * Game/AppID (with version if applicable): Team Fortress 2
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) (1.11.0.6655) and it still happens.

# Description
Team Fortress 2 (and possibly other games, since this is in the base teamplay system) has an event `server_changelevel_failed` that the game uses during the gameover state to move to the next map in the cycle.  SourceMod's `sm_nextmap` isn't cleared at this stage; if the game was in that state and the `sm_nextmap` ~~was invalid~~ couldn't be validated (e.g. `workshop/1`), SourceMod will intercept the game's attempts to change level and switch back to the invalid map, getting into a loop.

# Problematic Code (or Steps to Reproduce)
1. While in TF2, use `sm_setnextmap workshop/1` in the game / server console to set the next map, or change `sm_nextmap` directly to `workshop/1`.
2. Get to the post-game screen, then observe the server console as it changes maps.

# Logs
```
In gameover, but failed to load the next map. Trying next map in cycle.
CHANGE LEVEL: cp_snakewater_final1
L 02/18/2021 - 06:46:07: [SM] Changed map to "workshop/1"
[TF Workshop] Preparing map ID 1
[TF Workshop] Error fetching updated information for map id 1
[TF Workshop] Info lookup failed for workshop file 1 ( EResult 1 )
[TF Workshop] Map failed to sync, load will not go well :(
CModelLoader::Map_IsValid:  No such map 'maps/workshop/1.bsp'
Unable to change level!
In gameover, but failed to load the next map. Trying next map in cycle.
CHANGE LEVEL: cp_sunshine
L 02/18/2021 - 06:46:07: [SM] Changed map to "workshop/1"
[TF Workshop] Preparing map ID 1
[TF Workshop] Error fetching updated information for map id 1
[TF Workshop] Info lookup failed for workshop file 1 ( EResult 1 )
[TF Workshop] Map failed to sync, load will not go well :(
CModelLoader::Map_IsValid:  No such map 'maps/workshop/1.bsp'
Unable to change level!
In gameover, but failed to load the next map. Trying next map in cycle.
CHANGE LEVEL: cp_metalworks
L 02/18/2021 - 06:46:07: [SM] Changed map to "workshop/1"
[TF Workshop] Preparing map ID 1
[TF Workshop] Error fetching updated information for map id 1
[TF Workshop] Info lookup failed for workshop file 1 ( EResult 1 )
[TF Workshop] Map failed to sync, load will not go well :(
CModelLoader::Map_IsValid:  No such map 'maps/workshop/1.bsp'
Unable to change level!
In gameover, but failed to load the next map. Trying next map in cycle.
[...]
```

**Comment by ambaca** [comment]
I think problem is, just timing and how/when you use sm_nextmap convar.

This sm_nextmap convar is very powerful, it override in-game nextlevel convar. Which is really good.
- Remember, SourceMod nextmap, mapchooser, etc. are changing this cvar. If you don't want that then unload those plugins.

You need also understand, when you have map set into sm_nextmap (sm_nextmap cp_dustbowl),
it will be there as long as nothing change that.

So, you could try:
- In server.cfg file, add ```sm_nextmap ""``` to clear console variable
- Create SourceMod plugin for TF2, using that event ``` server_changelevel_failed ```


I don't see why need make fix in sm_nextmap code, TF2 game could have only that event tough.

**Comment by nosoop** [comment]
I already have my own solution; that's beside that point.  This happens on a completely clean SourceMod installation, and so I consider it a bug worth filing.

I do use the stock map chooser, but in the event that a workshop map is invalid (perhaps the map was removed from public view and the server operator hasn't been maintaining their mapcycle), I think it'd be perfectly reasonable to have a failsafe built in for this instance to avoid causing a map switching deadlock.

It already does [a check for definitely invalid maps](https://github.com/alliedmodders/sourcemod/blob/91a1fd074be6534ff07fa0895166d936d1715626/core/NextMap.cpp#L126-L129), so I don't think this is an unreasonable ask.
