### ISSUE TITLE
Introduce ConVar.GetDescription() method

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1432]
Hi,

Can you add please an ability to return "Description" string field by ConVar handle?

It is an argument, filled in CreateConVar() function, and also available via FindFirstConCommand enumerator.

Will be good to easily access everything in one place.
Thank you.

**Comment by Wend4r** [comment]
I also want to add to this request getting the minimum and maximum ConVar values
```
ConVar.HasMinValue.get
ConVar.HasMaxValue.get
ConVar.MinValue.get
ConVar.MaxValue.get
```
I think it will be useful if the plugin would control the value of ConVar through the user (the outer shell) to give him an error and etc..

**Comment by asherkin** [comment]
> I also want to add to this request getting the minimum and maximum ConVar values

Please do not hijack other issues.

What you're after is already implemented as the [GetBounds](https://sourcemod.dev/#/convars/methodmap.ConVar/function.GetBounds) / [SetBounds](https://sourcemod.dev/#/convars/methodmap.ConVar/function.SetBounds) functions.
