### ISSUE TITLE
Crash in SourceMod::NameHashSet (called from GetCommandFlags)

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1433]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Linux v.?
  * Game/AppID (with version if applicable): 730 (CS:GO)
  * Current SourceMod version: 1.10.0.6502
  * Current SourceMod snapshot: 1.10.0.6502
  * Current Metamod: Source snapshot:
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Crash place: [SourceMod::NameHashSet](https://github.com/alliedmodders/sourcemod/blob/617fb77ea02076cc70be84c6092ebcfc81d54cc2/core/smn_console.cpp#L185).

Crash is happening when the player enters in chat some text, processed by my [command_eater.sp](https://forums.alliedmods.net/showthread.php?p=2673306) via 
```AddCommandListener(ListenSay, "say");```
and followed to [CommandExists](https://sm.alliedmods.net/new-api/console/CommandExists)() sm function.

Crash is only happening when my plugin is used together with csgo_gunmenu.sp plugin & "Simple Chat Processor (Redux)" (2.3.0) by Simple Plugins, Mini.

Reported in this topic: https://hlmod.ru/threads/command-eater-pozhiratel-komand.50706/page-4#post-515337

# Logs
https://crash.limetech.org/3gsep6ovxalb
[Throttle.txt](https://github.com/alliedmodders/sourcemod/files/6063421/Throttle.txt)
[csgo_gunmenu 1.2.zip](https://github.com/alliedmodders/sourcemod/files/6063422/csgo_gunmenu.1.2.zip)

**Comment by asherkin** [comment]
> * Current SourceMod version: 1.10.0.6502
> * Current SourceMod snapshot: 1.10.0.6502
> 
> * [x]  I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
> * [x]  I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.

This was fixed in 1.11 with #1256, it hasn't been back-ported to 1.10 yet.

The bug is related to multiple different case versions of a command being registered.

**Comment by dragokas** [comment]
Thank you for the kind explanation.

**Comment by KyleSanderson** [comment]
Thanks much asher. @dragokas we should probably pin stable again as it's been a year+. I'll take this away to see when we can do a rls.
