### ISSUE TITLE
EntIndexToEntRef throws error if param is reference

### ISSUE THREAD

**Issue by Ilusion9** [alliedmodders/sourcemod#1436]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet] - yes
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible - yes
  - [x] I can always reproduce the issue with the provided description below. - yes

# Environment
  * Operating System version: any
  * Game/AppID (with version if applicable): csgo
  * Current SourceMod version: any
  * Current SourceMod snapshot: any
  * Current Metamod: Source snapshot: any

# Description
If I send entity reference to EntIndexToEntRef, sourcemod just throws an error: Invalid entity index.

# Problematic Code (or Steps to Reproduce)
```
HookEntityOutput("logic_timer", "OnTimer", Output_OnLogicTimer);

public void Output_OnLogicTimer(const char[] output, int caller, int activator, float delay)
{
	int reference = EntIndexToEntRef(caller);
}
```
If I use the entity reference in GetEntityClassname or GetEntProp, everything is fine. Is this on purpose?

This is the workaround that I currently use:
```
int EntIndexToEntRef_Ex(int entity)
{
	if (entity < 0 || entity > 4096)
	{
		return entity;
	}
	
	return EntIndexToEntRef(entity);
}
```

**Comment by KyleSanderson** [comment]
So this one is a bit screwy, but you want to do EntIndexToEntRef(EntRefToEntIndex(entity)); this way the conversion handles anything that the engine gives you.
