### ISSUE TITLE
CDetour: what the extension.h?

### ISSUE THREAD

**Issue by Wend4r** [alliedmodders/sourcemod#1440]
What the `extension.h`?

https://github.com/alliedmodders/sourcemod/blob/ae485c311541bb0fa609e5a9a33e0fdf1595fd56/public/CDetour/detours.h#L35

Where is it located?

**Comment by asherkin** [comment]
It is your extension's main header file, e.g. https://github.com/alliedmodders/sourcemod/blob/master/public/sample_ext/extension.h for `sample_ext`.

Please use the forum or Discord for questions like this in the future.

**Comment by Wend4r** [comment]
Thank you. 
```
gcc (Debian 8.3.0-6) 8.3.0
```
It's just trying to find `extension.h` relatively `sourcemod/public/CDetour/`
