### ISSUE TITLE
allow handle subtyping of subtypes

### ISSUE THREAD

**Issue by arthurdead** [alliedmodders/sourcemod#1457]
currently you cant subtype of a subtype
https://github.com/alliedmodders/sourcemod/blob/master/core/logic/HandleSys.cpp#L123-L130

and i need this feature for a ext

**Comment by dvander** [comment]
Can you explain why you need this?

**Comment by arthurdead** [comment]
i have an extensions for the NextBot system

and it has these classes: Path, PathFollower, ChasePath, RetreatPath, CTFPathFollower
and their inheretance look like this:

Path
PathFollower < Path
ChasePath < PathFollower
CTFPathFollower < PathFollower
RetreatPath < PathFollower

so when creating a handle for each i cant subtype of PathFollower because it is already a subtype of Path

**Comment by asherkin** [comment]
Handle subtypes are just for simpler permissions management, they have no relation to the class hierarchy, I think you just want 6 different top-level handle types.

**Comment by Wend4r** [comment]
I needed to find out what parameters has the `Event` methodmap by some iterator, and the subtypes concept is great for that. An example is `methodmap Event < KeyValues`, where `KeyValues` by `virtual KeyValues *IGameEventManager2::GetEventDataTypes(IGameEvent *event)`.
