### ISSUE TITLE
PCRE is not compiled with Unicode property support

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcemod#1460]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: 
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
SM has regex flag for UCP but extension does not support it.
`PCRE is not compiled with Unicode property support`

# Problematic Code (or Steps to Reproduce)
Compile/run any regex expression with flag `PCRE_UCP`

**Comment by Headline** [comment]
What arch?

**Comment by JoinedSenses** [comment]
1.10.0.6492
ubuntu / debian

Tested by another user, not myself unfortunately. I dont have any machines with 1.11 to check right now either

**Comment by JoinedSenses** [comment]
I'll go ahead and upgrade to 1.11 on both win/linux to test

**Comment by JoinedSenses** [comment]
Closing because tested on 1.11 with no issue

```
public void OnPluginStart() {
	RegAdminCmd("sm_testregex", cmdTest, ADMFLAG_ROOT);
}

public Action cmdTest(int client, int args) {
	char err[256];
	RegexError re;
	Regex r = new Regex("asdf", PCRE_UCP, err, sizeof err, re);
	ReplyToCommand(client, "r:%i err:%s re:%i", r, err, re);
	delete r;
	return Plugin_Handled;
}
```

> r:-121174664 err: re:0
