### ISSUE TITLE
Add SetCollisionGroup to API

### ISSUE THREAD

**Issue by xMaZax** [alliedmodders/sourcemod#1461]
Hello everyone, some people know and have encountered the fact that when installing a collision, an object can fall under the map or have some other side effects.

# Problematic Code (or Steps to Reproduce)
  ```
 SetEntProp(client, Prop_Data, "m_CollisionGroup", flags);
  ```

If we use a function that directly causes a collision to be set then this problem will not occur

void CBaseEntity::SetCollisionGroup( int collisionGroup )

https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/shared/baseentity_shared.cpp#L2704

I suggest adding this feature to the main sourcemod API.

I think this is because another CollisionRulesChanged() function is not called; when we expose just via SetEntProp.

I think a direct function call will be more correct than we use now " crutches"

**Comment by xMaZax** [comment]
Other info bug:
https://bugs.alliedmods.net/show_bug.cgi?id=6348
https://web.archive.org/web/20190406220848/https://forum.facepunch.com/gmoddev/likl/Crazy-Physics-cause-found/1/

And even there is a plugin to try to fix this problem, I do not see the point in it when you can add it to the main API.
https://github.com/ashort96/SetCollisionGroup

**Comment by ashort96** [comment]
The plugin does fix it, and yes you are spot on about the reasoning. `CollisionRulesChanged()` getting called after changing an entity's collision group does prevent the "Physics Mayhem" bug.

**Comment by ashort96** [comment]
I believe this Issue can be closed as #1507 addresses this.

**Comment by KyleSanderson** [comment]
Indeed, thanks for the PR.
