### ISSUE TITLE
sdkhooks forwards never used

### ISSUE THREAD

**Issue by naris** [alliedmodders/sourcemod#1464]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 10
  * Game/AppID (with version if applicable): n/a
  * Current SourceMod version: 1.10 build 6502
  * Current SourceMod snapshot: n/a
  * Current Metamod: Source snapshot: n/a
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
When I include sdkhooks.inc and define OnEntityDestroyed() the compiler complains the symbol is never used and it never get called.

//// test.sp
//
// test.sp(355) : warning 203: symbol is never used: "OnEntityDestroyed"
// Code size:             2992 bytes
// Data size:             2368 bytes
// Stack/heap size:     262144 bytes
// Total requirements:  267504 bytes
//
// 1 Warning.
//
// Compilation Time: 0.12 sec
// ----------------------------------------

# Problematic Code (or Steps to Reproduce)
  compile the code below

  // TODO(you): code here to reproduce the problem
```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>
#include <sdktools>
#include <sdkhooks>

// WTF? -> warning 203: symbol is never used: "OnEntityDestroyed"
void OnEntityDestroyed(int entity)
{
    LogMessage("OnEntityDestroyed: %d", entity);
}
```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by Impact123** [comment]
You're missing ```public```

**Comment by naris** [comment]
doh

**Comment by KyleSanderson** [comment]
All good, glad you were able to solve it.
