### ISSUE TITLE
[L4D2] Unrecognized library matchmaking_ds

### ISSUE THREAD

**Issue by ProjectSky** [alliedmodders/sourcemod#1466]
# Help us help you
  - [ ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Ubuntu 20.04.2
  * Game/AppID (with version if applicable): 550
  * Current SourceMod version: 1.10.0.6497
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
https://forums.alliedmods.net/showthread.php?t=331732
#1006

# Problematic Code (or Steps to Reproduce)

# Logs

**Comment by spumer** [comment]
Should be fixed in https://github.com/alliedmodders/sourcemod/pull/1504

**Comment by ProjectSky** [comment]
fix in https://github.com/alliedmodders/sourcemod/pull/1504
