### ISSUE TITLE
Built-in JSON module

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcemod#1468]
I suggest add built-in JSON module into SourceMod base distro. In AMXX JSON is already "out-of-box" since 30 Sep 2017 (https://github.com/alliedmodders/amxmodx/pull/379).

@ErikMinekus in [REST in Pawn](https://github.com/ErikMinekus/sm-ripext) provided very handy API for working with JSON objects.
Maybe he can create a PR with part of RiP code related with JSON?

**Comment by asherkin** [comment]
This is the kind of feature request that makes more sense to prototype as an extension that can get community buy-in and then be adopted upstream if/when it makes sense.

Given the large scope and lack of concrete use cases, I don't think there is anything actionable here currently - to try and keep the issue list slightly cleaner I'm going to close this for now. Issues filed here should really have a strong "I need this [bug fixed / core feature added] to solve [concrete problem I'm having]" vibe - anything else should be a forum thread.
