### ISSUE TITLE
NULL_VECTOR in stack breaks TeleportEntity

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1471]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 10
  * Game/AppID (with version if applicable): 500
  * Current SourceMod version: 1.11.0.6675
  * Current SourceMod snapshot: 1.11.0.6675
  * Current Metamod: Source snapshot: 1.10.7
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
When you use NULL_VECTOR for optional argument of your own function (instead of {0.0, 0.0, 0.0}), further call to TeleportEntity fails.

# Problematic Code (or Steps to Reproduce)
  ```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>
#include <sdktools>

#define BUG 1

public void OnPluginStart()
{
	RegConsoleCmd("sm_te", CmdTe, "Teleports yourself to a random player");
}

public Action CmdTe(int client, int argc)
{
	Tele(client);
	return Plugin_Handled;
}

#if BUG
void Tele(int client, float vec[3] = NULL_VECTOR)
#else
void Tele(int client, float vec[3] = {0.0, 0.0, 0.0})
#endif
{
	int team = GetClientTeam(client);
	
	for( int i = 1; i <= MaxClients; i++ )
	{
		if( i != client && IsClientInGame(i) && GetClientTeam(i) == team )
		{
			GetClientAbsOrigin(i, vec);
			TeleportEntity(client, vec, NULL_VECTOR, NULL_VECTOR);
			PrintToChat(client, "%N teleported to pos: %f %f %f", client, vec[0], vec[1], vec[2]);
			break;
		}
	}
}
  ```

# Logs
In both cases with #define BUG 1 and 0 console log reports a correct position of other player:
```
Drakoshka teleported to pos: 1926.089111 1005.284240 432.031250
```
but in case BUG 1 (NULL_VECTOR as a default value) the TeleportEntity does nothing.
Player hasn't teleport.
No error logs in log folder or server console.
With BUG 0 ({0.0, 0.0, 0.0} as a default value) everything works OK, as expected.

**Comment by ErikMinekus** [comment]
> but in case BUG 1 (NULL_VECTOR as a default value) the TeleportEntity does nothing.
> Player hasn't teleport.

```
const float[3] origin
New origin, or NULL_VECTOR for no change.
```

So it behaves as it should?

**Comment by asherkin** [comment]
This seems to be working correctly, the identity of the `NULL_VECTOR` constant is being preserved through the call (and your code is erroneously changing its value, which can confuse other plugins misusing if) so `TeleportEntity` is not doing a position change (as documented).

`NULL_VECTOR` is a magic identifier for native functions, your use of it here in a non-native doesn't make a lot of sense really. It is not just a all-zero vector (and in fact it is often not filled with zeros, due to usage like your code.)

**Comment by peace-maker** [comment]
You can check if `NULL_VECTOR` was passed to your function using `IsNullVector`. It's for C natives differentiating between a `nullptr` and the vector `{0.0, 0.0, 0.0}`. If you need that kind of optional argument in your own code, use `IsNullVector` (or `IsNullString`) in your functions. There's `IsNativeParamNullVector` for your native callbacks too.

Your use case shouldn't be using `NULL_VECTOR` at all though as was mentioned.

**Comment by dragokas** [comment]
Thanks for an explanation.

```
PrintToChat(client, "IsNull? %b", IsNullVector(vec));

```
is really returns true.

Still, I can't understand how the same variable can hold simultaneously 2 "values" - nullptr and array ptr,
so for TeleportEntity and IsNullVector it is recognized as nullptr and at the same time for PrintToChat vec[0] is recognized as a normal array item with a value assigned before.

**Comment by asherkin** [comment]
If you look at where `NULL_VECTOR` is defined in `core.inc`:

```sourcepawn
public float NULL_VECTOR[3];        /**< Pass this into certain functions to act as a C++ NULL */
```

When a plugin is loaded SM looks up the address of this variable and stores it against the plugin, if a native needs a special `NULL` vector input, it can then check the address of the passed in parameter against this stored address - which is what `IsNullVector` does.

From the plugin perspective (and any native that doesn't have special logic to handle `NULL_VECTOR`) it is just the same as any other `float[3]` array.

**Comment by dragokas** [comment]
Understood. Thanks a much!
