### ISSUE TITLE
Add GetFilePermissions()

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1476]
Hi,

please, add a function to be able to retrieve file security information.
Such as:
 - GetFilePermissions in a counterweight to [SetFilePermissions](https://sm.alliedmods.net/new-api/files/SetFilePermissions).

**Comment by MAGNAT2645** [comment]
It would be also useful to have octal format specifier `%o` (for debugging purposes).
But i'm not sure if i should create a Feature Request for that.
