### ISSUE TITLE
SetClientMoney to api

### ISSUE THREAD

**Issue by eyal282** [alliedmodders/sourcemod#1478]
This is halfassed for now in the goal to make it faster. In general, in CS:GO setting money can break horribly against the system of bot takeovers.

**Comment by CrazyHackGUT** [comment]
This is game specific API, so it shouldn't be in core. In Team Fortress 2, for example, players don't have any money.

**Comment by eyal282** [comment]
> This is game specific API, so it shouldn't be in core. In Team Fortress 2, for example, players don't have any money.

CS_SetClientMoney / CS_GetClientMoney

**Comment by KyleSanderson** [comment]
Can you clarify what you're actually looking for here, and what should be done. Doesn't setting m_iAmmount do this?

**Comment by Wend4r** [comment]
> m_iAmmount

*m_iAccount
```sourcepawn
GetEntProp(client, Prop_Send, "m_iAccount");
// and
SetEntData(client, Prop_Send, "m_iAccount", 123);
```
There are also `m_iStartAccount` - How much cash this player started the round with.

**Comment by eyal282** [comment]
> Can you clarify what you're actually looking for here, and what should be done. Doesn't setting m_iAmmount do this?

Try taking over a bot in CS:GO and this idea straight up collapses. At least during my AS development it was like this.

**Comment by Wend4r** [comment]
According to the inheritance hierarchy, CCSBot inherits CCSPlayer where is this NetProp variable. I don't think there should be a problem with that.
