### ISSUE TITLE
CommandExists() case sensitive alternative

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1480]
At the moment, [CommandExists()](https://sm.alliedmods.net/new-api/console/CommandExists) is case insensitive, so it is useless for cases when I need to check for:

```
CommandExists("sm_ADMIN")
```
returns true, however, ~~such command "sm_ADMIN"  cannot be handled by console.~~ such chat command "!ADMIN" cannot be handled.

Is it possible to add a new command like CommandExistsEx() or an optional argument, allowing to check "Is Command Exists" considering case sensitivity?

Thank you.

**Comment by KyleSanderson** [comment]
I took a look at your plugin and it looks like it can be improved, you should be using AddCommandListener(listener); and it will listen for all commands. When you miss, check your caselower trie, and finally when you can't find the command in your cache, do the full iteration, then log the unknown command. When there's a dozen or so unknown commands within a couple frames, kick the client or something. Does that make sense?

**Comment by dragokas** [comment]
There is no sense to go to the full iteration logic when the sm engine already should care about easy access to such pre-cached command list to check for existence.

CommandExists() is clearly lying. Console can't handle sm_ADMIN, and that case should be properly indicated by CommandExists() return value.

As about my plugin, I'm doing exactly as you described with exception - instead of AddCommandListener, I'm using list of commands retrieved from GetCommandIterator() and precached in StringMap. But that list cannot be further updated during gameplay due to a significant lag caused by too many items in that list. This required e.g. for cases when some plugins get dynamically loaded and registered new commands, so:
 - I can't rely on CommandExists() - it is case insensitive.
 - I can't rely on GetCommandIterator() - due to lag.

**Comment by dvander** [comment]
Adding a case sensitivity to this seems very reasonable. That said, I'm struggling to see where this is case insensitive. CommandExists() is a wrapper around GetCommandFlags(), which is implemented here:

https://cs.alliedmods.net/sourcemod/source/core/smn_console.cpp#138

And all of this looks case sensitive, except maybe icvar->FindCommandBase which we don't have the source to.

So you might have to experiment to see why this is happening.

**Comment by Wend4r** [comment]
In the engine, command characters are converted to the upper case, and then compared by hash.
https://cs.alliedmods.net/hl2sdk-csgo/source/tier1/generichash.cpp#101-118

**Comment by dvander** [comment]
Weird - why does the console reject it then? Anyway, a GetCommandFlags with a case sensitivity option would be fine.

**Comment by Wend4r** [comment]
> Weird - why does the console reject it then?

It is processed in the server/client console 
```
sm_ADMIN
sm_admin
sm_admin1
Unknown command "sm_admin1"
```
> Anyway, a GetCommandFlags with a case sensitivity option would be fine.

0_0
https://github.com/alliedmodders/sourcemod/blob/1fbe5e1daaee9ba44164078fe7f59d862786e612/plugins/include/console.inc#L722-L725

**Comment by Headline** [comment]
Some engines don't care about command case sensitivity and some do. I don't see how this is such a huge problem considering any reasonable plugin author is going to be developing plugins will all lowercase command names

**Comment by dragokas** [comment]
> > Weird - why does the console reject it then?
> 
> It is processed in the server/client console
> 
> ```
> sm_ADMIN
> sm_admin
> sm_admin1
> Unknown command "sm_admin1"
> ```

Yes, you are right. I've almost slept, when answered. Sorry all for confusion.
I was mean, such command:
```
!ADMIN
```
is not handled when it is entered in chat, such a way not possible to verify it using CommandExists().
Dunno, is it a bug in chat handlers.

**Comment by asherkin** [comment]
It is likely that chat trigger handling just needs to be updated with support for case-insensitive commands (as has slowly happened with all the other SM subsystems interacting with commands), when all of SM's command handling stuff was implemented the engine was entirely case-sensitive and Valve have been relaxing it over the years.

> I believe it was a recent patch in 1.11 that made CommandExists case insensitive

#1433

> That said, I'm struggling to see where this is case insensitive.

`m_CmdFlags` has a case-insensitive hashing policy - we were seeing bugs due to it not matching up with `FindCommandBase` and storing the same command object multiple times.

**Comment by Headline** [comment]
> It is likely that chat trigger handling just needs to be updated with support for case-insensitive commands

So to nudge this forward, are we planning on accepting all casing options now as valid input? Is that not handled by the engine or is it something we can easily switch? That's clearly the best avenue here.
