### ISSUE TITLE
Crash when trying to change the "m_szCrosshairCodes" netprop

### ISSUE THREAD

**Issue by manicogaming** [alliedmodders/sourcemod#1484]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 10 64-bit 2004
  * Game/AppID (with version if applicable): 730
  * Current SourceMod version: 1.11.0.6659
  * Current SourceMod snapshot: 6659
  * Current Metamod: Source snapshot: 1.12.0-dev+1147
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

# Problematic Code (or Steps to Reproduce)
  ```
 #include <sourcemod>
#include <sdktools>

public void OnPluginStart()
{
	HookEventEx("player_spawn", OnPlayerSpawn);
}

public void OnPlayerSpawn(Event eEvent, const char[] szName, bool bDontBroadcast)
{
	for (int i = 1; i <= MaxClients; i++)
	{
		if (IsClientInGame(i))
		{    
			SetEntPropString(GetPlayerResourceEntity(), Prop_Send, "m_szCrosshairCodes", "CSGO-m9FPN-ZHep5-OUAV7-qMUyG-xJ8nM", i);
		}
	}
}
  ```

# Logs
[https://crash.limetech.org/s6vcvyovpzul](https://crash.limetech.org/s6vcvyovpzul)

**Comment by asherkin** [comment]
That crash report doesn't appear to be related, can you still reproduce this with the latest 1.11 snapshot?

**Comment by manicogaming** [comment]
It still crashes
[https://crash.limetech.org/3kpxl66rtzdz](url)
