### ISSUE TITLE
TR_DidHit returns true if world was hit but filtered out in the custom trace

### ISSUE THREAD

**Issue by bottiger1** [alliedmodders/sourcemod#1487]
Not sure if the fault lies with Valve, but TR_DidHit returns true if entity 0 (world) was hit but you have a custom filter specifying that 0 does not collide.

To reproduce, just copy and paste this code, noclip into the world with no other players. IsPlayerStuckInPlayer will return true.

```
static bool IsPlayerStuckInPlayer(int client)
{
    float origin[3];
    float mins[3];
    float maxs[3];
    
    GetEntPropVector(client, Prop_Send, "m_vecOrigin", origin);
    GetEntPropVector(client, Prop_Send, "m_vecMins", mins);
    GetEntPropVector(client, Prop_Send, "m_vecMaxs", maxs);

    TR_TraceHullFilter(origin, origin, mins, maxs, CONTENTS_SOLID, TraceFilter, client);
    return TR_DidHit();
}

static bool TraceFilter(int entity, int mask, int client)
{
    if(entity == client)
    {
        return false;
    }

    if(entity > 0 && entity <= MaxClients && IsPlayerAlive(entity))
    {
        return true;
    }
    
    return false
}
```

**Comment by KyleSanderson** [comment]
(From memory) There's something messed up with traces when players have the exact same coordinates. If I remember correctly it's actually cheaper to bulk get the coordinates then do the math as opposed to using traces (but this obviously can change over time).

**Comment by bottiger1** [comment]
No other player is needed for this bug. It also happens when you check things besides players as well.

**Comment by asherkin** [comment]
Looking at the SDK code, this behaviour appears to be correct. You want to check `TR_GetEntityIndex() > 0` instead (which corresponds to `CGameTrace::DidHitNonWorldEntity`). `TR_DidHit` is very coarse, it might be a good note for the docs.
