### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Truyn** [alliedmodders/sourcemod#1496]
https://www.reddit.com/r/GlobalOffensive/comments/gseioz/massive_memory_leak/

I saw fixes from this one on sale, can the respected developers of sourcemod also fix this?

I apologize for the incorrect design, English is not my native language, it is quite difficult for me to navigate.

**Comment by asherkin** [comment]
This doesn't appear to be a SourceMod bug, if you're looking for a plugin to patch this you should post on [the forum](https://forums.alliedmods.net/forumdisplay.php?f=60).
