### ISSUE TITLE
Stream I/O

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcemod#1499]
I suggest implement Stream API, like something [C# have](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-5.0).
For basically, in SM can be implemented two stream types: Files and in-memory streams (some code write in something memory part, another reads).
Also this should have API for extensions. For example, plugin should can create in-memory stream, write 5 mbytes and pass this to HTTP client (like [REST in Pawn](https://github.com/ErikMinekus/sm-ripext)).

**Comment by asherkin** [comment]
This is the kind of feature request that makes more sense to prototype as an extension that can get community buy-in and then be adopted upstream if/when it makes sense.

Given the large scope and lack of concrete use cases, I don't think there is anything actionable here currently - to try and keep the issue list slightly cleaner I'm going to close this for now. Issues filed here should really have a strong "I need this [bug fixed / core feature added] to solve [concrete problem I'm having]" vibe - anything else should be a forum thread.
