### ISSUE TITLE
File.ReadLine doesn't exclude line ending from buffer

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1502]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 10
  * Game/AppID (with version if applicable): ---
  * Current SourceMod version: 1.11.0.6675
  * Current SourceMod snapshot: 1.11.0.6675
  * Current Metamod: Source snapshot: 1.10.7

# Description
Not sure is it by design. When you read file with File.ReadLine(), it includes line ending characters in the destination buffer.
So, you quite often forced to include TrimString() to prevent further parsing errors.

# Problematic Code (or Steps to Reproduce)
  ```
public void OnPluginStart()
{
	char str[128];
	File hFile = OpenFile("addons/test.txt", "r");
	if( hFile )
	{
		while( !hFile.EndOfFile() && hFile.ReadLine(str, sizeof(str)) )
		{
			PrintToServer("Initial line:");
			PrintChars(str);
			
			PrintToServer("After TrimString():");
			TrimString(str);
			PrintChars(str);
			break;
		}
		delete hFile;
	}
}

void PrintChars(char[] str)
{
	int ch;
	PrintToServer("string: %s", str);
	
	for( int i = 0; i < strlen(str); i++ )
	{
		ch = str[i];
		PrintToServer("%i. %i", i, ch);
	}
}
  ```

# Logs
File contents:
```
a<CR><LF>
b
```
Server log:
```
Initial line:
string: a

0. 97
1. 13
2. 10
After TrimString():
string: a
0. 97
```

**Comment by asherkin** [comment]
This is the expected behaviour for `ReadLine - it matches common `fgets` behaviour.
