### ISSUE TITLE
CS_TerminateRound doesn't work well.

### ISSUE THREAD

**Issue by Smesh292** [alliedmodders/sourcemod#1503]
# Help us help you
  - [yes ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ yes] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ yes] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: 
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [yes ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [yes ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ yes] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Function doesn't work well.

# Problematic Code (or Steps to Reproduce)
  ```Function crash on CS_TerminateRound(0.0, CSRoundEnd_CTWin)
![2021-06-16 (125)](https://user-images.githubusercontent.com/44304306/122249011-2ccc3800-ced1-11eb-9fc2-077dbeddb176.png)
![2021-06-16 (125)](https://user-images.githubusercontent.com/44304306/122249052-348bdc80-ced1-11eb-9449-e0eb74abdbb7.png)


  // TODO(you): code here to reproduce the problem
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.
![2021-06-16 (125)](https://user-images.githubusercontent.com/44304306/122249086-39e92700-ced1-11eb-981a-619b90418be7.png)

**Comment by Natanel-Shitrit** [comment]
`CS_TerminateRound()` works fine for me.

**Comment by Natanel-Shitrit** [comment]
looks like a recursion, `deathmatch.sp` is calling to `CS_TerminateRound()` inside a `cs_win_panel_round` event (which happens in round end) hence they will call each other and eventually eat up all the stack memory, this is unrelated to sourcemod.

Please contact the author of this plugin, and ask him to fix it.

**Comment by Smesh292** [comment]
Thank you.
