### ISSUE TITLE
Add DeleteDirectory()

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1508]
Can you, please, add DeleteDirectory() in the counterweight of [CreateDirectory](https://sm.alliedmods.net/new-api/files/CreateDirectory)?

It's useful for making an uninstallation procedure for some stuff willing to clear itself by the user's request.

**Comment by Natanel-Shitrit** [comment]
[`RemoveDir()`](https://sourcemod.dev/#/files/function.RemoveDir)

**Comment by dragokas** [comment]
Well, other naming.
Thanks for letting me know.
