### ISSUE TITLE
Server crash on FrameIterator initialization

### ISSUE THREAD

**Issue by GAMMACASE** [alliedmodders/sourcemod#1517]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Current SourceMod snapshot: 1.11.0.6703
  * Current Metamod: Source snapshot: 1.12.0-dev+1147
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
As the title suggests, server crashes whenever FrameIterator is initialized (same if the plugin was late loaded). Currently it's fine on earlier versions of sm (latest versions of 1.10 for example works fine).

# Problematic Code (or Steps to Reproduce)
  ```
#include "sourcemod"

public void OnPluginStart()
{
	FrameIterator iter = new FrameIterator();
	delete iter;
}
  ```

# Logs
* Accelerator crash report: https://crash.limetech.org/ncsatv52kasc

**Comment by peace-maker** [comment]
`IFrameIterator::FunctionName` and `IFrameIterator::FilePath` can return null on failure. std::string can't be assigned a nullptr, but the old amtl AString was fine with that I guess? We're missing null checks here now.

https://github.com/alliedmodders/sourcemod/blob/b0563a493ce0661156c6080cdd7e37a7bbae9bfb/core/logic/FrameIterator.h#L59-L60
