### ISSUE TITLE
Windows - DOD:S - sm_slay not work

### ISSUE THREAD

**Issue by ambaca** [alliedmodders/sourcemod#1524]
https://github.com/alliedmodders/sourcemod/blob/d7c359c4122d860deb7b0401a0e068514cfd7190/gamedata/sdktools.games/game.dod.txt#L57

Previous dod:s update changed windows offset.
- Offset 439 seems work right. I have not tested in Linux.

**Comment by KyleSanderson** [comment]
hmm. Our tooling may be bugged, but the runs we have doesn't have this as changing
`O: CommitSuicide          - GOOD.    current [ w: 438, l: 439 ].`

To verify, you've turned off the gamedata updater when you changed the offset, correct?

**Comment by ambaca** [comment]
Yes, gamedata update had to disabled to test different offset.
Update is so fast to overwritten gamedata file, couldn't test custom offset.

**Comment by KyleSanderson** [comment]
@asherkin you're much better at this stuff than I am - do you know what we should do here?

**Comment by ambaca** [comment]
Apologize for making this issue... I noticed in game, sm_slay do not work on player who just spawned.
Player need move little bit out of spawn location, then sm_slay work.

Don't know reason of this. Decompiling map I see HINT/SKIP brush over spawn location.
Could be another game setting reason.

Let's forget this issue for now.

Let's make new one if I was totally wrong.
