### ISSUE TITLE
Support stripping plugin debug info

### ISSUE THREAD

**Issue by Wend4r** [alliedmodders/sourcemod#1525]
In connection with the decision https://github.com/alliedmodders/sourcepawn/pull/581#issuecomment-874671296 ("We are not going to support stripping out debug/RTTI info."), in this issue, I will leave code where do you support stripping debug info.

**Comment by Wend4r** [comment]
https://github.com/alliedmodders/sourcemod/blob/5d94f0bea863ad6bee71ddc829c32af296cc0f8b/core/logic/DebugReporter.cpp#L216-L220
https://github.com/alliedmodders/sourcemod/blob/5d94f0bea863ad6bee71ddc829c32af296cc0f8b/core/logic/DebugReporter.cpp#L229-L233

**Comment by dvander** [comment]
Debug info and RTTI are very different. Debug info doesn't affect runtime operation. RTTI does. New features will be more and more dependent on RTTI, and removing it will simply not be feasible. Once the new parser is in better shape, bytecode will directly embed links to RTTI sections, and won't run without it.

Debug info, on the other hand, has historically been buggy. We don't try too hard to validate it. If it's missing, the VM will still work. That said, if your goal is obfuscation: don't get too excited. Once the new parser is complete we will move to source-distribution of plugins. That is likely a long time away though.

**Comment by dvander** [comment]
The LookupFunction call is an example of a special case, it's only used for debugging at the moment. However, it relies on RTTI. For 1.11 (and I believe 1.10?) RTTI is required and this should fail validation in MethodVerifier. For pre-RTTI versions of spcomp, we can accept that the function might not have a valid debug entry.

**Comment by Wend4r** [comment]
I stick to the idea that JIT should be able to work with and without debugging. If you want to want to fence off non-debugging SMX, as I understood from https://github.com/alliedmodders/sourcepawn/pull/581#issuecomment-874671296 , but remove the subsequent work with non-debugging and giving understandable error when does SMX start. I ask you to make a safe code for this, as I did, but in terms of correct working without debugging.

**Comment by KyleSanderson** [comment]
https://github.com/alliedmodders/sourcemod/issues/1525#issuecomment-874844133

I can't speak for the project in general, but from how it reads to me is fencing off invalid code generation. If another tool is generating invalid headers with valid byte code: that's an issue with the generator. Hardening the project like you mentioned seems worthwhile, working around issues for buggy compilers moves the conversation in another direction. It's like writing valid code in C, GCC has a bug, and then the kernel works around it. The kernel shouldn't crash, but it shouldn't rewrite DWARF information and should instead kill the process if it needs it.

**Comment by dvander** [comment]
The JIT does not require debugging. It _does_ require RTTI, and this will not (and cannot) change.

However, let's be realistic: the only reason to strip debug info is to circumvent SourceMod's licensing requirements. Why would we take code to support that use case?

**Comment by Wend4r** [comment]
> However, let's be realistic: the only reason to strip debug info is to circumvent SourceMod's licensing requirements. Why would we take code to support that use case?

I strips off SMX debugging, so that it would be very difficult for my hosting to disassemble it, in case it is stolen from the server.

**Comment by Headline** [comment]
> > However, let's be realistic: the only reason to strip debug info is to circumvent SourceMod's licensing requirements. Why would we take code to support that use case?
> 
> 
> 
> I strips off SMX debugging, so that it would be very difficult for my hosting to disassemble plugin, in case it is stolen from the server.

Any host that steals your plugins is a host you should not do business with. I personally don't like that argument and don't agree that it's a valid one to champion this issue forward.

**Comment by KyleSanderson** [comment]
@Wend4r Closing this one now that https://github.com/alliedmodders/sourcepawn/issues/580 has landed. If it should remain open please let us know why.
