### ISSUE TITLE
Expose 'CBaseAnimating::GetAttachment' function

### ISSUE THREAD

**Issue by KoNLiG** [alliedmodders/sourcemod#1555]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  
# Description

As discussed [here](https://discord.com/channels/335290997317697536/335290997317697536/870079382079799317) there is a function to retrieve an attachment origin & angles called `CBaseAnimating::GetAttachment`.

It would be nice if a native will be added to access this function.

**Comment by asherkin** [comment]
This is a very common SDKCall used in plugins and I think it'd be a great idea to have a native for it.

Marking as good-first-issue as the implementation should be relatively straightforward for anyone familiar with SDKCall looking to get a start in C++ land - we have a lot of very similar natives already that can be cribbed from.
