### ISSUE TITLE
Private forward crashing server when handle is destroyed in mid-call

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1565]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 10
  * Game/AppID (with version if applicable): -
  * Current SourceMod version: 1.11.0.6731
  * Current SourceMod snapshot: 1.11.0.6731
  * Current Metamod: Source snapshot: 1.10.7
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Following code crashing the server:

# Problematic Code (or Steps to Reproduce)
  ```
#include <sourcemod>

PrivateForward	g_fwd;

public void OnPluginStart()
{
	g_fwd = new PrivateForward(ET_Ignore);
	g_fwd.AddFunction(GetMyHandle(), foo);
	Action result;
	Call_StartForward(g_fwd);
	Call_Finish(result);
}

public void foo()
{
	delete g_fwd;
	
	// Safe version:
	// g_fwd.RemoveAllFunctions(GetMyHandle());
	// delete g_fwd;
}

  ```
https://crash.limetech.org/24bzgibx5ryy

Can you please add a protection / throwing error / or auto-execution of RemoveAllFunctions() on handle destruction?

**Comment by asherkin** [comment]
Thanks - this is already open as #1041.
