### ISSUE TITLE
Engine throws ERROR_HANDLE_EOF when use_valve_fs turned on

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1567]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 7
  * Game/AppID (with version if applicable): 730 (CS:GO)
  * Current SourceMod version: 1.11.0.6736
  * Current SourceMod snapshot: 1.11.0.6736
  * Current Metamod: Source snapshot: 1.11.0.1145
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Following code causing server console to throw error 38:

# Problematic Code (or Steps to Reproduce)
  ```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>

public void OnPluginStart()
{
	File hr = OpenFile("resource/valve_english.txt", "rb", true);
	if( hr )
	{
		int bytesRead, buff[1024];
		
		while( !hr.EndOfFile() )
		{
			bytesRead = hr.Read(buff, sizeof(buff), 1);
				
			PrintToServer("bytes read: %i", bytesRead);
		}
		delete hr;
	}
}
  ```

# Logs
```
...
bytes read: 1024
bytes read: 1024
bytes read: 1024
Unknown read error 38
bytes read: 772
```
If you set "use_valve_fs" argument to false, an error is not appearing.
I'll clarify the file is still located locally, not in a container.

Error is specific to CS:GO. For L4D1 & L4D2 everything works normally.

**Comment by Wend4r** [comment]
> Any ideas about topic, why CSGO throw "Unknown read error 38" ?

https://gist.github.com/vtellier/e04f78ce29cfb519e49e352fa745d7d1#file-lasterror-h-L60

**Comment by asherkin** [comment]
This looks like it is probably a bug in the engine's implementation of overlapped IO on Windows, can you see if the problem still happens if you set the `filesystem_use_overlapped_io` hidden cvar to `0`?

**Comment by dragokas** [comment]
@asherkin sorry for late reply.
Unfortunately,
```
sm_cvar filesystem_use_overlapped_io 0
```
didn't helped to bypass the error message.

And, yeah, there are more issues with valve_fs when reading larger files (maybe not related?): https://github.com/alliedmodders/sourcemod/issues/1577

**Comment by asherkin** [comment]
I don't think there is anything we can do here, our usage of the filesystem API all seems correct (and as you say it works on all other games). I'm going to close this as a Valve issue until something surfaces indicating that SM is using the API incorrectly.
