### ISSUE TITLE
Low performance reading the large file with use_valve_fs turned on

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1577]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 7
  * Game/AppID (with version if applicable): 730 (CS:GO)
  * Current SourceMod version: 1.11.0.6736
  * Current SourceMod snapshot: 1.11.0.6736
  * Current Metamod: Source snapshot: 1.11.0.1145
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
By executing the following code the script execution timeout happens:

# Problematic Code (or Steps to Reproduce)
  ```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>

public void OnPluginStart()
{
	int bytesRead, buff[1024];
	File hFile = OpenFile("resource/csgo_english.txt", "rb", true);
	if( hFile )
	{
		PrintToServer("File size: %i", GetFileSize(hFile));
	
		while( !hFile.EndOfFile() )
		{
			bytesRead += hFile.Read(buff, sizeof(buff), 1);
		}
		delete hFile;
	}
	PrintToServer("Total bytes read: %i", bytesRead);
}

int GetFileSize(File hFile)
{
	int save_pos = hFile.Position;
	hFile.Seek(0, SEEK_END);
	int size = hFile.Position;
	hFile.Seek(save_pos, SEEK_SET);
	return size;
}
  ```

# Logs
```
File size: 5421686
L 09/07/2021 - 22:36:51: [SM] Exception reported: Script execution timed out
```

If you turn OFF the use_valve_fs:
```
File hFile = OpenFile("resource/csgo_english.txt", "rb", false);
```

File read almost instantly:
```
File size: 5421686
Total bytes read: 5421686
```

Problem is specific to CS:GO only.

**Comment by asherkin** [comment]
Do you have any reason to believe the performance issue is on the SM side? If the performance is so much better when using SM's filesystem implementation instead of the engine's, it seems pretty clear this is a Valve issue.

**Comment by dragokas** [comment]
No. I'm not familiar with implementation. The documentation is not clear about that.
```
bool use_valve_fs
If true, the Valve file system will be used instead. This can be used to find files existing in valve search paths, rather than solely files existing directly in the gamedir.
```
If that means, read function is fully switched to use Valve API, it makes sense the performance issue is solely related to Valve code.

**Comment by dragokas** [comment]
Just to mention, @SilvDev done a walkaround:
https://forums.alliedmods.net/showthread.php?t=334905
