### ISSUE TITLE
Latest TF2 update seems to break sourcemod and metamod

### ISSUE THREAD

**Issue by bottiger1** [alliedmodders/sourcemod#1582]
- IServer->GetMapName() returns null 
- SetEntProp in Sourcemod causes segfault.
- CPlayer::Initialize(char const*, char const*, edict_t*) causes segfault.

Possibly more issues but those are the ones I see so far.

Did some investigation and it seems like the sdk has changed with functions being added and removed.

**Comment by bottiger1** [comment]
@psychonic 

This line still seems to be crashing sourcemod.

https://github.com/alliedmodders/sourcemod/blob/6a2ac9800bfd10ec986d18d2286177f4cbc52803/core/smn_console.cpp#L1243

**Comment by WOLFA22** [comment]
![image](https://user-images.githubusercontent.com/35665773/133728512-e1ed5b4b-6bf7-40cc-8e56-77112881ed8e.png)
OllyDebug 2.00
