### ISSUE TITLE
Translated buffers are early null terminated

### ISSUE THREAD

**Issue by Adrianilloo** [alliedmodders/sourcemod#1594]
I've just noticed what seems to be an important issue.

When holding a string buffer of size `N`, formatting it without involving translations allow for the null terminator to be placed at the last cell as much (`N - 1`), correctly. However, when a translation is used while formatting, the null terminator is written as much late at the `N - 2` cell. This causes to always render one cell of the max. length useless.

See attached picture for an illustrative sample.

![Captura](https://user-images.githubusercontent.com/15228896/136632208-e316897a-31e6-4a66-90e9-fbac367459dc.PNG)

Thank you.

**Comment by Wend4r** [comment]
@dvander, if you have time to fix it, then I also had a problem with the fact that when throwing an exception from `atcprintf`, that it did not terminate running the SP code, I think this is not in the SM style. I was too lazy to write an issue about this, sorry.

**Comment by dvander** [comment]
At this point, it's probably a compatibility issue to fix that bug :(

**Comment by Adrianilloo** [comment]
Sorry to ask, but is there any news on the main issue?

**Comment by dvander** [comment]
My guess is that this lines in sprintf.cpp:

    res = Translate(buf_p, llen, pCtx, key, *target, params, &arg, &error);

Should be:

    res = Translate(buf_p, llen + 1, pCtx, key, *target, params, &arg, &error);

`atcprintf` wants a buffer including the null terminator, but `llen` counts remaining non-null characters. Feel free to give that a try (I don't have the time at the moment to submit a PR and test).

[1] https://cs.alliedmods.net/sourcemod/source/core/logic/sprintf.cpp#1221

**Comment by Adrianilloo** [comment]
Ok,

I compiled SM on the `master` branch (aka `1.11` currently), deployed the binaries to my test server and the initial showcasing SP test now fully includes all characters in the translated buffer:

![2021-11-15 (1)](https://user-images.githubusercontent.com/15228896/141846577-0abf94b6-176a-4e0b-bafc-7087bd077c32.png)

So I can say: it works!

Not sure if the change would have any other implication. Let me know if I shall create a PR (to which branch?) or you'll do it. Have in mind I'd be interested in the patch to end in `1.10-dev` branch, at least (not sure if that's assumed).

**Comment by dvander** [comment]
Good to hear, a PR would be great.
