### ISSUE TITLE
Old 'nominate' translations are still present in non-english languages

### ISSUE THREAD

**Issue by azalty** [alliedmodders/sourcemod#1622]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Current SourceMod version: Latest stable build (1.10 - build 6522), though it must also affect any prior version

# Description

"Map Nominated" exists in rockthevote.phrases.txt in both english and french versions, but the English version isn't included in the stable builds, leading to the French one breaking cause the "Format" line isn't included. Same for all Nomination phrases inside rockthevote.phrases.

Asherkin confirmed that this was indeed an issue, but it shouldn't impact anyone using the default mapchooser and rockthevote plugins, but it does impact me because I use shavit-mapchooser.

Asherkin:
> that phrase was removed from SM in 2008
> https://github.com/alliedmodders/sourcemod/commit/4106620928bb9506f7fd8b5eba59d821da143232#diff-31669f98da4faffbab1058a351c5d80a5be34b03fdbfa802f75b4a4866e28ec5

# Problematic Code (or Steps to Reproduce)

![image](https://user-images.githubusercontent.com/36737524/139559833-6c7c3ae2-0842-4d32-bd7a-afe0173ca715.png)
This, as well as other nominate related phrases, should NOT be present into non-english languages.

https://sm.alliedmods.net/translator should display the updated english translations

Non-english translations should match the phrases in the official english translation files: https://github.com/alliedmodders/sourcemod/tree/master/translations

# Logs
It caused me to have this displayed in chat: `[SM] {1} a choisi la map {2} pour le RTV.` (formatting doesn't work, this phrase was removed a long time ago, as asherkin stated. A working one is located in nominations.phrases)

**Comment by KyleSanderson** [comment]
Fixed by https://github.com/alliedmodders/sourcemod/pull/1962
