### ISSUE TITLE
SourceMod gives an annoying error each time I talk to my server's chat via the console

### ISSUE THREAD

**Issue by justkamiii** [alliedmodders/sourcemod#1632]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows (Unknown specific version because the server is in a gameserver hosting provider)
  * Game/AppID (with version if applicable): 440
  * Current SourceMod version: 1.10.0.6512
  * Current SourceMod snapshot: N/A
  * Current Metamod: Source snapshot: N/A
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Each time I talk in my server with the ``say`` command via the console, it gives me the following error:
```
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM] Exception reported: Invalid client index 0
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM] Blaming: basecomm.smx
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM] Call stack trace:
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM]   [0] ThrowNativeError
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM]   [1] Line 39, /home/builds/sourcemod/linux-1.10/build/plugins/basecomm/natives.sp::Native_IsClientGagged
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM]   [3] BaseComm_IsClientGagged
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM]   [4] Line 137, discord_utilities/forwards.sp::OnClientSayCommand
```

# Problematic Code (or Steps to Reproduce)
1- Execute the command ``say <Anything>`` once your server is fully loaded
2- Magic

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.
```
11/05/2021 - 15:43:37: L 11/05/2021 - 15:43:37: [SM] Exception reported: Invalid client index 0
11/05/2021 - 15:43:37: L 11/05/2021 - 15:43:37: [SM] Blaming: basecomm.smx
11/05/2021 - 15:43:37: L 11/05/2021 - 15:43:37: [SM] Call stack trace:
11/05/2021 - 15:43:37: L 11/05/2021 - 15:43:37: [SM]   [0] ThrowNativeError
11/05/2021 - 15:43:37: L 11/05/2021 - 15:43:37: [SM]   [1] Line 39, /home/builds/sourcemod/linux-1.10/build/plugins/basecomm/natives.sp::Native_IsClientGagged
11/05/2021 - 15:43:37: L 11/05/2021 - 15:43:37: [SM]   [3] BaseComm_IsClientGagged
11/05/2021 - 15:43:37: L 11/05/2021 - 15:43:37: [SM]   [4] Line 137, discord_utilities/forwards.sp::OnClientSayCommand
11/05/2021 - 15:43:37: Console: corruped barney
11/05/2021 - 15:43:43: *DEAD* Haito: Barney?
11/05/2021 - 15:43:51: Client "♫" connected (censored).
11/05/2021 - 15:43:52: twitch.tv/carita_cp: ez
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM] Exception reported: Invalid client index 0
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM] Blaming: basecomm.smx
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM] Call stack trace:
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM]   [0] ThrowNativeError
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM]   [1] Line 39, /home/builds/sourcemod/linux-1.10/build/plugins/basecomm/natives.sp::Native_IsClientGagged
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM]   [3] BaseComm_IsClientGagged
11/05/2021 - 15:43:53: L 11/05/2021 - 15:43:53: [SM]   [4] Line 137, discord_utilities/forwards.sp::OnClientSayCommand
11/05/2021 - 15:43:53: Console: barney de half life/black mesa
11/05/2021 - 15:43:54: *DEAD* Haito: Ah
11/05/2021 - 15:43:58: L 11/05/2021 - 15:43:58: [SM] Exception reported: Invalid client index 0
11/05/2021 - 15:43:58: L 11/05/2021 - 15:43:58: [SM] Blaming: basecomm.smx
11/05/2021 - 15:43:58: L 11/05/2021 - 15:43:58: [SM] Call stack trace:
11/05/2021 - 15:43:58: L 11/05/2021 - 15:43:58: [SM]   [0] ThrowNativeError
11/05/2021 - 15:43:58: L 11/05/2021 - 15:43:58: [SM]   [1] Line 39, /home/builds/sourcemod/linux-1.10/build/plugins/basecomm/natives.sp::Native_IsClientGagged
11/05/2021 - 15:43:58: L 11/05/2021 - 15:43:58: [SM]   [3] BaseComm_IsClientGagged
11/05/2021 - 15:43:58: L 11/05/2021 - 15:43:58: [SM]   [4] Line 137, discord_utilities/forwards.sp::OnClientSayCommand
11/05/2021 - 15:43:58: Console: a
```

**Comment by peace-maker** [comment]
This appears to be an issue with your discord_utilities plugin, which is using the `BaseComm_IsClientGagged` native incorrectly. That's why it blames basecomm.smx.

Check that plugin :)

**Comment by justkamiii** [comment]
Oooh, I thought it was two different errors, one in basecomm's side and the other on discord_utilities. I wouldn't have done this issue if I knew that the issue wasn't from SourceMod hehe, thanks for the quick response!

**Comment by asherkin** [comment]
Thanks for the bug report though - you did find an issue with the error logging.

**Comment by justkamiii** [comment]
Wait, I did? Lmao, that's funny. Glad it helped :)
