### ISSUE TITLE
GetMenuExitBackButton is bugged?

### ISSUE THREAD

**Issue by Adrianilloo** [alliedmodders/sourcemod#1645]
I lately edited a certain plugin to conditionally add the "Exit back" button to its custom clientprefs menu depending on whether it was opened through `sm_settings` or a direct command, but, I thought of also checking `GetMenuExitBackButton` through the custom items' selections to keep the button visibility decision on menu re-instantiation.

However, it always returned `false` on the `MenuAction_Select` cases, and then, leading to the native API code seems to prove it's comparing against the wrong stored flag (`MENUFLAG_BUTTON_EXIT`):

https://github.com/alliedmodders/sourcemod/blob/1fbe5e1daaee9ba44164078fe7f59d862786e612/core/logic/smn_menus.cpp#L1017

Is this a clear mistake or I'm missing something? If I shall create a PR, that'd be straightforward.

**Comment by KyleSanderson** [comment]
Pretty sure this is an ancient typography. Nice catch.
