### ISSUE TITLE
ShouldCollide originalResult different with SM 1.11

### ISSUE THREAD

**Issue by Adrianilloo** [alliedmodders/sourcemod#1650]
Per updating my SM install from 1.10 to 1.11 recently, the value of `originalResult` changed from `true` to `false`, as of my plugin usage:

```
SDKHook(client, SDKHook_ShouldCollide, Hook_ShouldCollide);

// .......

public bool:Hook_ShouldCollide(entity, collisiongroup, contentsmask, bool:originalResult)
{
	return (isKillProtected[entity] && bNoBlock) ? false : originalResult;
}
```

What the value of `originalResult` depends on? Is it possible that something is wrong from SM?

I had noted improper collisions were being filtered out instead of succeeding after upgrading, breaking my server (players passing through bullets and other players). And for now I replaced `originalResult` with true. I was assumming the value of it was the one from the game function, but I see that doesn't make sense on a non-post hook, right?

This is the only plugin that hooks `ShouldCollide` in my server.

**Comment by psychonic** [comment]
This sounds like it could potentially just be a gamedata issue, with the wrong function being hooked.

**Comment by Adrianilloo** [comment]
The game is HL2DM, but I'm using an SSDK2013 binary. However, I've just compared official HL2DM `ShouldCollide` offset and my binary's and they're matching gamedata. Gamedata is same between `master` and `1.10` branch, anyway.

![Captura](https://user-images.githubusercontent.com/15228896/142967157-5ad509c3-575a-4458-b2bd-c8a338c8ba86.PNG)

**Comment by asherkin** [comment]
Thanks! This should be fixed now - the issue wasn't actually SM version dependent, it was a bug that had always been there, the value was just undefined.
