### ISSUE TITLE
SDKHooks not working after latest TF2 update / sourcemod updates, both dev and stable branches.

### ISSUE THREAD

**Issue by higps** [alliedmodders/sourcemod#1652]
# Help us help you
  - [X ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: All
  * Game: TF2
  * Current SourceMod version:  SourceMod 1.10.0.6528
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [x ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
SDKHooks got broken after the latest TF2 Update. When triggered, nothing happens.
SDKHook_Touch, SDKHook_PreThink, SDKHook_WeaponSwitch are the few I have tested that doesn't work right. Causing many of my plugins to not function correctly.

# Logs
No error logs are created, it's like the feature does nothing.

# Problematic Code (or Steps to Reproduce)
A simple plugin to test is Admin grab, you will not be able to grab anyone, but you will get the name popup of the player.

https://forums.alliedmods.net/showthread.php?p=1946774

**Comment by higps** [comment]
Addional note: The SDKHook_Touch works on some entities, like respawn room, but not on buildings for whatever reason.

**Comment by bakugo** [comment]
Are you absolutely sure that all your gamedata is up to date? The admingrab plugin works fine for me and so do other plugins that use sdkhooks (on the same sm version).

**Comment by higps** [comment]
Ah yes, somehow my gamedata didn't update correctly. Thanks!
