### ISSUE TITLE
SDKHooks_DropWeapon bypasses SDKHook_WeaponDrop hooks.

### ISSUE THREAD

**Issue by Alexeyt89** [alliedmodders/sourcemod#1655]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Ubuntu linux
  * Game/AppID (with version if applicable):  CSGO/730
  * Current SourceMod version:  1.11.0.6805
  * Current Metamod version:  1.12.0-dev+1156
  - [X] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [X] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [X] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
I have a plugin which uses SDKHooks_DropWeapon to drop player weapons. When the function is called other plugins don't get their drop hooks called. That is not expected and breaks the plugin behaviours.
That might be a bug/incorrect implementation of SH_MCALL. If it is, other functions utilizing SH_MCALL may also have this problem.

To reproduce the issue:
1) load "hooktest" plugin.
2) Press G to drop a weapon -> "Weapon dropped  %i" is shown, the hook works.
3) Type in console sm_dropweapons -> the weapons are dropped via SDKHooks_DropWeapon, but there is no message from the hook.
[hooktest.zip](https://github.com/alliedmodders/sourcemod/files/7612442/hooktest.zip)

Suggestions:
- fix the problem in sourcemod or SH_MCALL (if it is the reason for the problem) to make all SDK hooks reliable.
- add a new hook type and call it something like SDKHookReliable. That might, however make not reliable hooks not needed.

There is an old ticked about related problem:
https://github.com/alliedmodders/sourcemod/pull/1598/commits
But the solution doesn't fix SDKHooks_DropWeapon and doesn't offer a way to make reliable hooks.

UPD: I also noticed that SH_MCALL calls from an extension, used on my server don't make related hooks in plugins get fired.

**Comment by psychonic** [comment]
This is intentional behavior. The plugin calling SDKHooks_DropWeapon must set the blockHooks parameter to false for hooks to be able to see it.

**Comment by Alexeyt89** [comment]
Where can this parameter be set?
According to the API page there is no such parameter: https://sm.alliedmods.net/new-api/sdkhooks/SDKHooks_DropWeapon
Is there a particular purpose to have not reliable hooks?
I need to be sure that all drops made with SH_MCALL get intercepted in my plugins. How can I do that?

**Comment by Mikusch** [comment]
I believe psychonic means `bypassHooks`:
https://github.com/alliedmodders/sourcemod/blob/4e3df763582e06e6308c1c88305764f14f8311cf/plugins/include/sdkhooks.inc#L427-L438
