### ISSUE TITLE
Updater's SM 1.11 gamedata is missing SetOwnerEntity offset

### ISSUE THREAD

**Issue by KitRifty** [alliedmodders/sourcemod#1681]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Game/AppID (with version if applicable): Team Fortress 2
  * Current SourceMod version: 1.11.0.6842
  * Current Metamod: Source snapshot: 1.11.0-dev+1145

# Description
The auto-updater's game data seems to be outdated as it's missing the `SetOwnerEntity` offset, rendering the `SetOwnerEntity` and `SetEntityCollisionGroup` natives unusable, unless the gamedata is overridden or the auto-updater is disabled.

# Problematic Code (or Steps to Reproduce)
Let SM update the gamedata and check `sdktools.games/game.tf.txt`, or any gamedata for `SetOwnerEntity` offset. Offset is missing.

![image](https://user-images.githubusercontent.com/4492504/147716391-2eb599bf-ea3e-4b79-a318-698626dcf67d.png)

**Comment by asherkin** [comment]
Thanks, the autoupdater has been updated.
