### ISSUE TITLE
About HookID of DHooks behaviour

### ISSUE THREAD

**Issue by kice** [alliedmodders/sourcemod#1682]
Now we have DHooks comes with SourceMod; however, while I am writing a plugins using DHooks, I found there is an issue with the HookID. 

Current implementation just return the ID from SourceHook, and SourceHook just simply return the position of the hook in its internal list and **never free** such entry after the hook was being removed. 

My plugin will hook and unhook a lot of entities a lot of times, and my server will run 24/7. I do not except it will cause too much of a problem, but still being one more thing to keep in mind.

https://github.com/alliedmodders/metamod-source/blob/55718d2e3c91218cdfaef4c4b9cdd6fa830d596d/core/sourcehook/sourcehook_impl_chookidman.cpp#L22-L52

I am not sure if changing how SourceHook currently manager IDs would be possible or not, so make some change in DHooks might be a good idea?

Anyway, If any change needs to be made, I still would like to see the HookIDs would be unique during SRCDS process life time, so it will be safe to cache HookIDs in the plugins.

**Comment by asherkin** [comment]
As per the code you linked, freed entries are reused by later created hooks, so the list doesn't actually grow unbounded and hook IDs are not currently globally unique over SRCDS process lifetime.

What issue are you having with the current way hook IDs are implemented / exposed by DHooks?

**Comment by kice** [comment]
For my case, I think I would have close to a thousand hook at the same time and as low as less than 100. Looks like it dose not hurt the performance nor eating memory, but freeing up some memories would still be nice. It is technically unbounded but hardly cause any issues.

If an entity was hooked, and a timer will remove the hook later. However, before the timer execute, entity was killed for some reason and then another hook was created, which will reuse the same hook ID, by the same plug-in. Will the timer remove the new hook or just do nothing?

**Comment by peace-maker** [comment]
It'd remove the new hook, since the unhook native is only passed the hookid. You'll have to make sure to kill your timer in OnEntityDestroyed or pass the entity reference around together with the hookid.

I'll close this as working-as-intended. Feel free to reopen if you think the current behavior must be changed.
