### ISSUE TITLE
Bug in smx decompilation

### ISSUE THREAD

**Issue by YioLTY1994** [alliedmodders/sourcemod#1684]
good afternoon guys! during this week I found out that there is a bug in sourcemod where if we make a specific code it is not allowed to decompile to smx I tried everything to try to find this bug where it came from but I didn't get the error that appears when we decompile is ERROR NULL , and no version of sourcemod is created, they simply put the code in the compile and don't let it decompile.

**Comment by JoinedSenses** [comment]
This is a problem with Lysis on headline's website, not sourcemod
