### ISSUE TITLE
StartMessage/EndMessage (get state g_IsMsgInExec)

### ISSUE THREAD

**Issue by wS-SM** [alliedmodders/sourcemod#1693]
For example, if several plugins have done "say_team" hook and are doing this:

StartMessage..
return Plugin_Handled;

An error occurs:

```
// https://github.com/alliedmodders/sourcemod/blob/1fbe5e1daaee9ba44164078fe7f59d862786e612/core/smn_usermsgs.cpp#L421
if (g_IsMsgInExec)
{
    return pCtx->ThrowNativeError("Unable to execute a new message, there is already one in progress");
}
```

Do just return INVALID_HANDLE or let plugins know the value of variable "g_IsMsgInExec".

**Comment by asherkin** [comment]
This error indicates a plugin bug, it appears to be correct.

**Comment by wS-SM** [comment]
This is not a plugin bug, but an incompatibility between two plugins because they do the same thing. The problem is that the native CanStartMessage does not exist.

**Comment by asherkin** [comment]
Holding a global resource (like having a started usermessage) over a context switch is a plugin bug, UMs should be started, written to, and sent all within a single execution cycle.
