### ISSUE TITLE
sizeof

### ISSUE THREAD

**Issue by Smesh292** [alliedmodders/sourcemod#1711]
# Help us help you
  - [x ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: 
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [x ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

# Problematic Code (or Steps to Reproduce)
  ```sizeof
  // TODO(you): code here to reproduce the problem
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by Smesh292** [comment]
dev version have 001 and 029 error codes.

**Comment by asherkin** [comment]
This looks like an accidental submission so I'm going to close it - if you have a real issue with SourceMod, please edit the template and re-open it (don't create another new issue).

**Comment by Smesh292** [comment]
reproduce : char e[2]; Format(e, sizeof(2), "")
