### ISSUE TITLE
Arrays in Datapacks

### ISSUE THREAD

**Issue by eyal282** [alliedmodders/sourcemod#1712]
Is it possible to add normal arrays in Datapacks? This is because I want to store enum structs in Datapacks.

**Comment by asherkin** [comment]
[DataPack.WriteCellArray](https://sourcemod.dev/#/datapack/methodmap.DataPack/function.WriteCellArray) is available in 1.11. Please remember to look at the documentation / include files first, and please don't open issues for questions - asking on in the Scripting Help forum or in #sourcemod on Discord is a much better venue.

**Comment by eyal282** [comment]
> [DataPack.WriteCellArray](https://sourcemod.dev/#/datapack/methodmap.DataPack/function.WriteCellArray) is available in 1.11. Please remember to look at the documentation / include files first, and please don't open issues for questions - asking on in the Scripting Help forum or in #sourcemod on Discord is a much better venue.

I took a look in an official Alliedmods website, but I guess it only accounts for 1.10
