### ISSUE TITLE
TR_DitHit

### ISSUE THREAD

**Issue by Smesh292** [alliedmodders/sourcemod#1713]
# Help us help you
  - [x ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: 
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
TR_DitHit is undifined simbol.

# Problematic Code (or Steps to Reproduce)
  ```
  // TODO(you): code here to reproduce the problem
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by JoinedSenses** [comment]
You should join the sourcemod discord to ask questions about code... this section is for problems that exist in the framework.
