### ISSUE TITLE
Failed to load extension if more than 40 extensions 

### ISSUE THREAD

**Issue by Kxnrl** [alliedmodders/sourcemod#1722]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Win2016/2019
  * Game/AppID (with version if applicable):  740
  * Current SourceMod version: 1.10.0.6528
  * Current SourceMod snapshot: 1.10.0.6528
  * Current Metamod: Source snapshot: 1.11.0-dev+1144
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
The 40th one extension always failed to load.
The problem has nothing to do with the extension itself.

# Problematic Code (or Steps to Reproduce)
  ```
install 40+ extensions
load one by one
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.
[SM] Extension abc.ext.dll failed to load: 动态链接库(DLL)初始化例程失败。

![image](https://user-images.githubusercontent.com/3905845/155836953-d662425a-8ccc-44cf-b4fc-701fbf476452.png)

**Comment by asherkin** [comment]
> Operating System version: Win2016/2019

It looks like this is likely a Windows limitation around FLS slots.  Windows XP through to Windows 10 1809 had a limit of 128 slots, each CRT instance can require 1-2 slots, we statically link it so each SM and extension DLL will have an instance, combined with the game that seems in the right ballpark.

In Windows 10 1903 the limit was raised to 4096 slots, so if this is the issue that would certainly solve it. 

I can't find the information on the limits for the Server editions, Server 2016 would definitely not have the increased limit, Server 2019 appears to be 1809 which is just before the limit was increased. The "Windows Server" (no year) SKUs start from 1909 which would have the increased limit as long as they have kernel parity with the desktop versions.
