### ISSUE TITLE
[REQ] SQLite v3.38.0 JSON

### ISSUE THREAD

**Issue by MAGNAT2645** [alliedmodders/sourcemod#1728]
Similarly to #1592 i want to request SQLite upgrade to v3.38.0+ which has [built in JSON functions and operators](https://www.sqlite.org/json1.html#compiling_in_json_support) (not as an additional extension as it was before).
MySQL and PostgreSQL can handle JSON functions, so why SQLite driver can't have JSON support?

**Comment by ambaca** [comment]
Windows version, test version.
[[Windows] SQLite 3.38.3 - 01.05.2022](https://forums.alliedmods.net/showthread.php?t=337588)
