### ISSUE TITLE
[Solved] [DHooks] [L4D2] Stuttering when moving and jumping as survivors if moving speed is changed.

### ISSUE THREAD

**Issue by objir** [alliedmodders/sourcemod#1731]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 10 20H2
  * Game/AppID (with version if applicable): Latest L4D2
  * Current SourceMod version: 1.10.0
  * Current SourceMod snapshot: 6528
  * Current Metamod: Source snapshot: 1.11.0-git1145

# Description
 How I pinned point to DHooks:
 1. Launch Without  -insecure: the issue is gone.
 2. Launch With  -insecure but with all smx plugins Disabled: Stuttering still happens.
 3. Launch With -insecure but without extensions that are not from Sourcemod and DHooks: Stuttering still happens.
 4. Launch With -insecure but without DHooks: the issue is gone.

Also, I have tried: (1. Dev versions of Metamod: Source and SourceMod) or (2. DHooks 2.2.0-detours17 and detours16), and the stuttering still happens.

# Steps to Reproduce
 1. Install the latest stable versions of Metamod: Source, SourceMod, and DHooks.
 2. Moving or jumping as a survivor with changed movement speed (Adrenaline or In the water).

**Comment by asherkin** [comment]
There is something wrong with your reproduction process, the DHooks extension isn't loaded if there are no plugins loaded requiring it, so DHooks wouldn't have been loaded in case 2 where you still encountered the issue.

**Comment by objir** [comment]
Oh, I will check the plugins that require DHooks again.

**Comment by objir** [comment]
Sorry, It is actually caused by [https://forums.alliedmods.net/showthread.php?t=335683](Survivor Utilities (API)). Thanks for the clarification.
