### ISSUE TITLE
Feature Request: OnPlayerRunCmdPre

### ISSUE THREAD

**Issue by sapphonie** [alliedmodders/sourcemod#1759]
# Description
Having a version of OnPlayerRunCmd with a guarantee that none of the values have been touched by other plugins or extensions would be absolutely *wonderful*. I know I need it for [StAC](https://github.com/sapphonie/StAC-tf2/issues/88), I know it'd be helpful for things like [Shavit's OryxAC fork](https://github.com/shavitush/Oryx-AC), and it'd probably also be nice for any other server side anticheats.

I *really* don't want to do something [evil like dhooking sdktools](https://github.com/sapphonie/sm-onplayerruncmd-pre-evil-dontuse/blob/main/scripting/onplayerruncmd_pre.sp) (because it hooks PlayerRunCommand with a VMT hook, meaning detouring it normally would be useless) in prod to get this functionality. Please sourcemod developers, you're my only hope.

**Comment by Headline** [comment]
Love the idea, but god do I hate this naming scheme

**Comment by neko-pm** [comment]
> Love the idea, but god do I hate this naming scheme

I've got a pull request pretty much ready to go, but I was wondering about the naming as well. Given it's essentially a read only version of the OnPlayerRunCmd forward, I wonder if there would be a more appropriate name.
