### ISSUE TITLE
Alien Swarm: Reactive Drop 2022-05-24 update causing crashes in astools

### ISSUE THREAD

**Issue by BenLubar** [alliedmodders/sourcemod#1771]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: reproduced on both Ubuntu 22.04 and Win10
  * Game/AppID (with version if applicable): Alien Swarm: Reactive Drop / 563560 or 582400
  * Current SourceMod version: 
  * Current SourceMod snapshot: 1.11.0-git6884-windows ; also reported on 1.10.0-git6488-windows
  * Current Metamod: Source snapshot: 1.12.0-git1157-windows ; also reported on 1.11.0-git1130-windows
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Something broke and this plugin from 2010 is now crashing at startup. The game update changed the Steam API version; can't think of any other relevant changes that would affect the engine like this.
https://forums.alliedmods.net/showthread.php?p=1255318

# Problematic Code (or Steps to Reproduce)
1. Start server with astools.smx installed
2. Server will crash on map load in the entity search function near the bottom of astools.sp

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.
[crash dump from user](https://github.com/alliedmodders/sourcemod/files/8774358/006apf.zip)
symbol server at https://symsrv.reactivedrop.com

**Comment by psychonic** [comment]
Can you also upload your alienswarm_tools cfg?

**Comment by BenLubar** [comment]
I didn't have any files other than the dedicated server, metamod, sourcemod, and astools.smx

**Comment by psychonic** [comment]
It looks like the EntInfo gamedata for Windows needs to be updated.

**Comment by psychonic** [comment]
I've updated the gamedata for that and some other things. Some things could be missing or wrong, but it's in a better state than it was, and that specific crash has been fixed.

It looks like Reactive Drop had been updated to use a newer compiler version.
