### ISSUE TITLE
Cant find the compiler

### ISSUE THREAD

**Issue by Kolesos** [alliedmodders/sourcemod#1774]
Hello! I've been trying to compile a script offline cause it had custom include, I can't find The script folder where the compiler is. Can you please help me?

**Comment by rumblefrog** [comment]
Issue tracker is for code base related issues, use Discord or the forum next time.

https://www.sourcemod.net/downloads.php?branch=stable

https://wiki.alliedmods.net/Compiling_SourceMod_Plugins

**Comment by Kolesos** [comment]
Hello! I saw the second link about compiling but i downloaded source mod
but there is no scripting folder, do i have to start a local host server
for the script folder to be written  by it self ?

**Comment by rumblefrog** [comment]
it’s in sourcemod, please look.
