### ISSUE TITLE
Error Failed to find WriteBaselines signature -- stringtable error workaround disabled.

### ISSUE THREAD

**Issue by Truyn** [alliedmodders/sourcemod#1776]
L 06/04/2022 - 03:20:54: [SDKTOOLS] Sigscan for WriteBaselines failed
L 06/04/2022 - 03:20:54: [SDKTOOLS] Failed to find WriteBaselines signature -- stringtable error workaround disabled.

system linux debian 11
version sourcemode  SourceMod Version: 1.10.0.6540
version server
Protocol version 13833 [1477/1477]
Exe version 1.38.3.3 (csgo)
Exe build: 22:27:01 May 23 2022 (8598) (730)

Updated both sourcemod and the server and the effect is zero, the error still appears

P.s i use pterodactyl

**Comment by Headline** [comment]
This gamedata is updated already, either the server is updated and SourceMod isn't or vice versa. Ensure that your signature for WriteBaselines in `gamedata/sdktools.games/engine.csgo.txt` matches the following:

https://github.com/alliedmodders/sourcemod/blob/7424deefb9d0d21a008d000347abe76f59fd57c0/gamedata/sdktools.games/engine.csgo.txt#L390

**Comment by Truyn** [comment]
![image](https://user-images.githubusercontent.com/53527324/172056946-8345044b-90cd-4c2e-a577-f499ed2f6cc3.png)

**Comment by Truyn** [comment]
"WriteBaselines" I have exactly the same string value as the current one

**Comment by Truyn** [comment]
I say that I have the latest version of the server, as well as the version of sourcemod

**Comment by Truyn** [comment]
![image](https://user-images.githubusercontent.com/53527324/172057177-cbe287cd-26f4-47de-a637-c97c8215af89.png)

**Comment by Truyn** [comment]
The error is not on all servers, but on all the server version is the same

**Comment by Truyn** [comment]
![image](https://user-images.githubusercontent.com/53527324/172057428-38264d5b-eb02-4bf5-a4ac-faa3aed3fa31.png)
Given that the files on the server with the error and on the server without the error are identical

**Comment by Truyn** [comment]
I'm still waiting for help.

**Comment by Truyn** [comment]
I don't see many details myself, the error is only there when starting the server.
The server version is up to date, sourcemod is also the latest version.

And then I don’t know where to dig, I’m not a sourcemod developer
