### ISSUE TITLE
sourcemode server crashes.

### ISSUE THREAD

**Issue by INewWorldI** [alliedmodders/sourcemod#1778]
- # Help us help you

  - [ ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Ubuntu 20.04.4 LTS 
  * Game/AppID (with version if applicable):  CSGO / 730
  * Current SourceMod version:   1.10.0.6540
  * Current SourceMod snapshot:  1.10.0.6540, jit-x86 (build 1.10.0.6540)
  * Current Metamod: Source snapshot: 1.11.0-dev+1145
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

Server suddenly crashes while playing
The error log does not appear, and I was able to receive the log through the accelerator.

https://crash.limetech.org/jj676tnalais << this log
https://crash.limetech.org/kya6zufw4ck5
https://crash.limetech.org/sutoktm5l2bq
https://crash.limetech.org/xoghqcubukjy

game.cstrike.ext.2.csgo.so!CS_DropWeapon [natives.cpp:74183 + 0x2e3]

Overall, I found this to be the problem. I've checked several times that the log contains this.

# Problematic Code (or Steps to Reproduce)

There is a phenomenon in which weapons are discarded multiple times when automatically purchasing weapons in the ZR plugin, and I wonder if that may be a problem. I don't know, but...
If it is a DropWeapon, it is expected that it may be the problem.

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

A list of plugins and extensions is also attached as text.

[Plugin list.txt](https://github.com/alliedmodders/sourcemod/files/8850023/Plugin.list.txt)
[Exts list.txt](https://github.com/alliedmodders/sourcemod/files/8850024/Exts.list.txt)

`

**Comment by Alexeyt89** [comment]
I had a similar problem on my server. On random occasions players found in own inventory two knives or other weapons which were not supposed to be there, or zombies cold find themselves without knives. I analized the problem and found out that weapon_healthshots sometimes are not cleaned from m_hMyWeapons after using. On some maps where players are attached to other entities (crazy carts), it happens to primary weapons as well. It is fine if the not cleaned index is reused for another weapon, it only leads to glitches, but if it is used for another entity type, the engine still tries to deal with it as with an ordinary weapon and the server crashes.
Not sure if the crash here happens for the same reason, but you cold try to check when a weapon is being deleted whether any player still has it in m_hMyWeapons.

**Comment by INewWorldI** [comment]
Oh thanks for the advice on that matter

I don't have much knowledge about coding.
If I understand a lot, does that mean that there is a problem with weapon_healthshots not being deleted and that deleting weapon_healthshots with a plugin can solve that problem? I wonder if the plug-in provided as an option in ZR is correct...

**Comment by psychonic** [comment]
Closing as this isn't a bug in SourceMod itself. There will always be the potential for adverse reactions with certain combinations of plugin interaction with the game.

**Comment by Alexeyt89** [comment]
What I meant is that in OnEntityDestroyed call for a weapon, the weapon index should not be present in m_hMyWeapons property of the player who possesed the weapon before it was marked for deletion. If the weapon index is still there, the property should be nulled. That's what I do to avoid glitches and crashes. If the index is not nulled, the property can eventially refer to any entity which is created with the same index after the weapon is deleted. Entity handlers are meant to protect from such problems, but in this case it somehow doesn't work.
Here is the problem discussion: https://forums.alliedmods.net/showthread.php?t=316315

**Comment by INewWorldI** [comment]
Ah I understand, thanks for your help, I'll apply and test...
