### ISSUE TITLE
Implement natives to get / set entity handle values in addresses

### ISSUE THREAD

**Issue by nosoop** [alliedmodders/sourcemod#1805]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).

# Description

SourceMod is missing a `GetDataEnt2` equivalent for entity handles not directly stored on entities.  This is desired for accessing them via indirection, such as on `CUtlVector<CHandle<T>>` instances (ex. the player's list of wearable entities in TF2).

**Comment by Wend4r** [comment]
You can use 
`GetEntData() | (1 << 31) /* Add SourceMod bit mark to reference */)` or 
`SetEntData(x & 0x7FFFFFFF /* Remove SourceMod bit mark from reference */)`
by `CHandle< CBaseEntity >` value. 
You need to apply bit mark if you uses `EntRefToEntIndex()`/`EntIndexToEntRef()` after that.

**Comment by nosoop** [comment]
In response to a deleted question, while [I do have a working implementation of this in stocksoup](https://github.com/nosoop/stocksoup/blob/fe569a887157aa316c04351425b325cfaef7d43b/memory.inc#L53-L76), it uses SourceMod-specific implementation details that I don't want to have to rely on.
