### ISSUE TITLE
[CSGO] ShowMenu messages created by Source.Python produces a "libprotobuf FATAL" error with SourceMod 1.11

### ISSUE THREAD

**Issue by jordanbriere** [alliedmodders/sourcemod#1806]
Steps to reproduce:

- Install latest stable or dev version of MM and SM
- Install latest release of [Source.Python](http://downloads.sourcepython.com/)
- Install [testing.zip](https://github.com/alliedmodders/sourcemod/files/9175158/testing.zip) and add `sp plugin load testing` to `autoexec.cfg`
- Launch the server, join it, and type `test` in chat which will produce the following error:
    > [libprotobuf FATAL ..\src\google\protobuf\reflection_ops.cc:58] CHECK failed: (to->GetDescriptor()) == (descriptor): Tried to merge messages of different types.

I don't rule out that this is something that will need to be addressed into `Source.Python`, but since this error does not happen using [sourcemod-1.10.0-git6545-windows.zip](https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6545-windows.zip) I suspect a change that was made into 1.11 directly or indirectly causes this issue to happens within your `SendUserMessage` hook.

Only `ShowMenu` messages are affected, other messages work as intended.

For references:

https://github.com/Source-Python-Dev-Team/Source.Python/issues/451
https://github.com/ThaPwned/WCS/issues/93

**Comment by kifchan** [comment]
same problem, cant use SM11 because of this T_T

**Comment by peace-maker** [comment]
@jordanbriere Do you have new details about the problem?

**Comment by psychonic** [comment]
I don't have time to dig further at the moment, but this seems likely to be related to https://github.com/alliedmodders/sourcemod/commit/e5ddbd9886da0cd310f00f7e87668d7043b19bc2
