### ISSUE TITLE
CS:GO A2S_Rules fix does not patch MTU high enough to accommodate all use cases

### ISSUE THREAD

**Issue by Vauff** [alliedmodders/sourcemod#1814]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Game/AppID (with version if applicable): CS:GO/730

# Description
https://github.com/alliedmodders/sourcemod/pull/614 brought the functionality of the [A2S_Rules hax plugin](https://forums.alliedmods.net/showthread.php?t=236521) directly into SM to fix CS:GO A2S_Rules responses. However while that plugin increased the MTU to 65k bytes, SM's implementation went with a [value of 5k instead](https://github.com/alliedmodders/sourcemod/blob/2f0ba0f34516157c7d5a873dbd16c9e5c4ed2a5d/extensions/cstrike/rulesfix.cpp#L83). This has proven to not be enough for some people that have plugins adding many `FCVAR_NOTIFY` flagged convars, and causes the A2S_Rules response to fail again after going past 5k bytes.

This should be be a fairly simple PR, but I was unsure of the reasoning for going with a lower value in the first place, and want to make sure there aren't any concerns with 65k or whatever other value may be preferred.

# Problematic Code (or Steps to Reproduce)
Enough convars created like this will eventually trigger the issue
```
ConVar cvar;

public void OnPluginStart()
{
	cvar = CreateConVar("sm_cvar_with_notify_flag", "0", "", FCVAR_NOTIFY);
}
```

# Logs
Some real world examples posted by several users in the SM Discord
```
[NET] Cannot send 6031-byte packet to ***:7130.  MTU is 1200.  ff ff ff ff 45
[NET] Cannot send 5171-byte packet to 195.201.249.154:47566.  MTU is 1200.  ff ff ff ff 45
[NET] Cannot send 5602-byte packet to [IP]. MTU is 1200. ff ff ff ff 45 
```

**Comment by crashzk** [comment]
Any fix for this error?
