### ISSUE TITLE
[CSGO] Case Opening(1.4.0b) UPDATED 20th feb. 2022 - Issue

### ISSUE THREAD

**Issue by Razvan02** [alliedmodders/sourcemod#1820]
# Help us help you
 I've downloaded everything I needed, but the final step so the plugin could work is: "Add "case_opening" configuration in sourceomod/configs/database.cfg".

**Comment by psychonic** [comment]
This section is for reporting bugs or requesting features for SourceMod itself.

For help with specific plugins, ask in that plugin's thread or on the AM Discord.
