### ISSUE TITLE
Error 100 on view_as on Functions

### ISSUE THREAD

**Issue by florinilie139** [alliedmodders/sourcemod#1823]
I have this
property Timer DayStartFunction
{
  public get()
  {
      return view_as<Timer>(this.GetFunction("DayStartFunction"));
  }
  public set(Timer value)
  {
      this.SetFunction("DayStartFunction", value);
  }
}
and on the view_as, I have an error, 100: function prototypes do not match
before, in spcomp 1.10 this worked without a problem.

Is this expected?

Thanks

**Comment by asherkin** [comment]
This is being discussed at alliedmodders/sourcepawn#671.
