### ISSUE TITLE
Dependency plugin reload without calling OnPluginEnd

### ISSUE THREAD

**Issue by BoneTM** [alliedmodders/sourcemod#1835]
Plugin A create a native, Plugin B use it
if Plugin A update when map changing by detecting the timestamp changed, Plugin B will recall OnPluginStart without calling OnPluginEnd
this is not a bug ?
mean the plugin with mem patch cant dependecy any plugin (when i validate patch in OnPluginStart)

**Comment by nosoop** [comment]
(Additional context: [Source Scramble](https://github.com/nosoop/SMExt-SourceScramble) provides a way to patch memory, and unpatching is performed when the handle is freed.)

**Comment by BoneTM** [comment]
more detail #1911
