### ISSUE TITLE
[CSS/L4D2/Any?] sm_map is causing a memory leak

### ISSUE THREAD

**Issue by lunatixxx** [alliedmodders/sourcemod#1838]
# Help us help you
  - [ ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Linux latest
  * Game/AppID (with version if applicable): Left 4 Dead 2/ CSS / More ?
  * Current SourceMod version: 1.10 and 1.11
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot: mmsource-1.11.0-git1143linux

happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Changing map with this command never free the memory taken by the previous, but to be honest i'm not entirely sure that this is not a normal problem of the source engine about changing maps. The memory free once you restart the server.

**Comment by KyleSanderson** [comment]
How are you changing level where it frees the memory?

**Comment by KyleSanderson** [comment]
> I'm not sure to understand your question. For example if i am changing to a new map 20 times in a row the memory will continuously become bigger even if the previous maps are not currently played. I think it happens too with the change map vote in l4d2.

ok so... if this happens with the ingame commands there's not much we can do in the core product. a plugin would be better suited to resolve this.
