### ISSUE TITLE
Compiler optimization

### ISSUE THREAD

**Issue by Smesh292** [alliedmodders/sourcemod#1848]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: https://www.sourcemod.net/compiler.php
  * Game/AppID (with version if applicable): https://www.sourcemod.net/compiler.php
  * Current SourceMod version: https://www.sourcemod.net/compiler.php
  * Current SourceMod snapshot: https://www.sourcemod.net/compiler.php
  * Current Metamod: Source snapshot: https://www.sourcemod.net/compiler.php
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

# Problematic Code (or Steps to Reproduce)
  ```
  // TODO(you): code here to reproduce the problem
public any test(int i)
{
return i == 0 ? 1.5 : -5;
}
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.
* warning 213: tag mismatch (expected "float", got "int")

**Comment by Bara** [comment]
You should post this in the repository of sourcepawn -> https://github.com/alliedmodders/sourcepawn/issues

**Comment by asherkin** [comment]
> You should post this in the repository of sourcepawn -> https://github.com/alliedmodders/sourcepawn/issues

No thank you, we'll transfer issues as required. If you have an issue with the version of SourcePawn included with SM, here is the preferred home for it.

**Comment by peace-maker** [comment]
Ternary expressions have to evaluate to the same type in both arms. So the initial report is a bug in your code. Floats don't work with the `any` type anyway, since the special float related operator overloads aren't used.

Your second example is a common programming error when using macros. The expression you're effecively building is `0 < ent1 <= MaxClients ? ent1 : ent2 <= MaxClients` which isn't what you want. The common pattern is to put parens around your macro expansion variables like `0 < (%1) <= MaxClients`.

**Comment by Smesh292** [comment]
Tha nk you. I got it. Nosūtīts no: Pasts darbam ar Windows No: peace-makerNosūtīts: piektdiena, 2022. gada 2. decembris 21:13Kam: alliedmodders/sourcemodKopija: Nick Jurevich; AuthorTēma: Re: [alliedmodders/sourcemod] Compiler optimization (Issue #1848) Ternary expressions have to evaluate to the same type in both arms. So the initial report is a bug in your code. Floats don't work with the any type anyway, since the special float related operator overloads aren't used.Your second example is a common programming error when using macros. The expression you're effecively building is 0 < ent1 <= MaxClients ? ent1 : ent2 <= MaxClients which isn't what you want. The common pattern is to put parens around your macro expansion variables like 0 < (%1) <= MaxClients.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
