### ISSUE TITLE
`GetNativeStringLength` should add 1 to account for null terminator

### ISSUE THREAD

**Issue by assyrianic** [alliedmodders/sourcemod#1861]
https://github.com/alliedmodders/sourcemod/blob/94ff26bdf1c758120abe4ea95183ea4764acc3e8/core/logic/smn_fakenatives.cpp#L173

Either this or it really should be stated in documentation to add +1 to the length after using this API.

```c
 *addr = (cell_t)strlen(str) + 1;
```

**Comment by rumblefrog** [comment]
Bleh, this ain't buffer size.

**Comment by asherkin** [comment]
`GetNativeStringLength` is `strlen` rather than `sizeof` - while many plugins only care about reading the value and thus will use `+ 1`, it isn't exclusively the use of it especially when copying back different values.
