### ISSUE TITLE
[BUG] false syntax error on prepared insert statement

### ISSUE THREAD

**Issue by birgersp** [alliedmodders/sourcemod#1863]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Ubuntu 22.04
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 1.12
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Running a prepared statement on a postgres database yields a (seemingly, to me) false error:

```
SQL_PrepareQuery error: ERROR:  syntax error at or near ")"
LINE 1: insert into t_kill(c_foobar) values (?);
                                              ^
```
I mean how is this a syntax error?

# Problematic Code (or Steps to Reproduce)
  ```
	char error[512];
	DBStatement result = SQL_PrepareQuery(db, "insert into t_kill(c_foobar) values (?);", error, sizeof(error));
	if (result == null)
	{
		PrintToServer("SQL_PrepareQuery error: %s", error);
	}
  ```

The driver is "pgsql". Doing a SQL_FastQuery works as advertised.

**Comment by psychonic** [comment]
Remove the `;`

**Comment by birgersp** [comment]
Thanks for trying to help but removing the semicolon does not make the error go away.

```
		char error[512];
		DBStatement result = SQL_PrepareQuery(db, "insert into t_kill(c_foobar) values (?)", error, sizeof(error));
		if (result == null)
		{
			PrintToServer("SQL_PrepareQuery error: %s", error);
		}
```

```
SQL_PrepareQuery error: ERROR:  syntax error at or near ")"
LINE 1: insert into t_kill(c_foobar) values (?)
                                              ^
```

**Comment by asherkin** [comment]
I'm not super familiar with PgSQL, but the docs for `PREPARE` indicate that it uses `$1` etc for value placeholders rather than `?`, give that a try. 

We typically discourage server-side prepared queries in modern SM plugins - SM's client-side escaping is more flexible and reliable. 

> And, should it? Semicolons are perfectly reasonable to use in queries

SourceMod's DBI layer is explicitly single statement per query, it simplifies things over the different drivers and MySQL in particular is problematic with multiple result sets.

**Comment by asherkin** [comment]
Verified against the upstream docs for `PQprepare`:

> If any parameters are used, they are referred to in the query as $1, $2, etc.

**Comment by birgersp** [comment]
> I'm not super familiar with PgSQL, but the docs for `PREPARE` indicate that it uses `$1` etc for value placeholders rather than `?`, give that a try.

I did try it initially, but I crashed so I figured `?` must be the only correct way to do it, since it is the only way I could find documented. The crash is perhaps a different issue.

> Verified against the upstream docs for `PQprepare`:
> 
> > If any parameters are used, they are referred to in the query as $1, $2, etc.

Thank you for the info. Can you please provide a link to these docs?

**Comment by asherkin** [comment]
> Thank you for the info. Can you please provide a link to these docs?

https://www.postgresql.org/docs/current/libpq-exec.html#id-1.7.3.10.3.7.1.1.1.2

Do you have an Accelerator crash report for the crash?

**Comment by birgersp** [comment]
Thank you. I'll do some more trial-and-error on my end about the crash, it might just be something wrong on my end. I'll get back to if I think there's actually a bug 🤓

**Comment by asherkin** [comment]
If you crashed in SM, it's a bug, no matter what you did "wrong" 🙂
