### ISSUE TITLE
adminhelp.sp exception

### ISSUE THREAD

**Issue by NotPowered** [alliedmodders/sourcemod#1878]
Hello, With this update, https://github.com/alliedmodders/sourcemod/commit/ed662dc8cf4d07201c8a842368ae7cd

i got sometimes plugin adminhelp.sp to crash

L 12/09/2022 - 15:20:15: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 12/09/2022 - 15:20:15: [SM] Blaming: adminhelp.smx
L 12/09/2022 - 15:20:15: [SM] Call stack trace:
L 12/09/2022 - 15:20:15: [SM] [0] ConVar.Flags.get
L 12/09/2022 - 15:20:15: [SM] [1] Line 145, adminhelp.sp::HelpCmd
L 12/09/2022 - 15:20:25: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 12/09/2022 - 15:20:25: [SM] Blaming: adminhelp.smx
L 12/09/2022 - 15:20:25: [SM] Call stack trace:
L 12/09/2022 - 15:20:25: [SM] [0] ConVar.Flags.get
L 12/09/2022 - 15:20:25: [SM] [1] Line 145, adminhelp.sp::HelpCmd
L 12/09/2022 - 15:34:24: Error log file session closed.

**Comment by osyu** [comment]
Check if you're running an outdated version - 6c5a3fd fixed this with the addition of CommandIterator.ConVarFlags

**Comment by NotPowered** [comment]
I was on 1.12 - 6946. I have updated now to 1.12 - 6949.

I will check if error occured again and make a reply to this thread quickly

**Comment by peace-maker** [comment]
I'm assuming this was fixed with the introduction of the `.ConVarFlags` property. Please reopen if you encounter this again.
