### ISSUE TITLE
RadioMenuMaxPageItems on Black Mesa

### ISSUE THREAD

**Issue by atiksoftware** [alliedmodders/sourcemod#1882]
There is one thing I am wondering about. I'm not very familiar with the Source game engine and sourcemod. Frankly, I am writing here because I can't find the answer to my question.

Why is **RadioMenuMaxPageItems** limited to 6 in the **Black Mesa** game?
And can I update it dynamically by plugin?

When I change it manually from the common.games.txt file, the game changes it back to 6.

Was there an important reason for limiting it to 6?
because otherwise, 3 items appear on each page and make it very difficult to use.

**Comment by rumblefrog** [comment]
Inferring the commit message: https://github.com/alliedmodders/sourcemod/commit/fbe377a53d3b094fa264683ace6e783e2c4ec893

It seems like 7+ keys are not bound.

**Comment by atiksoftware** [comment]
In fact, when I changed it manually and ran the game, I saw that it worked without any problems.

**Comment by rumblefrog** [comment]
Perhaps an update changed it? If you can confirm that everything works with a higher maximum, you can probably PR to update it.

**Comment by atiksoftware** [comment]
actually this happened when the game crashed and closed and i restarted the game.
I'm wondering; Can I update this data with the plugin? Are they values that can be changed dynamically? Or can't it be changed?

**Comment by psychonic** [comment]
Black Mesa still does not bind beyond slot6 by default. We need to keep the max at a level that works for players out of the box.
