### ISSUE TITLE
Pre increment

### ISSUE THREAD

**Issue by Smesh292** [alliedmodders/sourcemod#1884]
# Help us help you
  - [ ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: 
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

# Problematic Code (or Steps to Reproduce)
  ```
  // TODO(you): code here to reproduce the problem
  ```
for(int i = 0; i <= MaxClients; ++i)

doesnt work
# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by asherkin** [comment]
I'm unable to reproduce, tested here and it works fine. If you're still having an issue please completely fill out the issue template with runnable code and re-open.

**Comment by Smesh292** [comment]
must be 1

**Comment by Smesh292** [comment]
![image](https://user-images.githubusercontent.com/44304306/208118637-53ac32f6-b507-41d3-aafb-8a6afe21d1f5.png)

**Comment by asherkin** [comment]
I'm afraid your code is incorrect and it is unrelated to pre-vs-post-increment.

I'd advise you post on the AM forum or join the Discord if you need scripting help.
