### ISSUE TITLE
The latest sourcemod build cannot be loaded by metamod

### ISSUE THREAD

**Issue by eldoradoel** [alliedmodders/sourcemod#1898]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 11.3
  * Game/AppID (with version if applicable): 730
  * Current SourceMod version: 1.12
  * Current SourceMod snapshot: 6966
  * Current Metamod: Source snapshot: 1.12.0-dev+1165
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
The latest sourcemod build cannot be loaded by metamod

# Problematic Code (or Steps to Reproduce)
  ```
meta load addons/sourcemod/bin/sourcemod_mm
Failed to load plugin addons/sourcemod/bin/sourcemod_mm (/root/csgo/csgo/csgo/addons/sourcemod/bin/sourcemod.2.csgo.so: undefined symbol: g_pCVar).
  ```

**Comment by psychonic** [comment]
Sorry about that. It will be fixed in the next build, which should trigger momentarily.
