### ISSUE TITLE
GameData.GetAddress silently fails on missing key

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#1918]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 10 x64
  * Game/AppID (with version if applicable): 550/Any?
  * Current SourceMod version:  1.12.0.6975
  * Current SourceMod snapshot:  1.12.0.6975
  * Current Metamod: Source snapshot: 1.11.0-dev+1148
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
When GameData config missing the address key requested, GetAddress returns 0 without reporting the error in log file.

# Problematic Code (or Steps to Reproduce)
  ```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>
#include <sdktools>

#define GAMEDATA		"Address_Detour"

public void OnPluginStart()
{
	char sPath[PLATFORM_MAX_PATH];
	BuildPath(Path_SM, sPath, sizeof(sPath), "gamedata/%s.txt", GAMEDATA);

	GameData hGameData = LoadGameConfigFile(GAMEDATA);
	if( hGameData == null ) SetFailState("Failed to load \"%s.txt\" gamedata.", GAMEDATA);
	
	Address g_Addr_Func = hGameData.GetAddress("SurvivorBot::IsReachable");
	PrintToServer("Address: %i", view_as<int>(g_Addr_Func));
	delete hGameData;
}
```
GameData:
```
"Games"
{
	"left4dead2"
	{
		"Addresses"
		{
			"WrongName"
			{
				"linux"
				{
					"signature" "SurvivorBot::IsReachable"
				}
			}
		}
		"Signatures"
		{
			"SurvivorBot::IsReachable"
			{
				"library"		"server"
				"linux"			"@_ZNK11SurvivorBot11IsReachableEP11CBaseEntity"
			}
		}
	}
}
```

# Logs
Current behaviour: Error log is empty
Expected behaviour: Error log should contain information about missing address key of config.

**Comment by nosoop** [comment]
This appears to be intended.  The documentation doesn't indicate that it raises any errors at all; it does point out that a return value of zero indicates a failure.

The behavior matches that of `GameData.GetOffset` and `GameData.GetMemSig`.
