### ISSUE TITLE
Implementing menu support in a game (Alien Swarm: Reactive Drop)

### ISSUE THREAD

**Issue by BenLubar** [alliedmodders/sourcemod#1938]
(appid 563560, `beta` branch; see also https://github.com/ReactiveDrop/reactivedrop_public_src/issues/510)

I would like to get SourceMod menus working in my game. In the current beta branch (as of a few minutes ago) they... partially work.

The only changes in the beta branch related to this are the additions of a few `resource/ui/plugin*.res` files copied from L4D2 and some sounds and sprites that it looks like SourceMod uses copied from HL2.

I can type `!admin` in chat on a local dedicated server and (after pushing the ESC key) navigate the menu it spawns. However, once I do this, I am unable to click on anything in the game unless a game menu (such as the ESC menu, the chat box, or (annoyingly) vgui_drawtree) is open.

I'd prefer if seeing a menu from SourceMod wasn't something that would lock you out of playing the game, obviously. Is this something someone has implemented in a mod using one of the newer Source Engine branches before? If it would be easier, we could implement a whole new menu handler in AS:RD (which would also give the benefits of being able to access it from vscript, having it visible without hitting ESC, making its style fit the game better, etc.)

**Comment by psychonic** [comment]
The preferred method for menu support is making the client `CHudMenu` menus functional, including ideally having slot0 through slot9 all bound by default. I'm less familiar with the Swarm SDK, but in the 2013 SDK, this works out of the box other than a missing section or two in the hudlayout.res script. I believe that the class at least exists in the Swarm SDK, but I don't know how well it's hooked up to the HUD, and how the Reactive Drop modification may affect it.

If you want to go that route, I can look up what those generally missing bits from hudlayout are in case that's helpful, or answer most other questions.

These are generally much more user-friendly than the older style of menu (which I haven't ever seen able to display in L4D and beyond, so nice job finding some of the missing bits for that). Also, note that for historical reasons, games/mods have to be opted into the hud/radio menus on the SourceMod side. (see https://github.com/alliedmodders/sourcemod/blob/a0eb6a95505530cf5b1c04a2407aa52ccdfbf8a0/gamedata/core.games/common.games.txt#L157-L201)

**Comment by BenLubar** [comment]
We do have CHudMenu in our code, but it looks like it's hooked up to the HL2 weapon switching code, which no game since the Orange Box has used to my knowledge.

We have F1 through F8 bound to `+selectmarine1`, etc. but that only gives us 1-8, F9 and F10 are bound to `playerlist` and `jpeg` by default, and it'd be weird to have that be tied to commands. Do you know off the top of your head if there's a way to intercept button presses before they get converted to bound commands?

We could use that to hook up F1-F10 directly to the menu when it's open. (1-8 are bound to various kinds of panic buttons based on your squad's loadout, so I don't think we should go down a row.)

**Comment by psychonic** [comment]
The CHudMenu-based menu code may need some massaging on that front, but it can definitely be made to work, even sharing key-bindings with other functionality. The reason it hooks into weapon selection by default, is so that when those keys are pressed, the menu can intercept if it's currently open. As long as they are sequential keys that wouldn't often be rebound and are handled by a single system, a similar approach should be able to be used. Even if only 8 in a row are bound, we have a system in place to limit the maximum amount of entries shown at once. It's most commonly used for a handful of games that don't bind past slot7 by default.

**Comment by BenLubar** [comment]
I've found a way to intercept F1-F10 directly, and I'm planning on pushing the code changes to the beta branch once I'm happy with the way the graphics look. All that needs to be changed on sourcemod's end is adding reactivedrop to that game list config.

**Comment by psychonic** [comment]
> I've found a way to intercept F1-F10 directly, and I'm planning on pushing the code changes to the beta branch once I'm happy with the way the graphics look. All that needs to be changed on sourcemod's end is adding reactivedrop to that game list config.

Sounds great. That's easy enough to flip when it's ready in the game.

**Comment by BenLubar** [comment]
If you mean non-beta branch, that'll be April 20th.

**Comment by psychonic** [comment]
If I'm correct in assuming that the current, non-beta state is no real menu functionality at all, I don't see any harm in us flipping on the ShowMenu support for Reactive Drop sooner / anytime.

**Comment by BenLubar** [comment]
That is correct. The beta branch supports both (although the non-CHudMenu version still causes mouse input to break) and the non-beta branch supports neither.

**Comment by psychonic** [comment]
I've enabled that now. If you need anything else from our side for it, feel free to let us know. Thanks!
