### ISSUE TITLE
[PostgreSQL] not support prepare query?

### ISSUE THREAD

**Issue by ProjectSky** [alliedmodders/sourcemod#1945]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: 
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

# Problematic Code (or Steps to Reproduce)
``` cpp
char query[512], sError[256];
DBStatement hInsertQuery;
FormatEx(query, sizeof(query), "INSERT INTO test (steamid, name, ip, firstjoin) VALUES (?, ?, ?, ?)");
hInsertQuery = SQL_PrepareQuery(g_hDataBase, query, sError, sizeof(sError))
if (hInsertQuery == null)
{
	delete hInsertQuery;
	LogError("failed %s", sError);
	return;
}
...
```

* error
```
failed ERROR:  syntax error at or near ","
LINE 1: ...test (steamid, name, ip, firstjoin) VALUES (?, ?, ?, ?)...
```

this statement work fine on mysql, pg not supported prepare query?

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by asherkin** [comment]
Postgres has a different syntax from MySQL for prepared queries. 

https://github.com/alliedmodders/sourcemod/issues/1863#issuecomment-1327501889

**Comment by ProjectSky** [comment]
sorry i didn't notice it
