### ISSUE TITLE
Semicolon after enum struct causes compilation error

### ISSUE THREAD

**Issue by dronelektron** [alliedmodders/sourcemod#1949]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 10
  * Game/AppID (with version if applicable): 300
  * Current SourceMod version: 1.11.0.6932
  * Current SourceMod snapshot: 1.12.0.6983
  * Current Metamod: Source snapshot: 1.12.0-dev+1167
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Semicolon after enum struct causes compilation error

# Problematic Code (or Steps to Reproduce)
  ```
 #include <sourcemod>

enum struct Something {
    int age;
    int weight;
}; // This semicolon cause an error

public Plugin myinfo = {
    name = "",
    author = "",
    description = "",
    version = "",
    url = ""
};
  ```

# Logs
drone@ANDY-PC MINGW64 ~/Desktop
$ spcomp enum-struct-semicolon.sp
SourcePawn Compiler 1.11.0.6932
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

enum-struct-semicolon.sp(6) : error 155: expected newline, but found ';'

1 Error.

**Comment by Wend4r** [comment]
https://github.com/alliedmodders/sourcepawn/pull/532

**Comment by dronelektron** [comment]
Oops, didn't see this thread.

**Comment by Wend4r** [comment]
You can try (Git Bash or Linux like)

https://github.com/Wend4r/sourcepawn-public/commit/6edba21e853d24cc28d2768ad258861179e51d35
```bash
cd sourcepawn # Enter to sourcepawn from ./alliedmodders/sourcemod 

git remote add wend4r https://github.com/Wend4r/sourcepawn-public.git
git fetch wend4r enum_struct-semicolon # Bash scripts: pack the branch name into a variable

git checkout -b enum_struct-semicolon
git pull wend4r enum_struct-semicolon #FUTURE: possible merge. # Updating 9cf9f31..6edba21: compiler/parser.cpp | 2 +-; 1 file changed, 1 insertion(+), 1 deletion(-)

cd ..
# Rebuild SourceMod with SourcePawn for your OS to using the spcomp
```

**Comment by dronelektron** [comment]
Thanks for the answer, but I don't really need it. I can wait until the developers add this feature in the next releases :)
