### ISSUE TITLE
question about source2

### ISSUE THREAD

**Issue by fdHYF** [alliedmodders/sourcemod#1952]
Would sourcemod still work if value release source2 engine?Or what can we do about it.

**Comment by rumblefrog** [comment]
Numerous discussions have been about this, and it does not belong on the issue tracker either. 

https://wiki.alliedmods.net/Introduction_to_SourceMod_Plugins#Will_SourceMod_support_Source_2.3F_Will_plugins_for_existing_games_continue_to_work_if_they_are_ported.3F

https://www.google.com/search?q=source+2+site%3Aforums.alliedmods.net
