### ISSUE TITLE
Nested menus: MenuAction_Cancel not called for parent menu

### ISSUE THREAD

**Issue by dysphie** [alliedmodders/sourcemod#1955]
# Environment
  * Operating System version: Windows 10
  * Game/AppID (with version if applicable): CSGO & No More Room in Hell
  * Current SourceMod version: 1.11.0.6927 and 1.12.0.6983
  * Current Metamod: Source snapshot:  1.12.0-dev+1163
  
# Description

When displaying a menu from another menu, the parent menu won't have its MenuAction_Cancel action called

# Problematic Code (or Steps to Reproduce)
  ```cpp
#include <sourcemod>

public void OnPluginStart()
{
	RegConsoleCmd("sm_menu1", Cmd_Menu1);
}

Action Cmd_Menu1(int client, int args)
{
	Menu menu = new Menu(MenuHandler1);
	menu.AddItem("", "menu1");
	menu.Display(client, MENU_TIME_FOREVER);
	return Plugin_Handled;
}

void SendMenu2(int client)
{
	Menu menu = new Menu(MenuHandler2);
	menu.AddItem("menu2", "menu2");
	menu.Display(client, MENU_TIME_FOREVER);
}

int MenuHandler1(Menu menu, MenuAction action, int param1, int param2)
{
	switch (action)
	{
		case MenuAction_End:
		{
			PrintToServer("MenuAction_End: %d %d", param1, param2);
			delete menu;
		}
		case MenuAction_Cancel:
		{
			PrintToServer("MenuAction_Cancel: %d %d", param1, param2);
		}
		case MenuAction_Select:
		{
			SendMenu2(param1);
		}
	}

	return 0;
}

int MenuHandler2(Menu menu, MenuAction action, int param1, int param2)
{
	return 0;
}
```

Output when selecting "menu1":
> Dysphie‎ : !menu1
> MenuAction_End: 0 0

**Comment by KyleSanderson** [comment]
This is correct behaviour per the documentation. The user did not "Exit" or "Cancel" the menu, so the action is not called. Feel free to ask for help on Discord or the forums.

**Comment by asherkin** [comment]
> This is correct behaviour per the documentation. The user did not "Exit" or "Cancel" the menu, so the action is not called. Feel free to ask for help on Discord or the forums.

"Interrupted by another menu" is one of the cancel reasons.
