### ISSUE TITLE
[Feature request] Expose GetUnifiedSteamIdentity in natives

### ISSUE THREAD

**Issue by sapphonie** [alliedmodders/sourcemod#1971]
I trust [SourceMod's implementation](https://cs.alliedmods.net/sourcemod/source/core/logic/AdminCache.cpp#1081) of this much more than [poorly documented forum posts](https://forums.alliedmods.net/showthread.php?t=324112) from years ago, and it seems much cleaner to use to boot...

**Comment by peace-maker** [comment]
From #1521 this was discussed previously and the conclusion was to use the account id instead of a string representation.
What do you need this representation for?

**Comment by sapphonie** [comment]
> From #1521 this was discussed previously and the conclusion was to use the account id instead of a string representation.
> What do you need this representation for?

I don't remember my specific use case but I think it was something having to do with passing a steamid from one native, in one format, to my code, and then passing that in another format, to another native, and it was a huge gigantic pain.

**Comment by KyleSanderson** [comment]
You're much better off passing the number than a formatted string

**Comment by sapphonie** [comment]
> You're much better off passing the number than a formatted string

How? It's 64 bit. Passing an int array would be kind of ugly too

**Comment by peace-maker** [comment]
https://sourcemod.dev/#/clients/function.GetSteamAccountID

**Comment by peace-maker** [comment]
Simliar to https://github.com/alliedmodders/sourcemod/pull/1521 this seems encouraging bad patterns, so I'm closing this.
