### ISSUE TITLE
[Feature request] Socket & WebSocket

### ISSUE THREAD

**Issue by Player-sudo** [alliedmodders/sourcemod#1983]
Socket & WebSocket shipped with sourcemod.

**Comment by asherkin** [comment]
I'm afraid this wouldn't happen without a well-established and decent community extension first. If there was demand for it, there would be a popular extension. 

This would be a SDK-less extension so there is a fairly low maintenance burden. Almost all the hard work here would be in defining a decent API (see also: all the different HTTP extensions), which is much more difficult when targeting SM's ultra stable API surface.
