### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by FZDNSZYT** [alliedmodders/sourcemod#1984]
sourcemod-1.10.0-git6528-linux is normal
![2023-04-15 (5)](https://user-images.githubusercontent.com/86947716/232114258-835518de-86c8-4bee-a86b-f2baafeb69bb.png)
sourcemod-1.11.0-git6926-linux and latest build version sourcemod-1.11.0-git6934-linux fails to compile
![2023-04-15](https://user-images.githubusercontent.com/86947716/232114651-3cd10fb3-d23e-495f-b380-01dc99f46690.png)
Error message:
Compiling adminhelp.sp ...
./spcomp: /lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./spcomp)
./spcomp: /lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./spcomp)
./spcomp: /lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./spcomp)

**Comment by asherkin** [comment]
Your operating system is too old to use the prebuilt binaries, you'll need to upgrade your OS or build SourceMod from source.

AM does not use GitHub issues as a support platform, please post on the forum or join the AM Discord if you have further questions.
