### ISSUE TITLE
Server crashes with a maxplayer count over 65 in TF2

### ISSUE THREAD

**Issue by dom64** [alliedmodders/sourcemod#2027]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 12
  * Game/AppID (with version if applicable): Team Fortress 2 Dedicated Server (232250)
  * Current SourceMod version: 6936
  * Current SourceMod snapshot: 7036
  * Current Metamod: Source snapshot: 1167
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

- Sourcemod seems to crash every attempt with making a server where the maxplayer count is set over 65.
- Disabling all the plugins still results in this issue.
- Attempting to compile [this](https://github.com/alliedmodders/sourcemod/pull/2026) pulll request still results in this issue.
- Running it only with SourceMM does not result in any crashes related to this issue.

# Problematic Code (or Steps to Reproduce)
- Run a TF2 server with the dev build of SourceMod and SourceMM.
- Add the console parameter `-unrestricted_maxplayer` to the server.
- Set the maxplayer count to anything above 65 (example being +maxplayers 100).
- Crashes with a segmentation fault.

# Logs
- [debug.log](https://github.com/alliedmodders/sourcemod/files/12173899/debug.log)
- [log.txt](https://github.com/alliedmodders/sourcemod/files/12173900/log.txt)
- [crash_20230726144319_12.dmp](https://github.com/alliedmodders/sourcemod/files/12173922/crash_20230726144319_12.zip)

**Comment by sapphonie** [comment]
This is a crash with Accelerator, not with SourceMod

**Comment by dom64** [comment]
@sapphonie I've double checked and I realized that I didn't clone your pull request properly (I forgot to specify the correct branch). After running it again it seems to be correct and working with 100 players. Sorry about my error

**Comment by psychonic** [comment]
Fixed by #2026
