### ISSUE TITLE
basebans.smx dosent work in latest snapshot

### ISSUE THREAD

**Issue by kmak7** [alliedmodders/sourcemod#2028]
# Environment
  * Operating System version: Debian 11
  * Game/AppID (with version if applicable):  tf2
  * Current SourceMod version:  1.12
  * Current SourceMod snapshot: Build 7037
  * Current Metamod: Source snapshot: 1.12 Build 1167
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [X] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [X] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Sourcemod says banreasons.txt is not found despite it being in configs folder

L 07/26/2023 - 23:02:17: [SM] Exception reported: Error in addons/sourcemod/configs/banreasons.txt: File not found, corrupt or in the wrong format
L 07/26/2023 - 23:02:17: [SM] Blaming: basebans.smx
L 07/26/2023 - 23:02:17: [SM] Call stack trace:
L 07/26/2023 - 23:02:17: [SM]   [0] SetFailState
L 07/26/2023 - 23:02:17: [SM]   [1] Line 128, /home/builds/sourcemod/debian9-1.12/build/plugins/basebans.sp::LoadBanReasons
L 07/26/2023 - 23:02:17: [SM]   [2] Line 71, /home/builds/sourcemod/debian9-1.12/build/plugins/basebans.sp::OnPluginStart
L 07/26/2023 - 23:02:17: [SM] Unable to load plugin "basebans.smx": Error detected in plugin startup (see error logs)

**Comment by psychonic** [comment]
This is also being tracked on https://github.com/alliedmodders/sourcepawn/issues/890 with more detailed info

**Comment by psychonic** [comment]
Fixed in #2032
