### ISSUE TITLE
Call forward for a specific plugin

### ISSUE THREAD

**Issue by deathscore13** [alliedmodders/sourcemod#2029]
I would like to be able to call forward (public function) for a specific plugin as it is currently called for all, that doesn't suit me very well

**Comment by Deathreus** [comment]
This is what private forwards are for

**Comment by deathscore13** [comment]
> This is what private forwards are for

You are right, this really already exists.  It's just that I used to think that you need to specify the function name (string) there, and not the function index in the .public table (int).  I'm sorry to trouble
