### ISSUE TITLE
Bad replay cvar name in sdktools

### ISSUE THREAD

**Issue by hydrogen-mvm** [alliedmodders/sourcemod#2031]
# Help us help you
  - [ ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Debian 11
  * Game/AppID (with version if applicable): 440 (TF2)
  * Current SourceMod version: 1.11.0.6924
  * Current SourceMod snapshot:  6924
  * Current Metamod: Source snapshot: 1.11.0-dev+1148
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

From this commit: https://github.com/alliedmodders/sourcemod/commit/f9309c83d28d955a478fd804374ebfade2b34453
The replay convar was written incorrectly, it should be **replay_enable** (without the "d").

The server is still crashing as reported in this PR https://github.com/alliedmodders/sourcemod/issues/1581 . I've been trying to get rid of the FileExists hook and it looks like the botched replay cvar name is preventing the workaround from executing.

I don't have the ability to recompile Sourcemod right now, or else I would test the fix myself. If I do manage to get around it, I will submit a PR.

Thanks.

**Comment by hydrogen-mvm** [comment]
Upon further probing, it seems like even fixing that spelling error doesn't correct the issue. The value of replay_enabled.GetBool() always returns false even if replay_enabled is set to 1. However, locally creating a ConVarRef object in CHookManager::NetChannelHook correctly returns the cvar value (see picture below).

![image](https://github.com/alliedmodders/sourcemod/assets/29522123/53a9a24e-fc51-4706-9573-306e8b79105f)

I don't know what's the best way to "fix" the issue but perhaps someone more knowledgeable than me can propose an appropriate remedy. In the meantime, as a workaround, I'll just replace that replay_enabled.GetBool() with true.

**Comment by hydrogen-mvm** [comment]
This fixed the issue for me. I'm not going to open a PR since this feels like a dirty hack, but this makes the sdktools.ext.tf2 binary correctly apply the replay workaround. The OnFileSend warning is now printed when replay_enable is set to 1.

![image](https://github.com/alliedmodders/sourcemod/assets/29522123/025e109b-1396-414f-88de-c6e8833b970b)

**Comment by psychonic** [comment]
Thanks for doing the investigation and making the report. All of that makes sense to an extent. Like you, I also wouldn't have thought that the constructor there was too early to look up the var, but can't argue with results.

I think what you have there is an acceptable fix if you'd like to PR, else I can just make the change directly. Looking up the ConVar at hook type is fine as it's not a hot path.
