### ISSUE TITLE
CS2 update

### ISSUE THREAD

**Issue by archy901** [alliedmodders/sourcemod#2054]
Hi! Yesterday Valve released new version of the game, CS2. Could you kindly tell, if you have any plans of updating current software or, maybe at least, check possability of using it for CS2? Any help very appreciated 🙏

**Comment by archy901** [comment]
> Plans to get something working, yes. Plans to make existing plugins work, highly unlikely.
> 
> https://wiki.alliedmods.net/Introduction_to_SourceMod_Plugins#Will_SourceMod_support_Source_2.3F_Will_plugins_for_existing_games_continue_to_work_if_they_are_ported.3F

Yes, thank you for sharing introduction docs, it made me better understand a core of the problem. Do you mind me asking, do you have any understanding of when it could be released at least in some kind of primary version?

**Comment by psychonic** [comment]
There are no plans to port SourceMod as-is to Source 2. Some members of the community have started work on a successor, but it is far too early to estimate a date of availability.
