### ISSUE TITLE
OnTakeDamage not supported on Dystopia. Please add support in takedamageinfohack.cpp or instruct how to do it

### ISSUE THREAD

**Issue by danomation** [alliedmodders/sourcemod#2070]
Help us support OnTakeDamage sdkhook in Dystopia. This will greatly assist us in making sourcemod plugins

**Comment by sapphonie** [comment]
This issue needs more info - what isn't working? Are there any error messages or warning messages in console? Do you just need gamedata?

**Comment by danomation** [comment]
None of the SDK hooks work in Dystopia. We get an error like this example:

- [ ] L 10/26/2023 - 02:22:30: [SM] Exception reported: Hook type not supported on this game
- [ ] L 10/26/2023 - 02:22:30: [SM] Blaming: arnerf.smx
- [ ] L 10/26/2023 - 02:22:30: [SM] Call stack trace:
- [ ] L 10/26/2023 - 02:22:30: [SM]   [0] SDKHook
- [ ] L 10/26/2023 - 02:22:30: [SM]   [1] Line 17, arnerf.sp::OnClientPutInServer
- [ ] L 10/26/2023 - 02:22:30: [SM]   [3] ServerCommandEx
- [ ] L 10/26/2023 - 02:22:30: [SM]   [4] Line 402, /home/builds/sourcemod/debian9-1.11/build/plugins/basecommands.sp::Command_Rcon
- [ ] L 10/26/2023 - 02:22:30: "Bot01<4><BOT><Unassigned>" joined team "Spectator"
- [ ] L 10/26/2023 - 02:22:30: "Bot01<4><BOT><>" entered the game
- [ ] L 10/26/2023 - 02:22:30: "Bot01<4><BOT><Spectator>" joined team "Punks"

**Comment by bauxiteDYS** [comment]
Does that mean we just need GameData, unsure?

**Comment by danomation** [comment]
> Does that mean we just need GameData, unsure?

nah they're just wanting some information to go on

**Comment by danomation** [comment]
I guess we do  need gamedata. The rest is just simple changes right?
