### ISSUE TITLE
EntityLump not working with stripper

### ISSUE THREAD

**Issue by mariokeks** [alliedmodders/sourcemod#2072]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System: Linux
  * Game/AppID (with version if applicable): Counter Strike: Source  / AppID 232330
  * Current SourceMod version: 1.12.0.7071
  * Current Metamod: Source snapshot: 2.0.0-dev+1255
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Currently EntityLump doesn't show any changes when modifying entities via stripper.
In the previous version of SM any modification with stripper was also visible in OnLevelInit inside the mapEntities, but OnLevelInit is deprecated now and mapEntities returns nothing.

# Problematic Code (or Steps to Reproduce)
Stripper example
  ```
add:
{
	"origin" "1504 3168 160"
	"targetname" "servercommandspawn"
	"classname" "point_servercommand"
}
  ```
Source for a test command
  ```
#include <entitylump>

#pragma newdecls required
#pragma semicolon 1

public void OnPluginStart()
{
	RegAdminCmd("sm_dump_mapentities", Command_Dump, ADMFLAG_ROOT, "Dumps all entities into error logs.");
}

public Action Command_Dump(int client, int args)
{
	int iEntities = EntityLump.Length();
	for (int i = 0; i < iEntities; i++)
	{
		EntityLumpEntry lumpEntry = EntityLump.Get(i);
		LogError("-----");

		int iKeyvalues = lumpEntry.Length;
		for (int j = 0; j < iKeyvalues; j++)
		{
			char sKey[64], sValue[128];
			lumpEntry.Get(j, sKey, sizeof(sKey), sValue, sizeof(sValue));
			LogError("%s - %s", sKey, sValue);
		}
		LogError("-----");
		delete lumpEntry;
	}
	return Plugin_Handled;
}

  ```

**Comment by Vauff** [comment]
Try this [updated Stripper](https://github.com/tilgep/stripper), it utilizes SM's entity lump API unlike the original.

**Comment by mariokeks** [comment]
Thanks, seems to work!
