### ISSUE TITLE
error windows

### ISSUE THREAD

**Issue by eduaris123** [alliedmodders/sourcemod#2156]
I just installed the latest version of Windows (metamod and sourcemod). I was surprised that it doesn't read the gamedata folder.

Missing required file: "addons\sourcemod\gamedata\l4d_console_spam.txt".
Read installation instructions again.
L 05/14/2024 - 22:57:34: [SM] Blaming: l4d_console_spam.smx
L 05/14/2024 - 22:57:34: [SM] Call stack trace:
L 05/14/2024 - 22:57:34: [SM] [0] SetFailState
L 05/14/2024 - 22:57:34: [SM] [1] Line 94, l4d_console_spam.sp::OnPluginStart
L 05/14/2024 - 22:57:34: [SM] Unable to load plugin "l4d_console_spam.smx": Error detected in plugin startup (see error logs)
L 05/14/2024 - 22:57:34: [SM] Exception reported:
Missing required file: "addons\sourcemod\gamedata\l4d_reload_fix.txt".
Read installation instructions again.
L 05/14/2024 - 22:57:34: [SM] Blaming: l4d_reload_fix-ph.smx
L 05/14/2024 - 22:57:34: [SM] Call stack trace:
L 05/14/2024 - 22:57:34: [SM] [0] SetFailState
L 05/14/2024 - 22:57:34: [SM] [1] Line 152, l4d_reload_fix-ph.sp::OnPluginStart
L 05/14/2024 - 22:57:34: [SM] Unable to load plugin "l4d_reload_fix-ph.smx": Error detected in plugin startup (see error logs)
L 05/14/2024 - 22:57:34: [SM] Exception reported:

**Comment by peace-maker** [comment]
This issue tracker is for problems with sourcemod itself. For questions regarding usage or third party plugins, please use the [forums](https://forums.alliedmods.net/) or ask on the discord.

If you think there is a problem with parsing gamedata files, please add steps on how to reproduce the issue.
