### ISSUE TITLE
sourcemod no longer works on L4D2 latest update.

### ISSUE THREAD

**Issue by NatashaV3** [alliedmodders/sourcemod#2165]
Since the game updated, my sourcemod keep crashing on server start up even tho o tried changing sourcemod versions to newer
The Servers will Not show on steam group servers list. which is a problem, and Vlave doesnt consider that a problem when i emailed them.

Update date: 14 May 2024
[https://steamdb.info/patchnotes/14357641/](https://steamcommunity.com/linkfilter/?u=https%3A%2F%2Fsteamdb.info%2Fpatchnotes%2F14357641%2F)

Here is the debug log:

--
-- Information
--

Installed

Nothing, only original Dedicated Files

--
-- Dedicated Server Debug Log
--

#Game_srv.so loaded for "Left 4 Dead 2"
Server is hibernating
ConVarRef test_progression_loop doesn't point to an existing ConVar
Parent cvar in server.dll not allowed (spit_scaling_min_scale)
Game supporting (2) split screen players
maxplayers set to 18
Unknown command "sv_maxplayers"
exec: couldn't exec server.cfg
Unknown command "mp_gamemode"
Unknown command "sv_gametype"
Unknown command "mat_bloom_scalefactor_scalar"
Network: IP 123.123.123.123, mode MP, dedicated Yes, ports 27200 SV / 0 CL
---- Host_NewGame ----
Host_NewGame on map c1m1_hotel
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file
VSCRIPT: Running mapspawn.nut
CSpeechScriptBridge initializing...
HSCRIPT loaded successfully
Initializing Director's script
Couldn't find any entities named fire13_timer, which point_template fire13_template is specifying.
Couldn't find any entities named fire13_clip, which point_template fire13_template is specifying.
Couldn't find any entities named fire13_smoke, which point_template fire13_template is specifying.
Couldn't find any entities named fire13_fog_volume, which point_template fire13_template is specifying.
Couldn't find any entities named fire14_timer, which point_template fire14_template is specifying.
Couldn't find any entities named fire14_clip, which point_template fire14_template is specifying.
Couldn't find any entities named fire14_smoke, which point_template fire14_template is specifying.
Couldn't find any entities named fire14_fog_volume, which point_template fire14_template is specifying.
Couldn't find any entities named fire15_timer, which point_template fire15_template is specifying.
Couldn't find any entities named fire15_clip, which point_template fire15_template is specifying.
Couldn't find any entities named fire15_smoke, which point_template fire15_template is specifying.
Couldn't find any entities named fire15_fog_volume, which point_template fire15_template is specifying.
Couldn't find any entities named fire16_timer, which point_template fire16_template is specifying.
Couldn't find any entities named fire16_clip, which point_template fire16_template is specifying.
Couldn't find any entities named fire16_smoke, which point_template fire16_template is specifying.
Couldn't find any entities named fire16_fog_volume, which point_template fire16_template is specifying.
Couldn't find any entities named sound, which point_template fire_ballroom_07-template is specifying.
Couldn't find any entities named fire03-sound, which point_template fire03-template is specifying.
Couldn't find any entities named fire04-sound, which point_template fire04-template is specifying.
Couldn't find any entities named fire10-sound, which point_template fire10-template is specifying.
Couldn't find any entities named fire27-sound, which point_template fire27-template is specifying.
Couldn't find any entities named fire28-sound, which point_template fire28-template is specifying.
Couldn't find any entities named fire_ballroom_02-sound, which point_template fire_ballroom_02-template is specifying.
Couldn't find any entities named fire_ballroom_01-sound, which point_template fire_ballroom_01-template is specifying.
Couldn't find any entities named fire_ballroom_03-sound, which point_template fire_ballroom_03-template is specifying.
Couldn't find any entities named fire_ballroom_04-sound, which point_template fire_ballroom_04-template is specifying.
Couldn't find any entities named fire_ballroom_05-sound, which point_template fire_ballroom_05-template is specifying.
Couldn't find any entities named fire_ballroom_06-sound, which point_template fire_ballroom_06-template is specifying.
Couldn't find any entities named fire_ballroom_07-particles, which point_template fire_ballroom_07-template is specifying.
Couldn't find any entities named fire_ballroom_07-point1, which point_template fire_ballroom_07-template is specifying.
Couldn't find any entities named fire_ballroom_07-point3, which point_template fire_ballroom_07-template is specifying.
Couldn't find any entities named fire_ballroom_07-point5, which point_template fire_ballroom_07-template is specifying.
Couldn't find any entities named fire_ballroom_07-point6, which point_template fire_ballroom_07-template is specifying.
Couldn't find any entities named fire_ballroom_07-hurt, which point_template fire_ballroom_07-template is specifying.
Couldn't find any entities named fire_ballroom_07-sound, which point_template fire_ballroom_07-template is specifying.
Couldn't find any entities named fire_ballroom_08-sound, which point_template fire_ballroom_08-template is specifying.
Couldn't find any entities named fire_ballroom_09-sound, which point_template fire_ballroom_09-template is specifying.
Couldn't find any entities named fire_ballroom_10-sound, which point_template fire_ballroom_10-template is specifying.
Couldn't find any entities named fire_ballroom_11-sound, which point_template fire_ballroom_11-template is specifying.
Couldn't find any entities named inferno02-sound, which point_template inferno02-template is specifying.
prop_door_rotating has Door model (models/props_downtown/metal_door_112_dm03_01.mdl) with no door_options! Verify that SKIN is valid, and has a corresponding options block in the model QC file
prop_door_rotating has Door model (models/props_downtown/metal_door_112_dm03_01.mdl) with no door_options! Verify that SKIN is valid, and has a corresponding options block in the model QC file
Commentary: Loading commentary data from maps/c1m1_hotel_commentary.txt.
Initializing Director's script
exec: couldn't exec server.cfg
Connection to Steam servers successful.
VAC secure mode is activated.

--
-- Client Debug Log
--

connect 123.123.123.123:27200
Connecting to public(123.123.123.123:27200)
Sending UDP connect to public IP 123.123.123.123:27200
Server using 'public' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address 123.123.123.123:27200
Grace request retry for unreserved server...
Retrying public(123.123.123.123:27200)
Sending UDP connect to public IP 123.123.123.123:27200
Server using 'public' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address 123.123.123.123:27200
Server approved grace request...
Retrying connection to 123.123.123.123:27200, server requires lobby reservation but is unreserved.
Retrying public(123.123.123.123:27200)
Retrying public(123.123.123.123:27200)
Retrying public(123.123.123.123:27200)
Retrying public(123.123.123.123:27200)
Retrying public(123.123.123.123:27200)
Retrying public(123.123.123.123:27200)
Retrying public(123.123.123.123:27200)
Retrying public(123.123.123.123:27200)
Connection failed after 10 retries.

BinkOpen( c:\program files (x86)\steam\steamapps\common\left 4 dead 2\left4dead2\media\l4d2_background05.bik )
==============================================
Regarding Metamod with Sourcemod, as soon as you install the two things, the game server no longer starts. Metamod seems to be fine.

Here is the debug log:

--
-- Information
--

Installed

Metamod: mmsource-1.11.0-git1153-linux
Sourcemod: sourcemod-1.11.0-git6962-linux

--
-- Dedicated Server Debug Log
--

#Game_srv.so loaded for "Left 4 Dead 2"
Server is hibernating
ConVarRef test_progression_loop doesn't point to an existing ConVar
Parent cvar in server.dll not allowed (spit_scaling_min_scale)
Game supporting (2) split screen players
maxplayers set to 18
Unknown command "sv_maxplayers"
exec: couldn't exec server.cfg
Unknown command "mp_gamemode"
Unknown command "sv_gametype"
Unknown command "mat_bloom_scalefactor_scalar"
Network: IP 123.123.123.123, mode MP, dedicated Yes, ports 27200 SV / 0 CL
#Game_srv.so loaded for "Left 4 Dead 2"
Server is hibernating
ConVarRef test_progression_loop doesn't point to an existing ConVar
Parent cvar in server.dll not allowed (spit_scaling_min_scale)
Game supporting (2) split screen players
maxplayers set to 18
Unknown command "sv_maxplayers"
exec: couldn't exec server.cfg
Unknown command "mp_gamemode"
Unknown command "sv_gametype"
Unknown command "mat_bloom_scalefactor_scalar"
Network: IP 123.123.123.123, mode MP, dedicated Yes, ports 27200 SV / 0 CL
#Game_srv.so loaded for "Left 4 Dead 2"
Server is hibernating
ConVarRef test_progression_loop doesn't point to an existing ConVar
Parent cvar in server.dll not allowed (spit_scaling_min_scale)
Game supporting (2) split screen players
maxplayers set to 18
Unknown command "sv_maxplayers"
exec: couldn't exec server.cfg
Unknown command "mp_gamemode"
Unknown command "sv_gametype"
Unknown command "mat_bloom_scalefactor_scalar"
Network: IP 123.123.123.123, mode MP, dedicated Yes, ports 27200 SV / 0 CL
========================
=======================

The update completely blocks the game servers from the Steamgroups from being displayed in the game. (I don't know whether that's supposed to be the case).

The update also destroyed some addons (well, that has nothing to do with Valve directly, but it's interesting):

- Metamod is working
- Tickrate 100 enabler working
- Sourcemod -> cause a crash on new update
- Stripper (1.2.2) -> cause a crash on new update
- L4DToolZ (1.1.0.2) -> cause a crash on new update

------------------------------------------------

With the old files before the update and an addon that I don't want to mention here, the game servers are displayed again in the server list in the game and sourcemod and all other addons also work the same as playing and connecting on the game server.
Information are from:  https://steamcommunity.com/app/550/discussions/0/4360125073502677611/

**Comment by Kenzzer** [comment]
According to your report, you're not using latest 1.11 sourcemod
`Sourcemod: sourcemod-1.11.0-git6962-linux`
patch 6963 is when the crash were fixed, please download latest sourcemod and try again

https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6964-linux.tar.gz

**Comment by NatashaV3** [comment]
The servers still do not show on Steam group servers list.

**Comment by Joaquel** [comment]
> The servers still do not show on Steam group servers list.

That's an issue since latest L4D2 update.
https://github.com/ValveSoftware/Source-1-Games/issues/6007

**Comment by psychonic** [comment]
The nature of this makes it seem unlikely to be an issue with SourceMod itself, but with some other plugin or extension running on top of SourceMod. Are you able to reproduce the behavior on a clean install with stock MM:S / SM and nothing else added?

If so, can you share steps to reproduce the issue? I'm not very familiar with the steam group system. How does one set that up? Where do you go to see it working. What do you expect to see that isn't there?

This is all covered by the issue template that seems to have been bypassed here.

**Comment by caxanga334** [comment]
@psychonic

I did some tests and the Steam group feature doesn't work even with a fully vanilla server.

## Steps to Reproduce

1. Install a Left 4 Dead 2 dedicated server.
2. Get the group ID of a Steam group that you are in. To find the group ID, you must be an admin and have access to the "edit group profile" page.
3. Associate the server with the Steam group by adding `sv_steamgroup <replace with group ID>` to the **server.cfg** file.
4. Start the server, make sure the ports used by the server are open.
5. Open Left 4 Dead 2.
6. Select *Play Campaign*.
7. Select *Play on Steam Group Server*.
8. Try to find the server you just created.

## What is happening

The Steam group servers page stays on *searching for games...* for a moment, then lists no games found. Meaning it's not finding **any** server.

Before the update I would get about 100 random servers listed there. The list also used to appear on the main menu.

This feature was broken by Valve and is most likely not related to Sourcemod or Metamod in any way.

**Comment by psychonic** [comment]
Thanks for the explanation

**Comment by oethanx** [comment]
> @psychonic
> 
> I did some tests and the Steam group feature doesn't work even with a fully vanilla server.
> 
> ## Steps to Reproduce
> 1. Install a Left 4 Dead 2 dedicated server.
> 2. Get the group ID of a Steam group that you are in. To find the group ID, you must be an admin and have access to the "edit group profile" page.
> 3. Associate the server with the Steam group by adding `sv_steamgroup <replace with group ID>` to the **server.cfg** file.
> 4. Start the server, make sure the ports used by the server are open.
> 5. Open Left 4 Dead 2.
> 6. Select _Play Campaign_.
> 7. Select _Play on Steam Group Server_.
> 8. Try to find the server you just created.
> 
> ## What is happening
> The Steam group servers page stays on _searching for games..._ for a moment, then lists no games found. Meaning it's not finding **any** server.
> 
> Before the update I would get about 100 random servers listed there. The list also used to appear on the main menu.
> 
> This feature was broken by Valve and is most likely not related to Sourcemod or Metamod in any way.

Hello, i know the thread is closed. My server still faces this issue, are you it's game's fault and nothing to do with any configs or sourcemod? Were you able to find any solution for it?
