### ISSUE TITLE
[L4D1/2] Unrecognized library "server"

### ISSUE THREAD

**Issue by rootbeer9292** [alliedmodders/sourcemod#2166]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 11 Build 22631
  * Game/AppID (with version if applicable):  550
  * Current SourceMod version: 1.11 6964
  * Current SourceMod snapshot: 1.12 7136
  * Current Metamod: Source snapshot: 1.12 1194
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Sourcemod won't load on singleplayer or local hosted server on 1.12 snapshot.

# Logs
[errors_20240522.log](https://github.com/alliedmodders/sourcemod/files/15408207/errors_20240522.log)

**Comment by psychonic** [comment]
Listen servers (local, non-dedicated servers) have not been officially supported by SourceMod for more than ten years.
