### ISSUE TITLE
SM .autoload files don't autoload extensions from x64 subdirectory

### ISSUE THREAD

**Issue by KaelaSavia** [alliedmodders/sourcemod#2183]
# Description

This is pretty minor thing so it's not really a priority but if you put .autoload file into extensions/x64/ folder then it won't auto load unlike 32-bit equivalent extensions folder

**Comment by Kenzzer** [comment]
This seems to be intended ? If you place the autoload file inside `extensions` it will load the x64 extension.
Example :
```
- sourcemod
| - extensions
     - accelerator.ext.autoload
     - accelerator.ext.so
     - x64
     | - accelerator.ext.so
```

**Comment by psychonic** [comment]
> This seems to be intended ? If you place the autoload file inside `extensions` it will load the x64 extension. Example :
> 
> ```
> - sourcemod
> | - extensions
>      - accelerator.ext.autoload
>      - accelerator.ext.so
>      - x64
>      | - accelerator.ext.so
> ```

This is correct and intended.
