### ISSUE TITLE
Event: player_spawn is fired when player is not spawning

### ISSUE THREAD

**Issue by Rushaway** [alliedmodders/sourcemod#2188]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Ubuntu 22.04
  * Game/AppID (with version if applicable): Counter-Strike: Source
  * Current SourceMod version: SourceMod Version: 1.12.0
  * Current SourceMod snapshot: 7137
  * Current Metamod: Source snapshot: Metamod:Source version 1.11.0-dev+1155
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
The Event `player_spawn` is fired multiples times. It's fired when the server loading the map and player did not choose any teams yet. 
I'm able to repro it on clean server only with SourceMod and Metamod installed.

# Problematic Code (or Steps to Reproduce)
  ```sp
#include <sourcemod>

public Plugin:myinfo = {
    name = "Test",
    author = "",
    description = "",
    version = "0.0",
};

public void OnPluginStart()
{
    HookEvent("player_spawn", EventPlayerSpawn);
}

public Action EventPlayerSpawn(Handle event, const char[] name, bool dontBroadcast)
{
    int client = GetClientOfUserId(GetEventInt(event, "userid"));
    
    if (IsFakeClient(client))
        return Plugin_Handled;

    LogMessage("Debug(EventPlayerSpawn) - Client %L is spawning", client);
    return Plugin_Continue;
}
  ```

# Logs
```
L 07/05/2024 - 16:13:06: -------- Mapchange to de_dust2 --------
Executing dedicated server config file server.cfg
Set motd from file 'cfg/motd_default.txt'.  ('cfg/motd.txt' was not found.)
Set motd_text from file 'cfg/motd_text_default.txt'.  ('cfg/motd_text.txt' was not found.)
SV_ActivateServer: setting tickrate to 66.7
'server.cfg' not present; not executing.
Client ".Rushaway" connected (xx.xx.xx.xxx:62803).
Server waking up from hibernation
// I get connected on the server, current team is none (did not select any)
L 07/05/2024 - 16:13:20: [plugin.smx] Debug(EventPlayerSpawn) - Client .Rushaway<2><[U:1:1605719263]><> is spawning
// I join a team here and now trigger the event correctly.
L 07/05/2024 - 16:13:28: [plugin.smx] Debug(EventPlayerSpawn) - Client .Rushaway<2><[U:1:1605719263]><> is spawning
```

**Comment by psychonic** [comment]
There is no actual bug in SourceMod here. The game itself generates the `player_spawn` event, including when the invisible, spectating player entity is spawned, before a team is selected. SourceMod does not control when game events occur; it merely notifies the subscribed event listeners when they occur.
