### ISSUE TITLE
[TF2] Windows server crash on map change with tv_enable due to ICommandLine vtable change on 9247927 (2024-10-11)

### ISSUE THREAD

**Issue by nosoop** [alliedmodders/sourcemod#2208]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 10
  * Game/AppID (with version if applicable): Team Fortress 2 (232250), version 9247927 and newer

# Description
Having `tv_enable` set to 1 causes the server to crash on level change.

It's been tracked down to the following line:

https://github.com/alliedmodders/sourcemod/blob/4e15a92984570aee8cb8438c8fd8bd24876342ca/core/PlayerManager.cpp#L318-L319

The fix to asherkin/accelerator#22 strongly suggests that `ICommandLine` was changed.  Disassembling the `engine.dll` for calls to `::FindParm` (via string "-textmode") indicate that it was shifted from offset 10 to 12.

Note that this only affects Windows servers - the Linux offsets seem unchanged here.

# Problematic Code (or Steps to Reproduce)
```
tv_enable 1;
changelevel ctf_2fort;
```

# Logs
https://crash.limetech.org/ikaw7m54ung2

**Comment by LextYi** [comment]
Thank you so much for finding this bug. You are my lifesaver!

**Comment by OfficerSpy** [comment]
Is this happening for anyone else again after today's build?

**Comment by Kenzzer** [comment]
Yes, and we've the issue already fixed. Though I'm unable to commit directly to either repo, so we just gotta wait for one of the maintainers to merge the PRs. A working build should be available in the next few hours (hopefully)

That said, reverting SM to build 1.12.0.7158 or 1.11.0.6968 will also fix your issue. If you use accelerator, consider reverting your gamedata update as well.
