### ISSUE TITLE
[BUG] Sourcemod Half-life 2 Deathmatch slay

### ISSUE THREAD

**Issue by Lunacy1984** [alliedmodders/sourcemod#2229]
Half-life 2 Deathmatch Sourcemod basic admin commands.

Ever since the 20 anniversary update I am unable to get the sm_slay to work either through the admin menu or console.
This is confirmed by many other server owners with both Windows and Linux.
This should be fixed as this is part of the most basic server admin tools and affects many other server plugins.

**Comment by caxanga334** [comment]
This is already fixed in #2224 

Forgot to merge @psychonic ?

**Comment by psychonic** [comment]
> This is already fixed in #2224
> 
> Forgot to merge @psychonic ?

Yes, sorry! Merged now.
