### ISSUE TITLE
Check SDKCall NULL_STRING in l4d2

### ISSUE THREAD

**Issue by dmatt201** [alliedmodders/sourcemod#2233]
Hello, I had this problem when I used sourcemod 1.13 version 7175, when running it on l4d2 dedicated server. And the problem here is that the code of the CreateSurvivorBot plugin does not have the "VDECODE_FLAG_ALLOWNULL" flag. I am facing this when using this version of sourcemod 1.13, and the situation is that all l4d2 servers using this version will have the same problem as me, because I think almost everyone uses it. This plugin is for running a multiplayer server .Before that it didn't have any problems when I used sourcemod 1.13 version 7168 and previous versions like 1.12, and when I updated it and played a custom map for about 2 hours it had problems. this topic. It's still the same today, even the latest version
So please let's check this again, and maybe skip the check for l4d2. Because actually, even adding decode flags will not have any effect, and will crash the l4d2 server. Besides i use windows server to run the server

P/s :I hope you will understand what I say, and accept my presentation. Since I don't use github much, please forgive me for this

Here is my log when the server encountered this problem:

L 12/03/2024 - 20:43:30: [SM] Exception reported: NULL not allowed
L 12/03/2024 - 20:43:30: [SM] Blaming: CreateSurvivorBot.smx
L 12/03/2024 - 20:43:30: [SM] Call stack trace:
L 12/03/2024 - 20:43:30: [SM]   [0] SDKCall
L 12/03/2024 - 20:43:30: [SM]   [1] Line 64, CreateSurvivorBot.sp::NATIVE_NextBotCreatePlayerBotSurvivorBot
L 12/03/2024 - 20:43:30: [SM]   [3] NextBotCreatePlayerBotSurvivorBot
L 12/03/2024 - 20:43:30: [SM]   [4] Line 12, CreateSurvivorBot::CreateSurvivorBot
L 12/03/2024 - 20:43:30: [SM]   [5] Line 1438, d:\Github\Private-Work\L4D2-插件\scripting_1.11\l4dmultislots.sp::SpawnFakeClient
L 12/03/2024 - 20:43:30: [SM]   [6] Line 828, d:\Github\Private-Work\L4D2-插件\scripting_1.11\l4dmultislots.sp::JoinTeam_ColdDown

And this is the code that the creator of this plugin wrote:

#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>
#include <sdktools>

#define PLUGIN_VERSION 				"1.0"

public Plugin myinfo = 
{
	name 			= "[L4D1 & L4D2] CreateSurvivorBot",
	author 			= "MicroLeo (port by Dragokas)",
	description 	= "Provides CreateSurvivorBot Native",
	version 		= PLUGIN_VERSION,
	url 			= "https://github.com/dragokas"
}

Handle g_hSDK_RespawnPlayer;
Handle g_hSDK_NextBotCreatePlayerBot;

public APLRes AskPluginLoad2(Handle myself, bool late, char[] error, int err_max)
{
	CreateNative("NextBotCreatePlayerBotSurvivorBot", NATIVE_NextBotCreatePlayerBotSurvivorBot);
	CreateNative("CTerrorPlayerRoundRespawn", NATIVE_CTerrorPlayerRoundRespawn);
	return APLRes_Success;
}

public void OnPluginStart()
{
	GameData hGameData = LoadGameConfigFile("CreateSurvivorBot");
	if( hGameData == null ) SetFailState("Could not find gamedata file at addons/sourcemod/gamedata/CreateSurvivorBot.txt , you FAILED AT INSTALLING");
	
	StartPrepSDKCall(SDKCall_Player);
	if( PrepSDKCall_SetFromConf(hGameData, SDKConf_Signature, "CTerrorPlayer::RoundRespawn") == false )
		SetFailState("Failed to find signature: CTerrorPlayer::RoundRespawn");
	g_hSDK_RespawnPlayer = EndPrepSDKCall();
	if( g_hSDK_RespawnPlayer == null ) SetFailState("Failed to create SDKCall: CTerrorPlayer::RoundRespawn");
	
	StartPrepSDKCall(SDKCall_Static);
	Address addr = hGameData.GetAddress("NextBotCreatePlayerBot<SurvivorBot>");
	if( addr == Address_Null ) SetFailState("Failed to find signature: NextBotCreatePlayerBot<SurvivorBot> in CDirector::AddSurvivorBot");
	int iOS = hGameData.GetOffset("OS"); // 1 - windows, 2 - linux
	if( iOS == 1 ) // it's hard to get uniq. sig in windows => will use XRef.
	{
		Address offset = view_as<Address>(LoadFromAddress(addr + view_as<Address>(1), NumberType_Int32));
		addr += offset + view_as<Address>(5); // sizeof(instruction)
	}
	if( PrepSDKCall_SetAddress(addr) == false )	SetFailState("Failed to find signature: NextBotCreatePlayerBot<SurvivorBot>");
	PrepSDKCall_AddParameter(SDKType_String, SDKPass_Pointer);
	PrepSDKCall_SetReturnInfo(SDKType_CBasePlayer, SDKPass_Pointer);
	g_hSDK_NextBotCreatePlayerBot = EndPrepSDKCall();
	if( g_hSDK_NextBotCreatePlayerBot == null ) SetFailState("Failed to create SDKCall: NextBotCreatePlayerBot<SurvivorBot>");
	
	delete hGameData;
}

public int NATIVE_NextBotCreatePlayerBotSurvivorBot(Handle plugin, int numParams)
{
	char szName[MAX_NAME_LENGTH];
	
	if( numParams == 1 )
		GetNativeString(1, szName, sizeof(szName));
	
	return SDKCall(g_hSDK_NextBotCreatePlayerBot, NULL_STRING);
}

public int NATIVE_CTerrorPlayerRoundRespawn(Handle plugin, int numParams)
{
	if( numParams < 1 )
		ThrowNativeError(SP_ERROR_PARAM, "Invalid numParams");
	
	int bot = GetNativeCell(1);
	SDKCall(g_hSDK_RespawnPlayer, bot);
	return true;
}

/* // All-in-one sample:

stock int CreateSurvivorBot()
{
	int bot = SDKCall(g_hSDK_NextBotCreatePlayerBot, NULL_STRING);
	if( IsValidEntity(bot) )
	{
		ChangeClientTeam(bot, 2);
		
		if( !IsPlayerAlive(bot) )
		{
			SDKCall(g_hSDK_RespawnPlayer, bot);
		}
		return bot;
	}
	return -1;
}
*/

**Comment by asherkin** [comment]
This is a very clear bug in that plugin which should never have been using `NULL_STRING` here. You can fix the plugin by replacing the usage here with `""`, this won't be patched in SourceMod.

**Comment by caxanga334** [comment]
> And the problem here is that the code of the CreateSurvivorBot plugin does not have the "VDECODE_FLAG_ALLOWNULL" flag.

Then update the plugin and add the flag. This will allow NULL_STRING to be used.

See #2178

**Comment by dmatt201** [comment]
It seems like I tried the methods everyone said, but it still doesn't work. I probably have to let the creator of this plugin edit it himself because I respect the creator of this plugin. Anyway, thank you everyone for your replies, this topic can be closed here.
