### ISSUE TITLE
Plugins randomly unloading

### ISSUE THREAD

**Issue by stickz** [alliedmodders/sourcemod#605]
Is anyone else experiencing the issue starting at SM 1.8, where plugins are unloading at random times, without creating any sort of error session? I tried to reload one of the plugins, but it told me I couldn't because a native was unavailable. It doesn't let me know in error session, that this is happening. I had to load [a plugin near the top](https://github.com/stickz/Redstone/blob/master/addons/sourcemod/scripting/nd_player_skill.sp) of my native chain, then reload others beneath it, so they worked properly.

**Comment by peace-maker** [comment]
You need to register a plugin library using `RegPluginLibrary` in `AskPluginLoad2` for dependencies to be picked up correctly. All your include files are missing [the required structures](https://wiki.alliedmods.net/Optional_Requirements_(SourceMod_Scripting)#Creating_a_Dependency).
