### ISSUE TITLE
Add 'Exact Match' feature to plugins search page

### ISSUE THREAD

**Issue by InvexByte** [alliedmodders/sourcemod#608]
I know this isn't exactly SM related but I made an issue here as instructed by psychonic.

A lot of users link to their plugins via:
https://www.sourcemod.net/plugins.php

However, none of the fields (title, author, desc) include an exact match option.
I'm requesting an exact match checkbox be added for each of the above forum inputs so a user can search for plugins matching an exact name, description and most importantly author.

**Comment by psychonic** [comment]
I've added this for author now. There are no plans to add it for the other fields as they are generally much longer and more volatile.
