### ISSUE TITLE
Change Author Field when user updates AlliedModders forum Username

### ISSUE THREAD

**Issue by InvexByte** [alliedmodders/sourcemod#609]
I know this isn't exactly SM related but I made an issue here as instructed by psychonic.

When a user changes their username via the new username feature Asher added, their old plugins keep their old username here:
https://www.sourcemod.net/plugins.php

I'm suggesting a query be added upon updating a username to change all the old username so it properly shows the correct current username.

As an example, I recently changed my username from: 'InvexByte' to 'Byte'.

**Comment by psychonic** [comment]
It turns out that there was a job in place already to handle this, but it was broken for a bit. I believe that it's fixed now. Regardless, a one-time sync was successful.
