### ISSUE TITLE
Server Spamming "All players have connected. ..." with Sourcemod (BFG Warmod) 

### ISSUE THREAD

**Issue by ieSalex** [alliedmodders/sourcemod#615]
Hello,

Just got a problem here with our servers we actually run on a event. It seems that since the update something changed, just tested this over months and never got this situation. As soon as all 10 players are connected the server starts to spam this in the chat:

All players have connected. Match will start in 60 seconds.
All players have connected. Match will start in 60 seconds.
All players have connected. Match will start in 60 seconds.
All players have connected. Match will start in 60 seconds.
All players have connected. Match will start in 60 seconds.
All players have connected. Match will start in 60 seconds.
All players have connected. Match will start in 60 seconds.
All players have connected. Match will start in 60 seconds.
All players have connected. Match will start in 60 seconds.

Were running our servers with Sourcemod and BFG Warmod, everything up to date. The warmod also continues to work as he should. The problem only appears in the warmup time (unlimited time with warmod). As soon as all 10 players are ready the warmod just starts the match and the massage dissapears. Just searched for this problem, but cant find anything.

Got an idea? Would be really fine if we got a sollution as fast as possible, as i said were running the servers at this moment at a event.

**Comment by psychonic** [comment]
This is an issue with that plugin, not a bug in SourceMod.
