### ISSUE TITLE
SDKHook_Reload is broken 

### ISSUE THREAD

**Issue by csgo-hklegend** [alliedmodders/sourcemod#616]
function  SDKHookEx -> SDKHook_Reload is broken on csgo server 
please fix it

**Comment by RussianRonin** [comment]
Can you please push this to 1.9?

**Comment by Drifter321** [comment]
It was

**Comment by RussianRonin** [comment]
I do not see it in the 1.9 builds list here: https://www.sourcemod.net/downloads.php?branch=dev

Am I missing something?

**Comment by peace-maker** [comment]
It's in 6097. The CS:GO gamedata fix and the merge commit were both pushed at the same time. There are only builds for the latest commit on a push. You'll see that it skipped 6096.

**Comment by RussianRonin** [comment]
Thanks for the clarification!
