### ISSUE TITLE
Feature request: Plugin hash

### ISSUE THREAD

**Issue by ESK0** [alliedmodders/sourcemod#617]
I would like to request modification for PluginInfo function. I am talking about plugin hash which can be found with sm plugins info <#>

**Comment by KyleSanderson** [comment]
Why? Maybe there's a better way to handle what you're trying to accomplish?

**Comment by ESK0** [comment]
I want to add tracker for my plugin. First time I wanted to use SourceQuery to chech server variables.. but we are unable to get those since some update.. So then I think is will be possible with checking plugin hash but only way to get plugin has with ServerCommandEx and parse it. But it looks kinda suspiciously in server's console.

**Comment by peace-maker** [comment]
If people modify your plugin they could just hardcode the old hash to send to your service too.

**Comment by ESK0** [comment]
I know about it.. But to be hones.. Most people will just copy/paste code without reading it. So they will send their hash instead of mine... Another option is send to .php pluginname+pluginversion+author+customhash(which will constains plugin hash and some other data) and the .php will check if everything fits to our data stored in db..

**Comment by asherkin** [comment]
I don't particularly want to expose this to code, it would hinder us changing the hash calculation in the future. I do not think the provided use case is very strong given the potential negatives.
