### ISSUE TITLE
Bug while converting steamid64to2

### ISSUE THREAD

**Issue by nnv87** [alliedmodders/sourcemod#618]
So, while I'm trying to divide cSecondNum (converted to int) by 2, I always getting wrong result, seems like sourcemod rounds to ceil number I provide, as example, I'm trying to convert 76561198301265885 to SteamID2, but always getting wrong result (STEAM_0:0:1705000780 instead of STEAM_0:1:170500078). Also, calc provides correct number after division, but not sourcemod... ( http://joxi.ru/gmvq9N6iLwzllr.png )

```
stock void Steam64to2(char[] cSteamID, int iSize)
{
	char cInt64[2][11];
	
	//const = 7960265728 (full: 76561197960265728)
	Format(cInt64[0], 10, cSteamID[0]);
	Format(cInt64[1], 11, cSteamID[9]);
	
	int iFirst64Num = StringToInt(cInt64[0][7], 10) - 79;
	int iSecond64Num = StringToInt(cInt64[1], 10) - 60265728;
	
	iSecond64Num = 100000000 + iSecond64Num;
	
	char cSecondNum[32];
	
	Format(cSecondNum, 32, "%i%i", iFirst64Num - 1, iSecond64Num);
	
	float flSecondDiv64 = FloatDiv(StringToFloat(cSecondNum), 2.0); //Seems like bug here...
	
#if defined DEBUG
	PrintToServer("Debug: cInt64[0]: %s, iFirst64Num: %i, cInt64[0][10]: %s, cSecondNum: %s", cInt64[0], iFirst64Num, cInt64[0][9], cSecondNum);
	PrintToServer("Debug: cInt64[1]: %s, iSecond64Num: %i, flSecondDiv64: %.1f", cInt64[1], iSecond64Num, flSecondDiv64);
#endif
	
#if defined DEBUG
	PrintToServer("Debug: Got cSecondNum: %s, cSteamID[7]: %s, cSteamID: %s", cSecondNum, cSteamID[7], cSteamID);
#endif
	
	int iFirstNum = 0;
	
	if (flSecondDiv64 - RoundToFloor(flSecondDiv64) > 0)
		iFirstNum = 1;

	Format(cSteamID, iSize, "STEAM_0:%i:%i", iFirstNum, RoundToFloor(flSecondDiv64));
	
#if defined DEBUG
	PrintToServer("Debug: Got cSteamID: %s", cSteamID);
#endif
	
	return;
}
```

Any ideas?

**Comment by asherkin** [comment]
You have run into the limit of floating-point precision.
Your example from calc.exe is using double-precision floating-point numbers.

See the output from a simple C program doing -1127553871.0 / 2.0:
```
Float: -563776960.0, Double: -563776935.5
```

This is not a SourceMod issue.

**Comment by psychonic** [comment]
@asherkin Would it make sense for us to expose common Steam ID conversion natives? I think we already have the logic for most or all of the conversions already in core/logic somewhere and it would save people trying to do some of these silly workarounds.

**Comment by asherkin** [comment]
@psychonic That would make sense, or something like https://phabricator.alliedmods.net/D5?download=true + a 64-bit capable StringToInt (returning 2 halfs) to make building them (and anything else needing 64-bit ints) saner.
