### ISSUE TITLE
typedef'ing extended to identifiers/variables feature req

### ISSUE THREAD

**Issue by assyrianic** [alliedmodders/sourcemod#621]
'ello m8s, I would like to put an official request for typedefing to extend to variables.
I know that using "enum" with a name can technically do this by implicitly typedefing int to the enum's name but I'd the option to typedef other names as well as arrays.
I'll just code in my examples
```c++
#include <sourcemod>

// makes declaring vec3 an array of float.
typedef float[3] vec3_t;
...
// is really 'float origin[3];'
vec3_t origin;
```

or another example case with strings
```c++
typedef char[64] StrNameBuffer_t;
StrNameBuffer_t name;
strcopy(name, sizeof(name), "example typedef");
```

more complex example
```c++
typedef StringMap PlayerFields_t;
...
PlayerFields_t fields;
fields = new PlayerFields_t();
methodmap Player {
	public Player() {
	}
	property int iEquipment
	{
		public get() {
			int i; fields.GetValue("iEquipment", i);
			return i;
		}
		public set(const int val) {
			fields.SetValue("iEquipment", val);
		}
	}
};
// player methodmap is defined, we can typedef it now
typedef Player Enemy_t, Friendly_t;
```

**Comment by WildCard65** [comment]
I think creating the issue here would be better: https://github.com/alliedmodders/sourcepawn/issues

**Comment by assyrianic** [comment]
whoops, can this be moved?

**Comment by WildCard65** [comment]
Might be best if closed this one and leave other open
