### ISSUE TITLE
Server crashing when running any standard admin command

### ISSUE THREAD

**Issue by RussianRonin** [alliedmodders/sourcemod#625]
Since the latest CSGO update (6/20/2017), our servers have been crashing when running any standard admin command (/slap, /slay... etc)

I made a bug report on bugs.alliedmodders.com but I am going to make one here as it is keeping all of our servers down.

Here is an accelerator report. https://crash.limetech.org/bdarq5irrz6g

We are using the 1.9 branch build 6107.

**Comment by KyleSanderson** [comment]
Does this happen when using sm_kick or any not funcommands/sdktools commands?

**Comment by psychonic** [comment]
bugs.alliedmods.net no longer accepts bug reports for SourceMod (the category is disabled). This is the proper place.

Does the crash occur without the sourcetvmanager extension loaded? It's at the top of your stack trace.

**Comment by RussianRonin** [comment]
It does happen on using the kick command. But only if it has an argument. /kick will not crash it but /kick @me will.

I will have to get back to you on that about the sourcetvmanager extension.

**Comment by RussianRonin** [comment]
Deleting the sourcetvmanager extensions does stop the crashing. But I am pretty sure we use them as we do use demos on our server.

**Comment by psychonic** [comment]
If removing the extension stops the crashing, the extension is very likely the issue, not SourceMod itself. You should contact the author via the extension's thread on the forum.

**Comment by RussianRonin** [comment]
Can do. Thanks for the help!
