### ISSUE TITLE
Add a function to verify the existence of the translation phrase or not

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcemod#626]
I would like to be able to check the existence of the phrase in the translation cache. Now this is impossible. If the phrase does not exist, the formatting functions fires a fatal error, and the function call is terminated.

P.S.: Sorry for my english. I'm from Russia.

**Comment by Benoist3012** [comment]
I don't think sourcemod has a check for that, however, how about giving back the translation key into char var, instead of terminating the code execution?

Like:

```
"Command Access Refuse"
{
              "en" "You are not allowed to use this command."
}
```

`Format(sBuffer, sizeof(sBuffer), "%t", "Command Access Refused");
PrintToChat(client, sBuffer);`

Output: `You are not allowed to use this command.`

But if the translation doesn't exist do:

Output: `Command Access Refused.`

Just a suggestion.

**Comment by joao7yt** [comment]
I think the main option would be awesome, then if the translation doesn't exists, we will be able to send a hard coded default English sentence. Please

**Comment by asherkin** [comment]
What is your use case?

Generally, testing for programmer error (you're trying to use some other plugin's translation file) or user error (the user didn't update the translation file) is not something we want to support - it is very intentional that errors in SourcePawn are loud and halt execution.

**Comment by joao7yt** [comment]
It would just create more possibilities and would create a way to scripters to prevent the plugin to stop the function just because a translation is missing

**Comment by CrazyHackGUT** [comment]
I'm writing plugin with config in KV format. This config looks like that:
```
"SomePlugin"
{
    "SomeSection"
    {
        "name" "MyName"
        "id"   "MyID"
        // <...>
    }

    // <...>

    "SomeSection999"
    {
        "name" "Example"
        "id"   "911"
        // <...>
    }
}
```

I want that if there is a translation of "Item_ID" (ex. `Item_911`) exists, then use him, else use `name` ("Example") from config.

**Comment by joao7yt** [comment]
```
stock bool TranslationExists(char[] phrase, char[] file)
{
	char cfgFile[PLATFORM_MAX_PATH];
	char dirName[PLATFORM_MAX_PATH];
	
	BuildPath(Path_SM, dirName, PLATFORM_MAX_PATH, "translations");
	BuildPath(Path_SM, cfgFile, PLATFORM_MAX_PATH, "translations/%s.txt", file);
	
	if (!DirExists(dirName) || !FileExists(cfgFile))
	{
		return false;
	}
	
	Handle kv = CreateKeyValues("Phrases");
	FileToKeyValues(kv, cfgFile);
	
	bool contains[16];
	if (KvJumpToKey(kv, phrase))
	{
		char bufferformat[255];
		KvGetString(kv, "#format", bufferformat, sizeof(bufferformat), "");
		
		bool passed = false;
		if (!StrEqual(bufferformat, ""))
		{
			for (int i = 1; i < sizeof(contains); i++)
			{
				char buffer[4];
				Format(buffer, sizeof(buffer), "{%d:", i);
				if (StrContains(bufferformat, buffer) != -1)
				{
					passed = true;
					contains[i] = true;
				}
				else
				{
					contains[i] = false;
				}
			}
		}
		
		char bufferphrase[255];
		KvGetString(kv, langname, bufferphrase, sizeof(bufferphrase), "");
		
		if (StrEqual(bufferphrase, ""))
		{
			return false;
		}
		
		if (passed)
		{
			for (int i = 1; i < sizeof(contains); i++)
			{
				if (contains[i])
				{
					char buffer[4];
					Format(buffer, sizeof(buffer), "{%d}", i);
					if (StrContains(bufferphrase, buffer) == -1)
					{
						return false;
					}
				}
			}
		}
	}
	else
	{
		return false;
	}
	
	return true;
}
```

**Comment by KyleSanderson** [comment]
FormatTranslation is the better solution, and while I agree this is an area we need to work on, I need to defer to my peers on actual implementation.

**Comment by joao7yt** [comment]
FormatTranslation? Don't know about it... What is that?

**Comment by CrazyHackGUT** [comment]
@joao7yt 
1). KeyValues have a bug with case of letters. Read more [here](https://forums.alliedmods.net/showthread.php?p=2362727#post2362727).
2). This is checks translation exists on file. But SourceMod parse file once when map changes. So if you add a quick phrase to a file, then this check will succeed, but the format functions still throws an error that the phrase does not.

We need check phrase in cache. Not in file.

**Comment by joao7yt** [comment]
That's right, and I recoded using SMC Parser, see here: https://forums.alliedmods.net/showthread.php?t=298883

And about the cached translations, i don't a clue how to get them, but I think the way it's right now, at least helps.

**Comment by Benoist3012** [comment]
Honestly that would just be better to make my suggestion imo, instead of building custom stocks that are going to slow down our code.
`Format(sBuffer, sizeof(sBuffer), "%t", "Command Access Refused");`
If the translation for "Command Access Refused" exists, it gives back what's in the file:
'custom translation here'
and if it doesn't exist, it simply gives back to the plugin this string:
'#Command Access Refused'

So plugin can still run, and code execution isn't aborted.

And if possible make a function within  the sm core, that does the same stuff that when it retrieves a translation phrase for the %t param, but instead returns true or false, if said translation exist.

**Comment by asherkin** [comment]
@Benoist3012 That does not work as the format implementation wouldn't know how many parameters to process.

**Comment by Benoist3012** [comment]
Oh yeah I didn't think about that, and isn't possible to make it ignore all parameters if translation is missing ?

**Comment by joao7yt** [comment]
Hey guys, I updated the code, now it will cache the valid translations in an array. And it will simply check in that array if the translation is available in the client language, server language or English. Do you think it's less slow and less broken right now? Give me your feed back.

See [here](https://forums.alliedmods.net/showthread.php?t=298883).

**Comment by CrazyHackGUT** [comment]
I'm close the issue. Pull request #669 with needed natives has been merged,
