### ISSUE TITLE
Trouble with FileToKeyValues

### ISSUE THREAD

**Issue by joao7yt** [alliedmodders/sourcemod#627]
I'm having troubles trying to read a KeyValues tree from a file that is saved as UTF-8. I was having unexpected behaves in my code, so I decided to read and output the following file, just to see what happens:
```
"Test0"
{
	"test1"
	{
		"test"		"123"
	}
	"test2"
	{
		"test"		"123"
	}
}
```
And I read and output the file using:
```
char file[PLATFORM_MAX_PATH];
BuildPath(Path_SM, file, PLATFORM_MAX_PATH, "test1.txt");
Handle kv = CreateKeyValues("Test0");
FileToKeyValues(kv, file);
BuildPath(Path_SM, file, PLATFORM_MAX_PATH, "test2.txt");
KeyValuesToFile(kv, file);
CloseHandle(kv);
```

I received these on console:
```
KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\test1.txt

KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\test1.txt

KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\test1.txt

KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\test1.txt

KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\test1.txt
(*test2*),
```
And my output was:
```
"﻿"
{
}
```

I think the symbols used by the file to tell it's an UTF-8, is messing with the sourcemod reading it.

P.S.: Ok, so I realized the cause of it, it's the BOM, the UTF-8 without BOM will work, but since I need to use special characters, it's useless, so I just request a feature to allow us to read an UTF-8 file with BOM.

**Comment by asherkin** [comment]
UTF-8 without BOM is the correct format to use and will support all Unicode characters. None of the Source Engine or SourceMod file routines support byte order marks and it is not something that will be added.
