### ISSUE TITLE
KeyValues.SetUInt64 only sets high (?) bits

### ISSUE THREAD

**Issue by nosoop** [alliedmodders/sourcemod#635]
Leveraging KeyValues to work with SteamID64 strings, found that the high bits aren't set in the KeyValues at all.

(Aside, [`KeyValues.SetUInt64` documentation](https://sm.alliedmods.net/new-api/keyvalues/KeyValues/SetUInt64) indicates 0 = high, seems to be the opposite in practice?)

[Test plugin available here (`.txt` since Github doesn't like `.sp`).](https://github.com/alliedmodders/sourcemod/files/1127038/keyvalues_uint64_test.sp.txt)

Plugin outputs the following on SM:1.9.0.6115 / MMS:1.10.8-dev for Team Fortress 2 on Ubuntu 16.04, SM:1.8.0.5973 / MMS:1.11.0-dev+1034 for TF2 on Debian 9 (64-bit).

```
[keyvalues_uint64_test.smx] SteamID64: 76561198006980102 -> AccountID: 46714374
[keyvalues_uint64_test.smx]    (hex: 02C8CE06 01100001)
[keyvalues_uint64_test.smx] AccountID: 46714374 -> SteamID64: 46714374
[keyvalues_uint64_test.smx]    (hex: 02C8CE06 00000000)
```

Expected behavior is that SteamID64 in the third line matches that of the first line, and that the hex values in the second and fourth lines match.

**Comment by psychonic** [comment]
Good catch. Thanks for reporting.

PR #636  has a fix incoming.
