### ISSUE TITLE
Kicking bots using KickClient() causes frequent crashes after update

### ISSUE THREAD

**Issue by Timocop** [alliedmodders/sourcemod#637]
I have some problems with this 9a6900a0ba08fe63632a0d01fd9fd0203cd79bd0 on L4D1 and L4D2. Ever since i updated sourcemod to dev 29d1187 my server crashes frequently when kicking bots. Even worse, sometimes they dont get kicked. I noticed this when creating bots. This never happend before.

https://crash.limetech.org/pfx3qgxlozfy

**Comment by psychonic** [comment]
There's indeed an issue with that change for some games, including L4D and L4D2. I know what the issue is and will try to post the fix later today or tomorrow.
