### ISSUE TITLE
CS:GO message strings parsing into menus

### ISSUE THREAD

**Issue by Technoblazed** [alliedmodders/sourcemod#640]
Couldn't find this elsewhere, but basically:

- If a user has one of the cs:go strings in their name, `#buy`, `#SFUI_*` etc; when the names are displayed into menus, it causes the game to display the strings as the game engine would usually use them.

Example:

![image](https://i.tech-no.me/260717203212.png)
![image2](https://i.tech-no.me/260717203218.png)

Note: Not plugin related.

**Comment by psychonic** [comment]
There isn't much that we can do about this. It's just a side effect of how the game client handles the text sent from the server.

**Comment by Technoblazed** [comment]
Thanks :^)
