### ISSUE TITLE
[CS:GO] Basevotes error

### ISSUE THREAD

**Issue by mrkos9i4ok** [alliedmodders/sourcemod#641]
```
L 07/27/2017 - 22:39:23: [SM] Exception reported: Client index 5 is invalid
L 07/27/2017 - 22:39:23: [SM] Blaming: basevotes.smx
L 07/27/2017 - 22:39:23: [SM] Call stack trace:
L 07/27/2017 - 22:39:23: [SM]   [0] BanClient
L 07/27/2017 - 22:39:23: [SM]   [1] Line 349, /home/builds/sourcemod/linux-1.8/build/plugins/basevotes.sp::Handler_VoteCallback
```

**Comment by SZOKOZ** [comment]
You get that error when the client leaves before the ban takes place. It should say the client was not in game but oh well.

`	if (!pPlayer || !pPlayer->IsConnected())
	{
		return pContext->ThrowNativeError("Client index %d is invalid", client);
	}`
https://github.com/alliedmodders/sourcemod/blob/master/core/logic/smn_banning.cpp
