### ISSUE TITLE
Switch Case with default inside a custom function creates a 209 warning

### ISSUE THREAD

**Issue by xerox8521** [alliedmodders/sourcemod#644]
When using switch case with return a value inside a function the compiler throws warning 209 (http://i.imgur.com/5zFD8x5.png) even though there is a return value for every case

Short example script tested with 1.9.0.6128 and 1.8.0.6016: 
Tested on Windows 10 64-Bit

```
#include <sourcemod>
#pragma newdecls required


public void OnPluginStart()
{
	SomeFunction();
}

int SomeFunction()
{
	switch(GetRandomInt(0, 5))
	{
		case 0: return 125;
		case 1: return 75;
		case 2: return 35;
		case 3: return 700;
		default: return 100;
	}
}

**Comment by peace-maker** [comment]
Language specific issues should go into SourcePawn's tracker not SourceMod.
Please report it over there to make tracking easier!
https://github.com/alliedmodders/sourcepawn

**Comment by KyleSanderson** [comment]
Indeed. Please report this in the SP section.

As an aside, this pattern isn't great. Set a single cell at the start, use your case statements to set the var, then return that value. Generally leads to better code generation in other languages; probably here too.
