### ISSUE TITLE
Forwards still push disconnected client indexes

### ISSUE THREAD

**Issue by Timocop** [alliedmodders/sourcemod#645]
**MetaMod:Source v1.11.0-dev+1096V
Stripper v1.2.2
SourceMod v1.9.0.6119
Left 4 Dead (Linux)**

Everytime SMAC or other plugins kicks a player (not bot) some sdkhook forwards still fire even when the client has been kicked. Which also floods my sourcemod errors logs for ~1sec.
This only happend after the sdkhook fix (fd87cb6b239fc7a7cf3703c30c53396752efb18b, 29d118743446c2116d36ddb543f8673b8836944d).
Or this this intended after the fix?
Look at the timespan in the logs below.

## Connection log:
> 0/32 Players - 21:45:56 - <[DE]tom_the_teacher> <STEAM_1:0:***> <***> DISCONNECTED after 31 minutes. \<All players idle\>

_("All players idle" is a plugin which kicks all afk players when there are no non-afk players left)_

## Sourcemod error logs:
> L 07/30/2017 - 21:45:57: [SM] Exception reported: Entity 3 (3) is invalid
> L 07/30/2017 - 21:45:57: [SM] Blaming: fo_fatman.smx
> L 07/30/2017 - 21:45:57: [SM] Call stack trace:
> L 07/30/2017 - 21:45:57: [SM]   [0] GetEntPropEnt
> L 07/30/2017 - 21:45:57: [SM]   [1] Line 976, D:\Left 4 Dead Modding\L4D SERVER\L4D SERVER\scripting\include\smlib/clients.inc::Client_GetActiveWeapon
> L 07/30/2017 - 21:45:57: [SM]   [2] Line 657, fo_fatman.sp::OnPlayerRunCmd
> L 07/30/2017 - 21:45:57: [SM] Exception reported: Client 3 is not in game
> L 07/30/2017 - 21:45:57: [SM] Blaming: smac_speedhack.smx
> L 07/30/2017 - 21:45:57: [SM] Call stack trace:
> L 07/30/2017 - 21:45:57: [SM]   [0] IsPlayerAlive
> L 07/30/2017 - 21:45:57: [SM]   [1] Line 145, smac_speedhack.sp::OnPlayerRunCmd
> L 07/30/2017 - 21:45:57: [SM] Exception reported: Client 3 is not in game
> L 07/30/2017 - 21:45:57: [SM] Blaming: l4d_teammate_light.smx
> L 07/30/2017 - 21:45:57: [SM] Call stack trace:
> L 07/30/2017 - 21:45:57: [SM]   [0] GetClientTeam
> L 07/30/2017 - 21:45:57: [SM]   [1] Line 410, l4d_teammate_light.sp::OnPlayerRunCmd
> L 07/30/2017 - 21:45:57: [SM] Exception reported: Client 3 is not connected
> L 07/30/2017 - 21:45:57: [SM] Blaming: smac_eyetest.smx
> L 07/30/2017 - 21:45:57: [SM] Call stack trace:
> L 07/30/2017 - 21:45:57: [SM]   [0] IsFakeClient
> L 07/30/2017 - 21:45:58: [SM]   [1] Line 182, smac_eyetest.sp::OnPlayerRunCmd

**Full error log:**
[errors_20170730.zip](https://github.com/alliedmodders/sourcemod/files/1191877/errors_20170730.zip)

**Comment by KyleSanderson** [comment]
::OnPlayerRunCmd is from SDKTools, not SDKHooks.

**Comment by psychonic** [comment]
I'm not sure what's going on there. PlayerRunCommand is being called on a player entity that is not tied to a connected client, let alone an in-game one (which should be the state during which they're attached).

Possibly something wrong with our caching of connected/ingame state in L4D. Needs more investigation.

**Comment by Timocop** [comment]
@KyleSanderson Yea i know. I thought the client caching was commited after the sdkhook fix thats why i wrote '_after_ sdkhook fix', but i was wrong.

@psychonic Forgot to mention that `IsClientConnected` and `IsClientInGame` works perfectly fine.
I put those were the exceptions occurred and have no errors since.

I found some weird stuff out btw.
I have a connection logger (Modded version of [this plugin](https://forums.alliedmods.net/showthread.php?p=1845362)), which logs connects/disconnects (Using `player_connect/player_disconnect` events in combination with `IsClientConnected()`), same plugin for both server i have L4D1 and L4D2. In L4D1 however it doesnt log connects for some reason, i didnt even noticed. All my connection logs on L4D1 have disconnects only. L4D2 is fine.

```
15:26:26 - ===== Map change to l4d_airport04_terminal ===== - Max. 32 Players

3/32 Players - 15:26:30 - <siranul> <STEAM_1:1:***> <***> DISCONNECTED after -1 minutes. <Disconnect by user.>
3/32 Players - 15:26:44 - <siranul> <STEAM_1:1:***> <***> DISCONNECTED after -1 minutes. <Disconnect by user.>
3/32 Players - 15:26:51 - <siranul> <STEAM_1:1:***> <***> DISCONNECTED after -1 minutes. <Disconnect by user.>
3/32 Players - 15:27:17 - <siranul> <STEAM_1:1:***> <***> DISCONNECTED after -1 minutes. <Disconnect by user.>
3/32 Players - 15:27:56 - <siranul> <STEAM_1:1:***> <***> DISCONNECTED after -1 minutes. <Disconnect by user.>
3/32 Players - 15:28:36 - <siranul> <STEAM_1:1:***> <***> DISCONNECTED after -1 minutes. <Disconnect by user.>
3/32 Players - 15:28:53 - <siranul> <STEAM_1:1:***> <***> DISCONNECTED after -1 minutes. <Disconnect by user.>

15:30:24 - ===== Map change to l4d_airport01_greenhouse ===== - Max. 32 Players


15:30:38 - ===== Map change to l4d_airport01_greenhouse ===== - Max. 32 Players

0/32 Players - 15:40:04 - <[RU]siranul> <STEAM_1:1:***> <***> DISCONNECTED after 10 minutes. <Disconnect by user.>

```

**Comment by peace-maker** [comment]
This might be related. PlayerRunCmd seems to be called with an invalid CUserCmd pointer?
https://crash.limetech.org/sks6cgfvf55z
