### ISSUE TITLE
GetConVarInt() and ConVar.IntValue

### ISSUE THREAD

**Issue by Russian85** [alliedmodders/sourcemod#648]
**GetConVarInt()** and **ConVar.IntValue** return wrong number. When number is odd that functions fix it to even number.

**Example**:

_27607405_ = _27607404_
_27607407_ = _27607408_

**Comment by psychonic** [comment]
On what game? Many supported games set the int value from the float value (which loses precision with high numbers like that).

**Comment by Russian85** [comment]
> On what game? Many supported games set the int value from the float value (which loses precision with high numbers like that).

CS:GO

**Comment by psychonic** [comment]
Sorry, one more follow-up question... 

How is the ConVar value being set in this case?
- Via config or direct in game console?
- Via SM in code? If so, SetConVarString? SetConVarFloat? SetConVarInt?
- Some other way?

**Comment by Russian85** [comment]
ConVar CVAR;
	(CVAR = CreateConVar("swgm_groupid",		"XXXXXXXX",	"ID Steam группы.")).AddChangeHook(OnGroupChange);
	g_iGroupId = CVAR.IntValue;
