### ISSUE TITLE
Add GetClientAuthId Independient of PlayerManager

### ISSUE THREAD

**Issue by ramonberrutti** [alliedmodders/sourcemod#650]
Is there an idea to make GetClientAuthId independient? I only can use then of ClientPutInServer but is you use in CSGO in ClientConnect work perfect is test with a module.

Thanks!!

**Comment by asherkin** [comment]
Please review [the guidelines for contributing](https://github.com/alliedmodders/sourcemod/blob/master/.github/CONTRIBUTING.md) to this repository, as you were asked to on the form when submitting this issue.

Particularly:
- What is your end goal, or what are you trying to accomplish?
- Why is this necessary, or what benefit do you see with it?
- Will this be useful to others?

**Comment by ramonberrutti** [comment]
Thanks @asherkin 

- What is your end goal, or what are you trying to accomplish?
Check SteamId when Player Connect and Reject them with the Native RejectMsg.

- Why is this necessary, or what benefit do you see with it?
Don't is necessary in the most of the case.

-Will this be useful to others?
Yes, for other people that want to do the same that me.

**Comment by KyleSanderson** [comment]
Use GetClientSteamID.

**Comment by ramonberrutti** [comment]
Fixed. Using validate: false work perfect.
