### ISSUE TITLE
TE Effect will not be output once the TE effect is outside the map.

### ISSUE THREAD

**Issue by GrimReaperKR** [alliedmodders/sourcemod#651]
This problem is occurring after recent update. (for cs:s / cs:go)

how can i fix that problem?

not print any error logs in SRCDS dedicate

sorry, i can't english well

[Normal]
![hl2-2017-08-11-22-57-43-560](https://user-images.githubusercontent.com/30930337/29216194-c996be7c-7ee8-11e7-82af-5ad8275c7100.gif)

[Problem]
![hl2-2017-08-11-22-52-47-328](https://user-images.githubusercontent.com/30930337/29216171-b230b832-7ee8-11e7-9ce2-dd2d4af57e31.gif)

**Comment by asherkin** [comment]
This is an issue in the game/engine outside of the control of SourceMod, and thus out of scope for this issue tracker.
