### ISSUE TITLE
Setting a delimiter with dbi extension

### ISSUE THREAD

**Issue by tenub** [alliedmodders/sourcemod#652]
Is it possible to set a delimiter in a query using the dbi extension? If so, what is the correct way? If not, is there a possibility of this feature being added?

Currently trying to run a query of the form:

```sql
DELIMITER //
DROP TRIGGER IF EXISTS example_trigger //
CREATE TRIGGER example_trigger
	BEFORE INSERT ON example_table
	FOR EACH ROW
BEGIN
	CALL example_procedure(param, param2, ...);
END //

DROP PROCEDURE IF EXISTS example_procedure //
CREATE PROCEDURE example_procedure (IN in_param, IN in_param2, ...)
READS SQL DATA
BEGIN
	SET @@SESSION.max_sp_recursion_depth = 25;
	INSERT INTO example_table2 VALUES ... ON DUPLICATE KEY UPDATE ...;
END //
DELIMITER ;
```

If there is an alternate way of running something of the above form I'd be very grateful if someone could help.

**Comment by asherkin** [comment]
No, the DB API does not support multiple result sets, which is a prerequisite for queries of this form.

**Comment by peace-maker** [comment]
It does! [FetchMoreResults](https://sm.alliedmods.net/new-api/dbi/DBResultSet/FetchMoreResults)
