### ISSUE TITLE
Crash server - update 

### ISSUE THREAD

**Issue by szogi1910** [alliedmodders/sourcemod#657]
server crashed.

SourceMod Version Information:
SourceMod Version: 1.8.0.6019
SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6019)
SourcePawn API: v1 = 4, v2 = 11
Compiled on: Aug 18 2017 06:08:58
Built from: https://github.com/alliedmodders/sou...commit/b952414
Build ID: 6019:b952414
http://www.sourcemod.net/

debug log

`----------------------------------------------
CRASH: Fri Aug 18 16:07:43 CEST 2017
Start Line: ./srcds_linux -autorestart -game csgo -usercon +game_type 0 +game_mode 0 -tickrate 128 -maxplayers 20 -maxplayers_override 20 +ip 193.33.176.75 -port 27058 +sv_setsteamaccount -exec server.cfg +tv_enable 1 +tv_maxclients 0 +tv_port 25128 +tv_advertise_watchable 1 +mapgroup mg_active +map de_dust2 -debug -pidfile /data/dd2/logs/522696.cs.pid
[New LWP 15089]
[New LWP 15239]
[New LWP 15238]
[New LWP 15207]
[New LWP 15253]
[New LWP 15241]
[New LWP 15255]
[New LWP 15263]
[New LWP 15258]
[New LWP 15256]
[New LWP 15265]
[New LWP 15269]
[New LWP 15264]
[New LWP 15267]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./srcds_linux -autorestart -game csgo -usercon +game_type 0 +game_mode 0 -tickr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf760b936 in ?? () from /lib/i386-linux-gnu/libc.so.6
#0  0xf760b936 in ?? () from /lib/i386-linux-gnu/libc.so.6
#1  0xec76e72f in CForward::PushString(char const*) () from /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/bin/sourcemod.logic.so
#2  0xec423229 in non-virtual thunk to CHalfLife2::EntityToBCompatRef(CBaseEntity*) () from /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/bin/sourcemod.2.csgo.so
#3  0x00000005 in ?? ()
#4  0x0d13b6e0 in ?? ()
#5  0xf23528cb in ?? () from /home/data/dd2/522696.csgo128/csgo/bin/server.so
#6  0xf22d4c8a in ?? () from /home/data/dd2/522696.csgo128/csgo/bin/server.so
#7  0xf1e5baea in ?? () from /home/data/dd2/522696.csgo128/csgo/bin/server.so
#8  0xed0b680a in __SourceHook_FHCls_IServerGameClientsClientCommand0::Func(edict_t*, CCommand const&) () from /home/data/dd2/522696.csgo128/csgo/addons/metamod/bin/metamod.2.csgo.so
#9  0xf5ec0c64 in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#10 0xf5ea725d in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#11 0xf5f86200 in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#12 0xf5f86535 in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#13 0xf5f8818b in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#14 0xf5f887cc in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#15 0xf5f991ce in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#16 0xf5eee88f in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#17 0xf5ebb98c in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#18 0xf5f6ddbe in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#19 0xf5f6ea5c in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#20 0xf5f6f1c8 in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#21 0xf5f78414 in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#22 0xf5f786e6 in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#23 0xf5f787f9 in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#24 0xf5fdabba in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#25 0xf5fd7b06 in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#26 0xf6ff94ed in ?? () from /data/dd2/522696.csgo128/bin/dedicated.so
#27 0xf6ff9578 in ?? () from /data/dd2/522696.csgo128/bin/dedicated.so
#28 0xf5fd7bfd in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#29 0xf610c090 in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#30 0xf5fd8def in ?? () from /home/data/dd2/522696.csgo128/bin/engine.so
#31 0xf6ff9654 in ?? () from /data/dd2/522696.csgo128/bin/dedicated.so
#32 0xf7056890 in ?? () from /data/dd2/522696.csgo128/bin/dedicated.so
#33 0xf7057abe in ?? () from /data/dd2/522696.csgo128/bin/dedicated.so
#34 0xf7056890 in ?? () from /data/dd2/522696.csgo128/bin/dedicated.so
#35 0xf6ff28f3 in ?? () from /data/dd2/522696.csgo128/bin/dedicated.so
#36 0x080486f9 in main ()
No symbol table info available.
eax            0x0	0
ecx            0x5	5
edx            0x2	2
ebx            0x5	5
esp            0xfffb7c64	0xfffb7c64
ebp            0xfffb7d18	0xfffb7d18
esi            0xae038d0	182466768
edi            0x5	5
eip            0xf760b936	0xf760b936
eflags         0x210283	[ CF SF IF RF ID ]
cs             0x23	35
ss             0x2b	43
ds             0x2b	43
es             0x2b	43
fs             0x3	3
gs             0x63	99
From        To          Syms Read   Shared Object Library
                        No          linux-gate.so.1
0xf776a6e0  0xf77a1fcb  Yes (*)     /lib/i386-linux-gnu/libm.so.6
0xf7761a30  0xf7762921  Yes (*)     /lib/i386-linux-gnu/libdl.so.2
0xf7748870  0xf7755ef1  Yes (*)     /lib/i386-linux-gnu/libpthread.so.0
0xf75a47f0  0xf76d147f  Yes (*)     /lib/i386-linux-gnu/libc.so.6
0xf77cf860  0xf77e86bd  Yes (*)     /lib/ld-linux.so.2
0xf754b1a0  0xf75678fc  Yes (*)     /data/dd2/522696.csgo128/bin/libtier0.so
0xf74ecb70  0xf751cf6c  Yes (*)     /data/dd2/522696.csgo128/bin/libvstdlib.so
0xf6ff25a0  0xf707fb98  Yes (*)     /data/dd2/522696.csgo128/bin/dedicated.so
0xf6fb3d60  0xf6fc91b4  Yes (*)     /data/dd2/522696.csgo128/bin/libsteam_api.so
0xf6f17914  0xf6f5dc78  Yes         /data/dd2/522696.csgo128/bin/libstdc++.so.6
0xf6ebde04  0xf6ecd4b8  Yes         /data/dd2/522696.csgo128/bin/libgcc_s.so.1
0xf5de9800  0xf6252ae0  Yes (*)     /home/data/dd2/522696.csgo128/bin/engine.so
0xf56ccc90  0xf57b2a5c  Yes (*)     /home/data/dd2/522696.csgo128/bin/materialsystem.so
0xf515d0d0  0xf5217c6c  Yes (*)     /home/data/dd2/522696.csgo128/bin/studiorender.so
0xf4f61cb0  0xf50bf9dc  Yes (*)     /home/data/dd2/522696.csgo128/bin/vphysics.so
0xf4e4cd80  0xf4ecf704  Yes (*)     /home/data/dd2/522696.csgo128/bin/datacache.so
0xf4d724b0  0xf4dee054  Yes (*)     /home/data/dd2/522696.csgo128/bin/vscript.so
0xf662d330  0xf664a050  Yes (*)     /home/data/dd2/522696.csgo128/bin/shaderapiempty.so
0xf33dc4c0  0xf4052b04  Yes (*)     /data/dd2/522696.csgo128/bin/steamclient.so
0xf661e840  0xf6621dfc  Yes (*)     /lib/i386-linux-gnu/librt.so.1
0xf32eff60  0xf33151c0  Yes (*)     /data/dd2/522696.csgo128/bin/crashhandler.so
0xf2e10a40  0xf2e6dae8  Yes (*)     /home/data/dd2/522696.csgo128/csgo/bin/matchmaking_ds.so
0xf1c575d0  0xf2722a9c  Yes (*)     /home/data/dd2/522696.csgo128/csgo/bin/server.so
0xf18a3b50  0xf18d57d4  Yes (*)     /home/data/dd2/522696.csgo128/bin/soundemittersystem.so
0xf18696a0  0xf188511c  Yes (*)     /home/data/dd2/522696.csgo128/bin/scenefilecache.so
0xf660aa50  0xf660de92  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/metamod/bin/server.so
0xed0aab60  0xed0e4af0  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/metamod/bin/metamod.2.csgo.so
0xf77c5a90  0xf77c61c8  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/bin/sourcemod_mm_i486.so
0xec40b870  0xec57ce59  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/bin/sourcemod.2.csgo.so
0xec72f440  0xec784120  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/bin/sourcemod.logic.so
0xec163700  0xec181294  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/bin/sourcepawn.jit.x86.so
0xf77c04f0  0xf77c3324  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/updater.ext.so
0xec02fa60  0xec057df5  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/webternet.ext.so
0xeb014a80  0xeb01a8f0  Yes (*)     /lib/i386-linux-gnu/libnss_files.so.2
0xf6602b50  0xf66057d6  Yes (*)     /lib/i386-linux-gnu/libnss_dns.so.2
0xeaeea690  0xeaef6ba4  Yes (*)     /lib/i386-linux-gnu/libresolv.so.2
0xec710800  0xec71626c  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/game.cstrike.ext.2.csgo.so
0xec708c90  0xec70c4d8  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/bintools.ext.so
0xeae92370  0xeaec9c42  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/sdktools.ext.2.csgo.so
0xeae6fdc0  0xeae7b6a6  Yes         /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/SteamWorks.ext.so
0xeb00a780  0xeb010e78  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/topmenus.ext.so
0xeb001ae0  0xeb006634  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/clientprefs.ext.so
0xead41e80  0xeae61ea0  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/dbi.sqlite.ext.so
0xec701e30  0xec704698  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/geoip.ext.so
0xeacca320  0xeacfc4d0  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/regex.ext.so
0xe9dd5730  0xe9df4d12  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/sdkhooks.ext.2.csgo.so
0xe9cdf410  0xe9d9baa4  Yes         /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/socket.ext.so
0xeacb8aa0  0xeacc1b44  Yes         /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/dhooks.ext.so
0xe9162490  0xe91ed1f5  Yes (*)     /home/data/dd2/522696.csgo128/csgo/addons/sourcemod/extensions/dbi.mysql.ext.so
0xeac8d8f0  0xeac9e122  Yes (*)     /lib/i386-linux-gnu/libz.so.1
(*): Shared library is missing debugging information.
End of Source crash report`

**Comment by asherkin** [comment]
There is already an open issue for this and you are not adding anything helpful.
