### ISSUE TITLE
Fix pls weapons!!!! ERROR

### ISSUE THREAD

**Issue by MrMaZa1** [alliedmodders/sourcemod#661]
L 08/19/2017 - 15:41:13: [CSTRIKE] Failed to locate function.
L 08/19/2017 - 17:10:26: [CSTRIKE] Failed to lookup AliasToWeaponID signature.

**Comment by Benoist3012** [comment]
First of all don't give them orders, second of all "hello, hi"? maybe, third of all check check if your issue isn't already posted *cough* issue #655 *cough*.
Useless to make new issues when you have already one opened of it, + you aren't helping with your logs.
Have a nice day.
