### ISSUE TITLE
SourceMod stopped logging

### ISSUE THREAD

**Issue by ShawnCZek** [alliedmodders/sourcemod#663]
Hello!
I have problem with logging in SourceMod. SourceMod stops log things (include errors) after some time running. It can be some days, sometimes it's just one day. It started to happen about month ago and it's really annoying to have no logs when I need to do something or fix something. Only restarts can help.
I think it's because I have many plugins, but then it would be weird if I couldn't track all needed things.
Thanks in advance for help.

**Comment by asherkin** [comment]
There is nothing in this issue report that is actionable.

**Comment by ShawnCZek** [comment]
I don't know how to describe it more. I don't know what it makes, what files in SourceMod do logs or where I can find more info.

**Comment by peace-maker** [comment]
What game? What sourcemod/metamod version? Plugin/extension list? Does the server has the correct file permissions to write the log files? Do you see the errors in the server console and just not in the files? Are there really any errors occuring that should be logged? Do you see the normal sourcemod log files?

To get help, don't cherry pick your answers, but provide all the info!

**Comment by ShawnCZek** [comment]
- Counter Strike: Global Offensive
> SourceMod Version: 1.8.0.5985
>  SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.5985)
>     SourcePawn API: v1 = 4, v2 = 11
>     Compiled on: Apr 26 2017 03:37:41
>     Built from: https://github.com/alliedmodders/sourcemod/commit/6b5faff
>     Build ID: 5985:6b5faff

> [SM] Displaying 15 extensions:
[01] Automatic Updater (1.8.0.5985): Updates SourceMod gamedata files
[02] Webternet (1.8.0.5985): Extension for interacting with URLs
[03] CS Tools (1.8.0.5985): CS extended functionality
[04] BinTools (1.8.0.5985): Low-level C/C++ Calling API
[05] SDK Tools (1.8.0.5985): Source SDK Tools
[06] SDK Hooks (1.8.0.5985): Source SDK Hooks
[07] Top Menus (1.8.0.5985): Creates sorted nested menus
[08] SteamWorks Extension (1.2.1): Exposes SteamWorks functions to Developers
[09] GeoIP (1.8.0.5985): Geographical IP information
[10] <FAILED> file "curl.ext.so": /home/csgoserver/csgo/csgo/addons/sourcemod/extensions/curl.ext.so: cannot open shared object file: No such file or directory
[11] Regex (1.8.0.5985): Provides regex natives for plugins
[12] System2 (2.32): System Commands and Information
[13] Client Preferences (1.8.0.5985): Saves client preference settings
[14] SQLite (1.8.0.5985): SQLite Driver
[15] MySQL-DBI (1.8.0.5985): MySQL driver implementation for DBI

> [SM] Listing 45 plugins:
  01 "VIP" (1.0) by ShawnCZek
  02 "Rock The Vote" (1.8.0.5973) by AlliedModders LLC
  03 "Fun Commands" (1.8.0.5985) by AlliedModders LLC
  04 "Giveaways manager" (1.0) by ShawnCZek
  05 "SourceComms" (0.9.266) by Alex
  06 "[Scoreboard] Tags" (2.0) by ShawnCZek
  07 "Player Commands" (1.8.0.5985) by AlliedModders LLC
  08 "[Any] Chat Logging Redux + RTF Support" (1.1.2) by McFlurry, Keith Warren (Drixevel)
  09 "Quick Messages" (1.0.4.0) by Shane A. ^BuGs^ Froebel
  10 "Fun Votes" (1.8.0.5985) by AlliedModders LLC
  11 "Sound Commands" (1.8.0.5985) by AlliedModders LLC
  12 "NativeVotes Vote Tester" (1.0) by Powerlord
  13 "Anti-Flood" (1.8.0.5985) by AlliedModders LLC
  14 "Basic Info Triggers" (1.8.0.5985) by AlliedModders LLC
  15 "[CS:GO] SpawnTools7" (1.0.1) by meng & IDDQD
  16 "Basic Commands" (1.8.0.5985) by AlliedModders LLC
  17 "RandomCycle" (1.8.0.5973) by AlliedModders LLC
  18 "SourceBans" (1.4.11) by SourceBans Development Team
  19 "Basic Votes" (1.8.0.5985) by AlliedModders LLC
  20 "Shop" (2.0) by ShawnCZek
  21 "[CS:GO] Auto-commands" (1.0.0) by [-=KILL MAN=-]
  22 "MapChooser" (1.8.0.5973) by AlliedModders LLC
  23 "Admin Help" (1.8.0.5985) by AlliedModders LLC
  24 "Admin Menu" (1.8.0.5985) by AlliedModders LLC
  25 "Workshop Map Loader" (0.13.0) by Nefarius
  26 "[CS:GO] Game Mode Dice" (1.0) by ShawnCZek
  27 "Reserved Slots" (1.8.0.5985) by AlliedModders LLC
  28 "Client Preferences" (1.8.0.5985) by AlliedModders LLC
  29 "Basic Chat" (1.8.0.5973) by AlliedModders LLC
  30 "Advertisements" (2.0.2) by Tsunami
  31 "Jailbreak Team Balance" (3.0.7.2) by databomb
  32 "Custom Votes" (0.5.6) by chundo
  33 "Nextmap" (1.8.0.5985) by AlliedModders LLC
  34 "Clients tracker" (1.0.1) by ShawnCZek
  35 "Disable Radar" (1.2.2) by Internet Bully, some random guy
  36 "Map Nominations" (1.8.0.5973) by AlliedModders LLC
  37 "SQL Admin Manager" (1.8.0.5973) by AlliedModders LLC
  38 "NativeVotes Basic Commands" (1.0) by Powerlord and AlliedModders LLC
  39 "AFK Manager" (4.1.5) by Rothgar
  40 "NativeVotes" (0.8.3) by Powerlord
  41 "SQL Admins (Threaded)" (1.8.0.5973) by AlliedModders LLC
  42 "Basic Comm Control" (1.8.0.5985) by AlliedModders LLC
  43 "Admin File Reader" (1.8.0.5985) by AlliedModders LLC
  44 "[ANY] Bank" (1.0) by Arkarr
  45 "CS:GO Admin ESP" (2.1) by Root

- Yes, they have. It works normally some time, then it fucks up.
- No, when it goes wrong, I can't see it in console and in files. Just nothing.
- Yes, of course. I still work on plugin and they have errors. And if not, normal logs should work. And they don't. Both stop working at the same time.

**Comment by peace-maker** [comment]
Try updating sourcemod. There have been several breaking updates since that version you're using for csgo. Make sure your server is up to date too.

**Comment by ShawnCZek** [comment]
So I updated my server and I'll see. I can't restart the server now, because it's almost full. So I will write an comment after the restart + some time server running.

**Comment by ShawnCZek** [comment]
So the server should run the newest version and it still doesn't work right. Last log is from yesterday night and there were players in the today morning.
>  SourceMod Version Information:
    SourceMod Version: 1.8.0.6024
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6024)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Aug 19 2017 07:06:42
    Built from: https://github.com/alliedmodders/sourcemod/commit/79a8bdd
    Build ID: 6024:79a8bdd
    http://www.sourcemod.net/

I am sharing last logs.
> L 08/22/2017 - 23:35:35: [randomcycle.smx] RandomCycle has chosen workshop/754568701/seek_space for the nextmap.
L 08/22/2017 - 23:49:22: [mapchooser.smx] Voting for next map has started.
L 08/22/2017 - 23:49:38: [mapchooser.smx] Voting for next map has finished. Nextmap: workshop/807564919/seek_town.

Proof there were players today (chat log from today):
> [Aug 23 |02:35:43| 2017] Enuabis (STEAM_1:0:128935820): votekick
[Aug 23 |02:35:49| 2017] cheeky (STEAM_1:1:43027513): votekick
[Aug 23 |02:35:53| 2017] csgoatse.com CSGONECRO.COM (STEAM_1:0:166060739): votekick
[Aug 23 |02:35:57| 2017] Enuabis (STEAM_1:0:128935820): votekick
[Aug 23 |02:35:59| 2017] Ma1kiee cs.money (STEAM_1:0:148802354): votekick

And then I tried `sm_chat` command. SourceMod didn't register it, but the chat log did. Because I have no logs today and the chat log has.
> [Aug 23 |08:44:54| 2017] (ADMINS)Console: test

Last thing. I have problem with timers in one plugin (I am fixing it now). The errors ended to print in the same time as logs. However, today there is single one error message from the night - 20 minutes after last logs.
> L 08/23/2017 - 00:08:02: SourceMod error session started
L 08/23/2017 - 00:08:02: Info (map "workshop/754568701/seek_space") (file "errors_20170823.log")
L 08/23/2017 - 00:08:02: [SM] Exception reported: Invalid timer handle df027cc6 (error 1)
L 08/23/2017 - 00:08:02: [SM] Blaming: Dice.smx
L 08/23/2017 - 00:08:02: [SM] Call stack trace:
L 08/23/2017 - 00:08:02: [SM]   [0] KillTimer
L 08/23/2017 - 00:08:02: [SM]   [1] Line 182, C:\Users\Shawn\Dropbox\Server\addons\sourcemod\scripting\Dice.sp::Event_RoundRestart

**Comment by KyleSanderson** [comment]
Try master once it ships and let us know. This should be largely fixed, as well as the other dozen or so cases where this could become a victim of circumstance.
