### ISSUE TITLE
Add natives for grenade management for cstrike extension

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcemod#665]
Ammo indexes common used in plugins that need to check/add/remove players' grenades (before we used CreateEntityByName, but now it is broken).
Functions based on this: [Getting ammo type (particularly grenades)](https://forums.alliedmods.net/showthread.php?t=300574)
I see two ways for it:
1) I suggest to add new function to extention for getting ammo indexes.
```native int CS_GetAmmoTypeIndex(const char[] ammotype);```
2) (I think is better) Add two native to grenade direct management
```
#define CS_GRENADE_HE 0
#define CS_GRENADE_FLASHBANG 1
#define CS_GRENADE_SMOKE 2
#define CS_GRENADE_MOLOTOV 3
#define CS_GRENADE_DECOY 4
// place for player tracer grenade
native int CS_GetGrenadeCount(int client, int type);
native void CS_SetGrenadeCount(int client, int type, int value);
```
Seems to be better because:
Not need to store offsets in each plugin.
3) Maybe add both.

Goal of this:
Help plugin that manage grenades.
Plugin not need to have own gamedata for it.

**Comment by micapat** [comment]
To help plugin readability, it could be nice to add:

`#define CS_GRENADE_INCGRENADE 3`

And it mustn't be forgotten for CS:GO the **weapon_tagrenade** (Offset "m_iAmmo": **22**).

------
Did you check if you had the same issue with the **weapon_healthshot** too (Offset "m_iAmmo": **21**) ? New natives could be needed for this weapon too.

**Comment by peace-maker** [comment]
Couldn't you iterate the m_hMyWeapons array of a player to count the grenades? I'd expect it to contain all the nades a player carries.

Something like
```sourcepawn
stock int GetGrenadeCount(int client, const char[] sClassname)
{
	char sBuffer[128];
	int iAmount;
	int iMaxWeapons = GetEntPropArraySize(client, Prop_Data, "m_hMyWeapons");
	for (int i; i < iMaxWeapons; i++)
	{
		int iWeapon = GetEntPropEnt(client, Prop_Data, "m_hMyWeapons", i);
		if (!IsValidEntity(iWeapon))
			continue;

		GetEntityClassname(iWeapon, sBuffer, sizeof(sBuffer));
		if (StrEqual(sBuffer, sClassname, false))
			iAmount++;
	}
	return iAmount;
}
```

To set it you could use `GivePlayerItem` and `RemovePlayerItem` based on the diff of the current amount.

**Comment by micapat** [comment]
I didn't test but this should still work:

**GetGrenadeCount:**
`int iGrenadeCount = GetEntProp(player, Prop_Data, "m_iAmmo", _, offset);`
**SetGrenadeCount:**
`SetEntProp(player, Prop_Data, "m_iAmmo", iGrenadeCount, _, offset);`

> Offset = 14 (HeGrenade), 15 (Flashbang) ....

---------

What I understand from this request is that before the last Valve update, the offset values could be retrieved (==> Avoiding to have constants in your plugins, in case Valve updates them one day..) but it's not working anymore.

See https://forums.alliedmods.net/showthread.php?t=300574.

**Comment by peace-maker** [comment]
I'm saying you don't need the ammotype directly for this.

**Comment by micapat** [comment]
Yes there're workarounds without using ammotype, but I guess **Kailo97** would like to keep the old method [1] (Or use a new easy method [2]). 

Calling **1** natives instead **1 + 4 * iMaxWeapons** natives should be a little better 😃.

**Comment by peace-maker** [comment]
Every native added needs maintaining after updates. If something is possible with the current API we should just use it.

The use case @Kailo97 provided can be done without any gamedata or new natives with some stocks like the following. You just lookup the ammo type once when you need it.

```sourcepawn
stock int GetWeaponAmmoType(int client, const char[] sClassname)
{
	static StringMap s_hAmmoTypes = null;
	if (s_hAmmoTypes == null)
		s_hAmmoTypes = new StringMap();

	// Already have this cached.
	int iAmmoType;
	if (s_hAmmoTypes.GetValue(sClassname, iAmmoType))
		return iAmmoType;

	// See if there's a weapon of this type available.
	int iWeapon = FindEntityByClassname(-1, sClassname);
	if (iWeapon == INVALID_ENT_REFERENCE || !IsValidEntity(iWeapon))
		return -1;

	// Cache the ammo type.
	iAmmoType = GetEntProp(iWeapon, Prop_Data, "m_iPrimaryAmmoType");
	s_hAmmoTypes.SetValue(sClassname, iAmmoType);
	return iAmmoType;
}

stock int GetGrenadeCount(int client, const char[] sClassname)
{
	int iAmmoType = GetWeaponAmmoType(client, sClassname);
	// No grenades of that type here at all, so the player can't have one.
	if (iAmmoType == -1)
		return 0;

	return GetEntProp(client, Prop_Send, "m_iAmmo", _, iAmmoType);
}

stock void SetGrenadeCount(int client, const char[] sClassname, int iCount)
{
	if (iCount < 0)
		return;

	int iCurrent = GetGrenadeCount(client, sClassname);
	if (iCurrent == iCount)
		return;

	int iAmmoType = GetWeaponAmmoType(client, sClassname);
	// Properly give the first grenade to add it to the player's inventory.
	if (iAmmoType == -1 || iCurrent == 0)
	{
		GivePlayerItem(client, sClassname);
		iCurrent++;
		iAmmoType = GetWeaponAmmoType(client, sClassname);
	}

	// Set the grenade count now.
	if (iAmmoType != -1)
		SetEntProp(client, Prop_Send, "m_iAmmo", iCount, _, iAmmoType);

	// Remove the last nade entity properly.
	if (iCount == 0)
	{
		int iWeapon = GetFirstWeapon(client, sClassname);
		if (iWeapon != INVALID_ENT_REFERENCE && IsValidEntity(iWeapon))
			RemovePlayerItem(client, iWeapon);
	}
}

stock int GetFirstWeapon(int client, const char[] sClassname)
{
	char sBuffer[128];
	int iMaxWeapons = GetEntPropArraySize(client, Prop_Send, "m_hMyWeapons");
	for (int i; i < iMaxWeapons; i++)
	{
		int iWeapon = GetEntPropEnt(client, Prop_Send, "m_hMyWeapons", i);
		if (!IsValidEntity(iWeapon))
			continue;

		GetEntityClassname(iWeapon, sBuffer, sizeof(sBuffer));
		if (StrEqual(sBuffer, sClassname, false))
			return iWeapon;
	}
	return INVALID_ENT_REFERENCE;
}
```

**Comment by KyleSanderson** [comment]
P-M's right here, I have code like this from 2011 that still works in SP. If this available in SP absolutely lets put it in the extension; but it's easily available as-is.
