### ISSUE TITLE
SRCDS Crashes when KeyValuesToFile() is called from a SourceMod Plugin - Synergy

### ISSUE THREAD

**Issue by Sarabveer** [alliedmodders/sourcemod#666]
#### Issue
SRCDS Crashes when `KeyValuesToFile()` is called from a SourceMod Plugin in Synergy

#### Behavior
I'm expecting it to Write my KeyValues to a File

#### Server Info
Windows 10 v1607 14393.1593, Synergy Source Dedicated Server 56.16  
SourceMod Version: 1.8.0.6022  
MetaMod Version: 1.10.7-dev Build ID: 959:4a27e2f

#### Stack Trace
https://crash.limetech.org/4polcjx3abxp

**Comment by Sarabveer** [comment]
Here is code to reproduce the error:

```
#include <sourcemod>

new Handle:playermodelskv
new String:playerfile[PLATFORM_MAX_PATH]

public OnPluginStart() {
        BuildPath(Path_SM, playerfile, sizeof(playerfile), "data/test.ini")
	playermodelskv = CreateKeyValues("Models")
	FileToKeyValues(playermodelskv, playerfile)
	KvJumpToKey(playermodelskv, "testkey", true)
	KvSetString(playermodelskv, "testkey", "testinfo")
	KvRewind(playermodelskv)
	KeyValuesToFile(playermodelskv, playerfile)
}
```

**Comment by psychonic** [comment]
The issue here is SDK 2013 mods that aren't on the latest version of the SDK not having the KeyValues cache methods on IKeyValuesSystem.

The interface isn't versioned, but I have a couple of ideas on how to work around it without changing functionality for games that do support it.

**Comment by Sarabveer** [comment]
Any update?
