### ISSUE TITLE
DBI MySQL driver can crash server if plugin uses SetFailState() in SQL callback

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcemod#686]
I think i found bug in MySQL DB Driver Extension.
When i call `SetFailState()` at SQL callback, game server may crash with probability ~40%.

**Comment by asherkin** [comment]
Do you have a crash report?

**Comment by CrazyHackGUT** [comment]
Link to crash on Accelerator will suit?

**Comment by psychonic** [comment]
Yes.

-- 
Nicholas Hastings

**Comment by KyleSanderson** [comment]
@CrazyHackGUT any update on this?

**Comment by CrazyHackGUT** [comment]
@KyleSanderson I will try to send a crash report within the next week.

**Comment by KyleSanderson** [comment]
Closing as INVALID.

**Comment by CrazyHackGUT** [comment]
I know that I'm very late, but still.
So far, i can reproduce only another problem. When you perform some queries on the MySQL database, all the same crash occurs.
https://crash.limetech.org/7clog7xpbg4m
