### ISSUE TITLE
KeyValues ExportToFile Not Including Colors

### ISSUE THREAD

**Issue by Headline22** [alliedmodders/sourcemod#689]
Test case:
```cpp
public void OnPluginStart()
{
	char path[PLATFORM_MAX_PATH];
	BuildPath(Path_SM, path, sizeof(path), "configs/somefile.txt");
	
	KeyValues kv = CreateKeyValues("some_kv");
	kv.SetColor("some_color", 255, 0, 0, 0);
	
	int r, g, b, a;
	kv.GetColor("some_color", r, g, b ,a);
	
	PrintToServer("%i %i %i %i", r, g, b, a);
	
	kv.ExportToFile(path);
	
}
```

Console output:
```
255 0 0 0
[SM] Plugin kv_testcase.smx reloaded successfully.
```

File output:
```
"some_kv"
{
}

```

This was reported to me by Drixevel, so thanks to him for reporting it.

Edit: I guess it's unimplemented in hl2sdk ref:https://github.com/alliedmodders/hl2sdk/blob/sdk2013/tier1/KeyValues.cpp#L973

**Comment by KyleSanderson** [comment]
I've mailed tfteam for you. If they implement it that's great; if not well, this is an SDK issue.
