### ISSUE TITLE
Issue with the DBI driver

### ISSUE THREAD

**Issue by Pukata** [alliedmodders/sourcemod#700]
After the csgo update around a week ago, i started getting crashes on my server.
I have many plugins which makes use of the DBI extension, so hard to pinpoint the exact behaviour that causes the crash, especially since they appear randomly, and need quite a few players on the server (15+ players) to trigger a crash. But they all tend to happen at the start of the map, when everyone is connecting, and a lot of database calls needs to be made.

Stack trace:
https://crash.limetech.org/sg4jaud5vyu3

Server info:
Linux version 4.9.30 (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) 
Metamod:Source version 1.10.7-dev
SourceMod Version: 1.8.0.6025

Also worth noting that im running the server in an lxc container.

Had a look at some crash statistics, and seems like im not the only one with the driver issue:
https://crash.limetech.org/stats/dbi.mysql.ext.so

**Comment by peace-maker** [comment]
Looks like you're mixing threaded and non-threaded queries in a plugin.

**Comment by Pukata** [comment]
But that hasn't been a problem up until now?
