### ISSUE TITLE
TF2_IgnitePlayer Broken

### ISSUE THREAD

**Issue by fearts** [alliedmodders/sourcemod#713]
TF2_IgnitePlayer is no longer working.

**Comment by fearts** [comment]
OS: Windows
Issue: Trying to ignite a player does nothing
Error Logs: None

**Comment by fearts** [comment]
Running a test with a simple plugin (https://pastebin.com/fvf4qBEC) to just sm_igniteplayer I notice I hear the flame sound and I also hear my player being hurt. However, no damage happens and after the sounds at the start nothing else happens.

**Comment by psychonic** [comment]
The default value of -1 for the duration no longer works the same as before with the new internal afterburn implementation. (I'm still not sure why there seem to be other cases where the game itself still calls with -1, working presumably fine there, but fix was to hardcode our documented duration of 10).

**Comment by MitchDizzle** [comment]
Why was this hardcoded to 10.0 seconds? Is the value ignored or can it be set to different elapsed times? Might be useful to just add an argument for the time, which defaults to 10 seconds. Just makes it easier to keep the flame on longer/shorter without creating some kind of timer to control the conditions etc.

**Comment by Headline** [comment]
@MitchDizzle You’re correct, an optional parameter to allow for time would be a great idea. 10.0 is entirely arbitrary

**Comment by psychonic** [comment]
> Why was this hardcoded to 10.0 seconds?

...

>  but fix was to hardcode our documented duration of 10).

> The default value of -1 for the duration no longer works

**Comment by MitchDizzle** [comment]
Was just wondering if it was a decision some where to make it only 10 seconds? If not I think it'd be worthwhile to add in another native to set the duration. I'll see if I can make the pull request but my c++ knowledge is very little.
