### ISSUE TITLE
Source Dev 1.9 - build 6216 not run

### ISSUE THREAD

**Issue by rsgua** [alliedmodders/sourcemod#730]
Hello, sm Dev 1.9 - build 6216 not run. I test 6206 - work

**Comment by Bara** [comment]
Same with 6210

Tried with meta load sourcemod:
> Failed to load plugin addons/sourcemod/bin/sourcemod_mm (Function CreateInterface not found).

**Comment by psychonic** [comment]
Until a fix gets integrated into the build, the temporary workaround for that issue (which only applies to new-ish builds on Linux, probably 1.8 too), run the following.

`objcopy --globalize-symbol=CreateInterface addons/sourcemod/bin/sourcemod.2.csgo.so`

**Comment by Timocop** [comment]
Same here (L4D2) any build after 6206 wont load.

**Comment by rsgua** [comment]
[CS:GO] SM 1.8 - build 6037 - not run too

**Comment by HallbergGG** [comment]
Hey any one of the developers looking at this already?

**Comment by asherkin** [comment]
I believe this has been fixed.

**Comment by Rainyan** [comment]
I'm getting this error when downloading the stable Win binaries from the website. Tried the latest build (6245) and the one before that.

> [META] Failed to load plugin addons/sourcemod/bin/sourcemod_mm: Function CreateInterface not found

> ] meta list
> Listing 1 plugin:
>   [02] \<ERROR\>

Using Metamod:Source version 1.10.7-dev (latest stable, build 963).
Episode 1 mp engine.

**Comment by asherkin** [comment]
Please open a new issue of your own and fill in the issue template completely.

**Comment by Rainyan** [comment]
Just in case someone stumbles here from google like I did, I managed to solve this by following the issue submission guidelines. Latest dev snapshot of both Metamod + SourceMod works fine. Probably not considered a bug, but caused some confusion as the latest stable MM + latest stable SM indeed fail to work together.

**Comment by asherkin** [comment]
It is probably due to removal of `core-legacy`, which is the original MM:S engine that was used for EP1 until recently - probably some lingering incompatibility that is only resolved in the development branch. Given the low usage of EP1-engine based games, it would probably be fairly low priority.

**Comment by psychonic** [comment]
It's extremely likely due to that. I'm fairly certain that we don't build against `core` for ep1 in the stable MM:S branch and I know we do build against `core-legacy` there. While we could probably make a compat shim, it doesn't seem worth the time. I'd rather just backport the changes if anything, now that stable SM requires it.

Regardless, also as mentioned separate issue would be more appropriate, and aimed at MM:S.

**Comment by KyleSanderson** [comment]
We could ship an MM:S release to sync-up. Alternatively rid ourselves of the stable branch as MM:S isn't seeing much if any development as of late.
