### ISSUE TITLE
L4D2 Finales Broken On Windows Servers

### ISSUE THREAD

**Issue by chatyak** [alliedmodders/sourcemod#739]
Every finale with a radio is broken. Log's spammed with:

21:57:25 (MOB) 160.00: MOB SPAWN ERROR: ANYWHERE = Empty spawn area set
21:57:25 (MOB) 160.03: MOB SPAWN ERROR: ANYWHERE = Empty spawn area set
21:57:25 (MOB) 160.07: MOB SPAWN ERROR: ANYWHERE = Empty spawn area set
21:57:25 (MOB) 160.10: MOB SPAWN ERROR: ANYWHERE = Empty spawn area set
21:57:25 (MOB) 160.13: MOB SPAWN ERROR: ANYWHERE = Empty spawn area set
21:57:25 (MOB) 160.17: MOB SPAWN ERROR: ANYWHERE = Empty spawn area set
21:57:25 (MOB) 160.20: MOB SPAWN ERROR: ANYWHERE = Empty spawn area set
21:57:25 (MOB) 160.23: MOB SPAWN ERROR: ANYWHERE = Empty spawn area set
21:57:25 (MOB) 160.27: MOB SPAWN ERROR: ANYWHERE = Empty spawn area set

Stock source and nothing else. Linux is fine.

**Comment by asherkin** [comment]
What makes you believe that this is an issue with SourceMod?

**Comment by chatyak** [comment]
Problem happens with source enabled - but turned out to be a cvar hidden deep in a cfg file. Please delete thanks!
