### ISSUE TITLE
Add method to link Commands to Plugins

### ISSUE THREAD

**Issue by InvexByte** [alliedmodders/sourcemod#742]
Okay so considering we have `plugin iterators` and `command iterators` there should be a way to know if a specific command belongs to a specific plugin. This data is already stored as functionality powers the built in `sm cmds` command.

However, parsing `sm cmds` has its own flaws (one being that commands names are cut off after 16 characters).

I propose a method to link commands to plugins is added to SourceMod.
I didn't find a way to do this without extensions so if this is already possible please enlighten me!

There are multiple ways in which this could be done.
One is to add a new API function that takes a command handle/name and gives you a plugin handle as returned by `ReadPlugin(pluginIterator);`.

Another method is to add a plugin num/id copyback to `ReadCommandIterator`.

**Comment by KyleSanderson** [comment]
What's the use-case?

**Comment by InvexByte** [comment]
Right now I'm trying to print out some information about all the commands belonging to a specific plugin.

Parsing `sm cmds` is not enough in my case because of the limitation I mentioned (i.e. it only prints 16 chars of the command). I need more specific command information such as the actual command flags instead of just the type `console` `admin` `server` access levels which I can get through the command iterator.

I mean you could make a very tiny extension to get you this information but I feel like it should be core.
