### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by myheartwellgoon** [alliedmodders/sourcemod#752]
When I use ForceChangeLevel in the plugins or use changelevel in the server console:

`threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x7088DA48/0x00000810/0x';`

Sourcemod v1.8.0.6040
Metamod 1.10.7-git961

All use the default extension;

**Comment by peace-maker** [comment]
TF2? This might be a duplicate of #748

**Comment by myheartwellgoon** [comment]
CSGO

**Comment by myheartwellgoon** [comment]
server is win2008 x64
