### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by myheartwellgoon** [alliedmodders/sourcemod#753]
sorry, i resend it:
OS:
window server 2008 X64

Engine:
CSGO

SM & MM:S
Sourcemod v1.8.0.6040
Metamod 1.10.7-git961

When I use ForceChangeLevel in the plugins or use changelevel in the server console:
`threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x7088DA48/0x00000810/0x'`

All use the default extension;

**Comment by asherkin** [comment]
Please do not create duplicate issues. 

Unless you have verified that this is an issue in SM, this should be a forum thread.

**Comment by myheartwellgoon** [comment]
i'm so sorry.
but i need help.

**Comment by Benoist3012** [comment]
Then start helping them by making sure your issue has to do with sourcemod and that's not a game bug.

**Comment by Majkovsky** [comment]
I also have this problem

**Comment by Majkovsky** [comment]
It seems to me that the bug lies in the latest version of Metamod Build **961** and you have to go back to the previous old version **959**.

**Comment by KyleSanderson** [comment]
Closing as there's no usable information in here :(
