### ISSUE TITLE
GivePlayerItem Fortress Forever

### ISSUE THREAD

**Issue by DarthMan** [alliedmodders/sourcemod#755]
Hello. The GivePlayerItem native from sdktools seems to crash my FortressForever server. Could the offsets be updated? I am working on a weapon giver plug-in. The offset for removing player weapon is bad as well. Many thanks !

**Comment by Drifter321** [comment]
Looking at the gamedata it looks correct. Do you happen to have a crash log from accelerator?

**Comment by DarthMan** [comment]
It was fixed. https://github.com/fortressforever/fortressforever-serveroffsets/blob/master/cffplayer_offsets_v2.7.6.txt
