### ISSUE TITLE
Alien Swarm Sourcemod crash

### ISSUE THREAD

**Issue by Sidewinder92** [alliedmodders/sourcemod#762]
Greetings Sourcemod Developers,

I have an issue regarding running Alien Swarm with Sourcemod. It mysteriously crashes at a strange moment, forcing me to desktop. Attached the ZIP File with the crash dump for you to inspect the issue.

Best regards,
Sidewinder92

[Swarm Crash Dump.zip](https://github.com/alliedmodders/sourcemod/files/1687137/Swarm.Crash.Dump.zip)

**Comment by asherkin** [comment]
I'm afraid that we do not support running SourceMod on game clients.
