### ISSUE TITLE
Cannot coerce functions to values

### ISSUE THREAD

**Issue by ntoxin66** [alliedmodders/sourcemod#770]
Hi Team,

From what I can tell. The "Cannot coerce functions to values" has turned from a warning into an error recently. I understand DataPack and Private Forwards are the current resolution which can cater to most cases.

Can I please request *Function methods be added to ArrayList and StringMap?

**Comment by asherkin** [comment]
Probably not, future non-int-sized function references cannot safely be stored in those containers.

**Comment by ntoxin66** [comment]
I will have a huge amount of high level plugins not compiling that require their callbacks to be registered in core plugins.

Surely there is some solution for ArrayList if function references are changing.

I really want to avoid extra Handles from using a private forward.

**Comment by KyleSanderson** [comment]
What? Why are you holding function ids? use references/private forwards.

**Comment by Headline** [comment]
Closing this as the issue seems stale, feel free to re-open and elaborate a response to kyle if you'd like

Thanks!
