### ISSUE TITLE
Support for Zombie Panic! Source 3.0 and above

### ISSUE THREAD

**Issue by JoelTroch** [alliedmodders/sourcemod#771]
This issue is a follow-up to the discussion on IRC about SourceMod support for [Zombie Panic! Source](http://store.steampowered.com/app/17500/Zombie_Panic_Source/) (ZPS) 3.0 and above.

**Note worthy informations:**
- We now use the "**Source SDK 2013 Multiplayer**" version of the Source engine (previously it was "Source 2007").
- The next ZPS version ("3.0.7-Hotfix2") will contain Linux binaries with this [patch](https://forums.alliedmods.net/showpost.php?p=2131144&postcount=2) applied.
- Main AppID is `17500`, dedicated server AppID is `17505`.

**Comment by JoelTroch** [comment]
We just released our "3.0.7-Hotfix2" patch that contains the Linux binaries with the SDK 2013 patch applied.

If you guys need help, just drop the word ^^

**Comment by Snneaky** [comment]
When is it going to be finished? any news?

**Comment by KyleSanderson** [comment]
Closing, fixed by PR #782.
