### ISSUE TITLE
SM Crash (1.10-6261)

### ISSUE THREAD

**Issue by sneak-it** [alliedmodders/sourcemod#789]
Hello, there appears to be a crash in the latest SM 1.10: https://crash.limetech.org/gc7kd3jn2mn6

OS: Windows Server 2008 R2
Game: CS:GO
MM:S Version: 1.11.0-dev+1103

I was going to test this on a fresh server install before creating an Issue, however @Headline recommended I create one regardless based upon the nature of the crash.

**Comment by Fyren** [comment]
Does this crash always happen to you on server start?  Only on some map changes?  If you remove all non-default extensions does it still happen?  You might be able to figure out a specific extension is causing a problem by disabling them one by one and retrying.

**Comment by sneak-it** [comment]
Just tested on a fresh server, with the same environment as above (windows version, sm version, mm:s version, game), except a fresh CS:GO install & everything default in SM, no crash anymore.

I tested adding a few more extensions, SteamWorks, no crash, then added PTaH, and now the server crashes instantly upon server start, no error logs.

Here is that crash dump: https://crash.limetech.org/z64ytfae4thn

**Comment by KyleSanderson** [comment]
This is almost certainly an issue in PTaH that's un-fixable in core and needs to be fixed at the ext level. Corrupt memory in an unsafe environment is corrupt memory.
