### ISSUE TITLE
Feature Request: CloneTrie() and CloneStack()

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcemod#796]
We have [CloneArray()](https://sm.alliedmods.net/new-api/adt_array/CloneArray), but we don't have `CloneTrie()` and `CloneStack()`. Why?

**Comment by KyleSanderson** [comment]
Freedom and things.

There's a snapshot already for a Trie.

**Comment by CrazyHackGUT** [comment]
Snapshot - "array" with keys from `StringMap`. This is not what I propose.
