### ISSUE TITLE
Strange issue - Crashing UNLESS variable is outputted in a specific way in previous scope first

### ISSUE THREAD

**Issue by Fare8545** [alliedmodders/sourcemod#798]
I have been having an odd issue regarding a sourcemod script I've been working on for left 4 dead 2 crashing with weird exception details; I've talked to my friend about this, and based on the fix he thinks that it might be a bug that should be reported.

Essentially so far all this script does is check a user's stats when they join (using system2) although currently all it does is say a message in chat if a user has a private profile (which can't be checked) so far.

[Here is the sourcecode](https://pastebin.com/yYdUJihD) fully commented with details, note line 46.

clientName is a variable that should be accessible anywhere after it's been set, it contains the user's display name.

At first, I only tried to actually output the variable (using PrintToChatAll) in a later function (line 75), but whenever this occurred, the script would crash referencing invalid client ID's.

I was doing debugging and decided to test to see if it would work before it did any checks, just to see if it could ever refer to the variable and output it to all chat, and as soon as I put a debug output using PrintToChatAll in a similar manner in a closer scope (line 46), it started working correctly.

If line 46 is removed, or is changed to something like PrintToServer instead, the crashes continue to happen. **So _PrintToChatAll(clientName)_ on line 75 will ONLY work in that function if there is also a _PrintToChatAll(clientName)_ in a previous function as well.**

[Another way to view the issue](https://www.diffchecker.com/lFAE7zbw) - The one on the right crashes on line 75 due to line 46 being commented.

**Sourcemod version**
    SourceMod Version: 1.8.0.6041
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6041)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Feb 15 2018 14:39:02
    Built from: https://github.com/alliedmodders/sourcemod/commit/d36b065
    Build ID: 6041:d36b065

**Comment by peace-maker** [comment]
Use the latetest 1.9 compiler or make `HttpResponseCallback` public!

**Comment by KyleSanderson** [comment]
P-M's right. If you use the latest compiler you should be okay. With any older compilers this was disallowed and absolutely needed to be public.
