### ISSUE TITLE
ArrayLists causing server memory leaks & plugin unloading

### ISSUE THREAD

**Issue by stickz** [alliedmodders/sourcemod#801]
When an ArrayList is created inside a function and not cleared, it will create memory leaks. If that function is called too many times, sourcemod will log an event in fatal and unload the plugin. This can cause other plugins not to function properly or fail if they depend on natives from the plugin being unloaded.

I would like to request a feature that automatically free's memory space (array cells), when an ArrayList is no longer accessible. It's not always appropriate to declare this class in the global file scope.

**Comment by stickz** [comment]
The API should say about in the class description if performing this action is required. Other languages do not require such an action to be performed on lists. It doesn't make sense for this step to be necessary.

**Comment by Benoist3012** [comment]
You didn't read the specifics about sourcepawn then, any created object must be deleted unless told otherwise. In your case and as you said nothing is said about deletion so you must delete it.

**Comment by Drifter321** [comment]
Where does it state that there is garbage collection? You create it, you’re responsible like everything else that is handle based.

**Comment by dvander** [comment]
Unless noted otherwise, any function that returns a Handle requires that you delete it when you're finished (or call CloseHandle). Handles are automatically freed when the plugin unloads.
