### ISSUE TITLE
How to measure the number of indeces in index buffer?

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#804]
Hi,

I have this source engine error: "too many indices for index buffer. tell a programmer".
Discussed [here](https://github.com/Facepunch/garrysmod-issues/issues/1286), [here](https://gmod.facepunch.com/f/gmoddev/nzlx/too-many-indices-for-index-buffer-tell-a-programmer-59838-32768/1/) and [here](https://steamcommunity.com/app/4000/discussions/1/558751364358575650/?l=french).
Caused in my case due to too complex custom models for players.

I need a way to measure the number of currently used indeces. So, I'll be able to find how many indeces used by each separate model.

Can I have such statistics using SM?
Or can you tip me please what source SDK API responsible for this, so I can made my own extension.
Sorry, if I found not appropriate place for my question.

Best regards,
Alex.

**Comment by KyleSanderson** [comment]
> Sorry, if I found not appropriate place for my question.
The AM forums is the appropriate place.
