### ISSUE TITLE
Can u add double type for variables(float has an error, like 0.699999 instead 0.7)

### ISSUE THREAD

**Issue by hitlerjugend** [alliedmodders/sourcemod#806]
# Help us help you
  - [ ] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: 
  * Game/AppID (with version if applicable): 
  * Current SourceMod version: 
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot:
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

# Problematic Code (or Steps to Reproduce)
  ```
  // TODO(you): code here to reproduce the problem
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by dvander** [comment]
This should go in the SourcePawn issue tracker [1] but fair warning, it's a long road to implement it. That said, doubles have an error too. They're still floating point.

[1] https://github.com/alliedmodders/sourcepawn

**Comment by KyleSanderson** [comment]
Further, please fill out a description for any issues you file anywhere in the future.
