### ISSUE TITLE
DOI - Can't exit

### ISSUE THREAD

**Issue by hellreturn** [alliedmodders/sourcemod#812]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Windows 2016 Server
  * Game/AppID (with version if applicable):  462310
  * Current SourceMod version:  Dev Build 1.9 6231
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot: 
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Cant exist on DOI. admin menu is the issue.

# Problematic Code (or Steps to Reproduce)
  ```
  // TODO(you): code here to reproduce the problem
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by KyleSanderson** [comment]
Can you clarify what you mean by this? If a menu is open the game client won't let you quit? If so this is 100% a game issue.
