### ISSUE TITLE
Crash after map load TF2 with SM 1.8 6043

### ISSUE THREAD

**Issue by grainz** [alliedmodders/sourcemod#815]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows
  * Game/AppID (with version if applicable):  Team Fortress 2
  * Current SourceMod version: 1.8 - build 6043
  * Current SourceMod snapshot: 1.9 - build 6231
  * Current Metamod: Source snapshot: 1.11 - build 1105
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
srcds crashes after map is loaded
Only happens with Sourcemod installed.
Server runs with and without Metamod: Source installed.
Happens on existing server and a clean server.

Missing shutdown function for Sys_InitAuthentication() : Sys_ShutdownAuthentication()
Missing shutdown function for S_Init() : S_Shutdown()
Missing shutdown function for Decal_Init() : Decal_Shutdown()
Missing shutdown function for InitStudioRender() : ShutdownStudioRender()
Missing shutdown function for StaticPropMgr()->Init() : StaticPropMgr()->Shutdown()
Missing shutdown function for modelloader->Init() : modelloader->Shutdown()
Missing shutdown function for InitMaterialSystem() : ShutdownMaterialSystem()
Missing shutdown function for HLTV_Init() : HLTV_Shutdown()
Missing shutdown function for g_Log.Init() : g_Log.Shutdown()
Missing shutdown function for ReplaySystem_Init( bDedicated ) : ReplaySystem_Shutdown()
Missing shutdown function for sv.Init( bDedicated ) : sv.Shutdown()
Missing shutdown function for g_GameEventManager.Init() : g_GameEventManager.Shutdown()
Missing shutdown function for NET_Init( bDedicated ) : NET_Shutdown()
Missing shutdown function for Key_Init() : Key_Shutdown()
Missing shutdown function for Filter_Init() : Filter_Shutdown()
Missing shutdown function for saverestore->Init() : saverestore->Shutdown()
Missing shutdown function for COM_Init() : COM_Shutdown()
Missing shutdown function for V_Init() : V_Shutdown()
Missing shutdown function for g_pCVar->Init() : g_pCVar->Shutdown()
Missing shutdown function for Cmd_Init() : Cmd_Shutdown()
Missing shutdown function for Cbuf_Init() : Cbuf_Shutdown()
Missing shutdown function for Con_Init() : Con_Shutdown()
Missing shutdown function for Memory_Init() : Memory_Shutdown()
Missing shutdown function for Host_Init( s_bIsDedicated ) : Host_Shutdown()
Missing shutdown function for Sys_InitMemory() : Sys_ShutdownMemory()
Missing shutdown function for Sys_Init() : Sys_Shutdown()
Missing shutdown function for COM_InitFilesystem( info.m_pInitialMod ) : COM_ShutdownFileSystem()

**Comment by Benoist3012** [comment]
Silly question but you don't mention it in your report. Have you tried to launch your server without sourcemod & metamod and see if it crashes?

**Comment by grainz** [comment]
Not a silly question. my mistake for not mentioning.
This happens only with Sourcemod installed. Server runs without issues with and without Metamod: Source.

**Comment by asherkin** [comment]
This looks like it is the same issue as #810, it should be resolved in 1.8-6044 / 1.9-6232.

**Comment by Benoist3012** [comment]
why this has been reopened? turns out it's not same as #810?

**Comment by NachoReplay** [comment]
I just started getting this as well. Running Ubuntu 14 lts tf2 server. All was running fine untill about a few days ago. Server runs fine stock no sm or meta. Tried most recent dev versions of both metamod and SM to no avail.

**Comment by ReallyLongName** [comment]
Same here with 6044

**Comment by SpikeyScout** [comment]
Same here, worked fine until a few days ago. On 6044, running Windows.

**Comment by Fyren** [comment]
Try 1.8 6064 or 1.9 6235 (or later).

**Comment by ReallyLongName** [comment]
Okay, running 1.8 6046 (Windows) and everything seems to be working fine. Thanks!
