### ISSUE TITLE
Server Crashes on Startup.

### ISSUE THREAD

**Issue by ScootyBootySauce2** [alliedmodders/sourcemod#816]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [ ] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [ ] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version
Windows 8.1 
  * Game/AppID (with version if applicable):
Team Fortress 2 
  * Current SourceMod snapshot: 
6044
  * Current Metamod: Source snapshot:
961
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

When starting the server it crashes, this happens when I freshly reinstall the server aswell so I know it's not corrupted. Here's my console.log if anyone needs it.

https://www.dropbox.com/s/u6obiv7nu1wp8iz/console.log?dl=1.

**Comment by asherkin** [comment]
Sorry, we're not going on a fishing expedition with you.
