### ISSUE TITLE
AutoExecConfig() doesn't work if cfg is too long

### ISSUE THREAD

**Issue by dragokas** [alliedmodders/sourcemod#817]
# Description & Problematic Code
https://forums.alliedmods.net/showthread.php?t=307696

# Help us help you
  - [v] I have checked that my issue [doesn't exist yet]
  - [-] I can't provide you test-case (because it's private), but I can give a temprorarily access for one person.
  - [v] I can always reproduce the issue with the provided description above.

# Environment
  * Operating System version: Windows 7.
  * Game/AppID (with version if applicable): 500
  * Current SourceMod version: Linux, sm v1.8 (official) or 1.10.0.6276 (self-built).
  - [v] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [v] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [v] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

**Comment by CrazyHackGUT** [comment]
> I can't provide you test-case (because it's private)
Write simple test case with long path to file (if i correctly understand problem).

**Comment by dragokas** [comment]
It can't be writted, because it's completely random. Though, people say it can be reproduced in L4d / L4d2 only (linux srcds issue).
Use my [ConVars Anomaly Fixer plugin](https://forums.alliedmods.net/showthread.php?t=307804) to find what ConVars is currently affected in your configuration.

**Comment by dragokas** [comment]
Valve bug is fixed by SilverShot using DHooks. Here is a plugin: https://forums.alliedmods.net/showthread.php?t=309656

**Comment by KyleSanderson** [comment]
> Valve bug is fixed

Cool thanks for the heads up.
