### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by Insomniac66** [alliedmodders/sourcemod#820]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 10
  * Game/AppID (with version if applicable): Team Fortress 2 / 440
  * Current SourceMod version: 1.8
  * Current SourceMod snapshot: SourceMod Version: 1.8.0.6046
  * Current Metamod: Source snapshot: Metamod:Source version 1.11.0-dev+1105
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.
  - This also happens when I build from source.

# Description
Some events aren't fired / relayed to plugins. Examples are "air_dash" and "player_chat". This is on a fresh install of srcds.

# Problematic Code (or Steps to Reproduce)
  ```
public void OnPluginStart()
{
    HookEvent("air_dash", AirDash_Event)
    HookEvent("player_death", PlayerDeath_Event)
}

public Action AirDash_Event(Event event, const char[] name, bool dontBroadcast)
{
    LogMessage("air_dash") // Won't show
}

public Action PlayerDeath_Event(Event event, const char[] name, bool dontBroadcast)
{
    LogMessage("player_death") // Will show
}
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

**Comment by asherkin** [comment]
SourceMod doesn't really have anything to do with this - do you have evidence that the game is firing these events on the server? (such as `net_showevents` output.)

**Comment by Insomniac66** [comment]
Ahh, my bad. Seems they removed and renamed some stuff. Cheers.
