### ISSUE TITLE
Plugins don't recompile when included file is updated

### ISSUE THREAD

**Issue by stickz** [alliedmodders/sourcemod#829]
# Environment
  * Operating System version: Windows and Linux
  * Current SourceMod version: 1.7.3
  * Current SourceMod snapshot: 5294
  * Current Metamod: Source snapshot: N/A

# Description
The sourcemod compiler will not recompile a plugin, if an included file is updated. 

The user has to manually go to the base file and change something, each time for the plugin to compile. If sourcemod is on GitHub with Travis, an extra commit is required. (if caches are enabled)

# Example
`#include "scripts/myFile.sp"`

If I updated myFIle.sp in the scripts folder, the plugin including it will not recompile.

**Comment by stickz** [comment]
I do use [socomp](https://github.com/stickz/Redstone/blob/master/build_scripts/build.sh#L91) for automated use.

**Comment by Fyren** [comment]
Whatever your problem is, it's not the compiler.  The compiler doesn't check if input files are modified.  It doesn't remember if they're modified.  It doesn't remember _anything_ and only writes out the compiled output.

**Comment by Benoist3012** [comment]
@stickz your problem is quite easy to solve, all you need is delete compile.dat hidden file that is generated everytime a plugin is compiled.

**Comment by Fyren** [comment]
We have arrived back at "you should be using `spcomp`."  The compiler is `spcomp` and `compile.exe` is not.

**Comment by Benoist3012** [comment]
Must have misunderstood their answer I thought they were saying spcomp was refusing to compile as well. Nvn then.
