### ISSUE TITLE
OnPlayRunCmd & unconnected clients

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcemod#832]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
Windows TF2 SM 1.9.0.6237

# Description
OnPlayerRunCmd does not check to see if player is connected
This issue didn't exist in 1.8

I could add a check within the plugins, though it might not be efficient.

# Error
  ```
L 06/18/2018 - 18:19:42: [SM] Call stack trace:
L 06/18/2018 - 18:19:42: [SM]   [0] IsClientSourceTV
L 06/18/2018 - 18:19:42: [SM]   [1] Line 1346, /home/forums/content/files/3/2/0/9/1/163527.attach::OnPlayerRunCmd
L 06/18/2018 - 18:19:42: [SM] Exception reported: Client 3 is not connected
  ```

**Comment by JoinedSenses** [comment]
I seem to receive a similar error for soundhooks

```L 06/18/2018 - 16:37:19: [SM] Exception reported: Client 2 is not connected
L 06/18/2018 - 16:37:19: [SM] Blaming: hide.smx::SoundHook
```

**Comment by KyleSanderson** [comment]
This is a game issue if these functions are being called when clients are not connected, this is not a SM issue. This is already normal behaviour for commandhooks.

**Comment by JoinedSenses** [comment]
Odd. I wonder why Im only seeing them once I switched from 1.8 to 1.9. Had these plugins a few years.
