### ISSUE TITLE
Gamedata for IOSoccer needs updating

### ISSUE THREAD

**Issue by richard-ob** [alliedmodders/sourcemod#833]
# Description
The latest public release of IOSoccer includes a renaming of the game directory from `ios` to `iosoccer`

**Comment by psychonic** [comment]
This is now fixed for the next build on all active branches, and in the gamedata updater.

Note that just offsets for SDKTools were fixed. Other function signatures were not checked, and as-is, there is no SDKHooks gamedata for IOSoccer (and none added).
