### ISSUE TITLE
[ZPS] Update for sdktools gamedata (signatures and offsets)

### ISSUE THREAD

**Issue by Silenci0** [alliedmodders/sourcemod#834]
Hello!

The ZPS sdktools gamedata that was updated a few months ago is missing signatures and some of the offsets. I have found these items and updated/tested them over the past few months and would like to issue a pull request to send over the changes, if that would be okay.

**Changes:**
- Updated signatures for FindEntityByClassname, FireOutput, and CBaseTempEntity/s_pTempEntities.
- Uncommented the CBaseTempEntity offsets (they were previously commented out due to lack of signatures).
- Updated SetEntityModel and WeaponEquip offsets (previously commented out and not updated).
- Reverted PlayerRunCommand offset name back to PlayerRunCmd.

Testing included running the updated gamedata on a live ZPS game server with plugins such as UMC, SMAC, Playervotes, etc. running and using the testsuite scripts to determine if the offsets/signatures were working correctly. If there are any further tests that should be done on my end to verify that the signatures are correct or if there are any questions, please let me know.

**Comment by Headline** [comment]
Thanks for wanting to organize changes before the pr, but feel free to close this, open the pr, and the changes can be discussed/directly reviewed there.

**Comment by Silenci0** [comment]
Thank you. I have created the pull request. Closing issue.
