### ISSUE TITLE
Aliases feature is now deprecated for CS:GO?

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcemod#842]
Now if try to "buy \<alias\>" eg. "buy magnum", says that it's not correct item name. Aliases was removed from CS:GO. CS_GetTranslatedWeaponAlias function was also removed.
May be now need to remove CS_GetTranslatedWeaponAlias for CS:GO from SM?
https://github.com/alliedmodders/sourcemod/blob/aae71612731eaa6771067a31f3a7ad34bdb0df28/extensions/cstrike/util_cstrike.cpp#L463-L489

**Comment by Drifter321** [comment]
Some aliases still work, for example fn57.
