### ISSUE TITLE
07/06/2018 CS:GO Gamedata Update

### ISSUE THREAD

**Issue by popey456963** [alliedmodders/sourcemod#843]
Since this seems like the latest update changed some gamedata, thought I'd create a thread so people could subscribe to know when it's fixed?

**Comment by psychonic** [comment]
What gamedata is broken?

**Comment by popey456963** [comment]
List of things that suddenly seems broken:

 - Kicking Players
 - SetTransmit::Func

Also broken on my server, perhaps for unrelated reasons:

 - Prepared Statements
 - Connecting to a DB

**Comment by psychonic** [comment]
A game update is not going to break the database API. That module is exactly the same on every game.

Need more details on things that "seem broken". What exactly is happening that's wrong? Code/steps to reproduce? Is there a reason that you scrapped or ignored the whole issue template?

**Comment by popey456963** [comment]
Crash logs:

 - Kicking Players: https://crash.limetech.org/4KDSBNUPOGBE
 - SetTransmit::Func: https://crash.limetech.org/OVMVXD2YQPGV

**Comment by popey456963** [comment]
Apologies for ignoring the issue template, in the past I thought it was simply a matter of grabbing offsets again and just wanted to create a thread to get alerted for the new update.

I did assume that the DB issues were likely due to me removing any modules that kick a player, hence the "perhaps for unrelated reasons" comment.

**Comment by Nachtfrische** [comment]
Well, the steps to reproduce the issue are quite simple.

1. Have the newest CSGO server version (1.36.4.0)
2. Kick a player (sm_kick Nachtfrische)

Server automatically crashes.
Crash log from me: 
https://crash.limetech.org/fgghlk5f47qx

**Comment by kice** [comment]
EmitSound also broken. I think we should check everything of sdktools.

**Comment by popey456963** [comment]
Getting an unusually high number of:

    Msg from 158.43.234.279:27005: CCLCMsg_VoiceData rejected by msg bind (88 bytes)

After the update.  Again, could be unrelated.

**Comment by popey456963** [comment]
Some hook crash, on latest SM. https://crash.limetech.org/WELWBA67UECR

**Comment by popey456963** [comment]
CallOnCoreMapEnd: https://crash.limetech.org/T6IHZPJJV2AZ

**Comment by psychonic** [comment]
The EmitSound and Kick/Ban issues have been fixed.

Two of the last three crashes linked are red herrings. (Think occurs every frame and is the root for a lot of logic, so it will show SM's hook in the stack, but SM is not the blame.). The CallOnCoreMapEnd one could be legitimate, but is a separate issue unrelated to the game update. It's likely at least partially caused by a mismatch of SM and extension versions.
