### ISSUE TITLE
CS:GO bugs with the new Panorama UI update

### ISSUE THREAD

**Issue by TropieRi** [alliedmodders/sourcemod#845]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Linux , don't know more, host doesn't tell.
  * Game/AppID (with version if applicable): 730 (Newest update 6/7/2018) (d/mm/yyyy)
  * Current SourceMod version: 1.9
  * Current SourceMod snapshot: 6241
  * Current Metamod: Source snapshot: 962
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
When using kick command it crashes the server. Any other commands don't seem to do it. I'm using sourcebans, but still wanted to tell it. Also server crashes randomly, I'm sorry that I'm not able to tell more. It came with the new UI update. Also almost all community servers are crashing.

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

I'm sorry but my host, for some reason doesn't allow me to get any logs/dumps.

**Comment by psychonic** [comment]
Double-check that the output of `sm version` matches the version you think you have one there. The issue was definitely fixed prior to the version you listed.

**Comment by Drifter321** [comment]
Latest snapshot should fix all SM related issues. If you still have issues it is third party plugin related.
