### ISSUE TITLE
The Windows Server still crashes (sourcemod.2.csgo.dll!SourceMod::StringHashMap)

### ISSUE THREAD

**Issue by Fastmancz** [alliedmodders/sourcemod#846]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows Server 2012 R2 Standard - Build 9600
  * Game/AppID (with version if applicable): CS:GO/740 (13640)
  * Current SourceMod version: 1.8.0.6050
  * Current SourceMod snapshot: 6241
  * Current Metamod: Source snapshot: 1.10.7-dev
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description

From (http://crash.limetech.org), crash ID: 35IO-BJ3Z-76WR
https://crash.limetech.org/35iobj3z76wr

[crash_35iobj3z76wr.zip](https://github.com/alliedmodders/sourcemod/files/2172915/crash_35iobj3z76wr.zip)

**When the player presses in !lr (8 - next), the server falls down.**

  ```
L 07/07/2018 - 18:41:45: [SM] Exception reported: Stack went below stack boundary
L 07/07/2018 - 18:41:45: [SM] Blaming: abner_round_end_sound.smx
L 07/07/2018 - 18:41:45: [SM] Call stack trace:
L 07/07/2018 - 18:41:45: [SM]   [1] Line 398, D:\Scripting\include\sdktools_sound.inc::EmitSoundToClient
L 07/07/2018 - 18:41:45: [SM]   [2] Line 127, abner_round_end_sound.sp::Client_StopSound
L 07/07/2018 - 18:41:45: [SM]   [3] Line 117, abner_round_end_sound.sp::StopMapMusic
L 07/07/2018 - 18:41:45: [SM]   [4] Line 528, abner_round_end_sound.sp::RoundEndCSGO
  ```

# Problematic Code (or Steps to Reproduce)
  ```
sourcemod.2.csgo.dll!SourceMod::StringHashMap<SourceMod::IChangeableForward *>::retrieve(char const *,SourceMod::IChangeableForward * *) [sm_stringhashmap.h:123 + 0xa]
  ```

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

Thanks for your patience and work. ❤️
Fastmancz.

**Comment by psychonic** [comment]
The fix for that specific crash is intentionally not in the 1.8 branch at this time. Upgrade to the new stable branch, 1.9.

https://www.sourcemod.net/downloads.php?branch=stable

**Comment by Fastmancz** [comment]
When I try to update to 1.9, the console writes to me that SM not found.

Files (folders) I have update:
bin
data
extensions
gamedata
plugins

Thanks for reply and help.
