### ISSUE TITLE
undefined symbol: ud_set_mode

### ISSUE THREAD

**Issue by Satanic-Spirit** [alliedmodders/sourcemod#853]
# Environment
  * Operating System version: "Debian GNU/Linux 9 (stretch)"
  * Game/AppID (with version if applicable):  Left 4 Dead 2 (2.1.5.1 7149)
  * Current SourceMod version: 1.10.0.6285
  * Current SourceMod snapshot: Latest 

# Description
Every time I try to compile an extension I get this undefined symbol issue. I had the environment setup for myself and all extensions used to work fine. The only thing that I changed was that I pulled the latest sourcemod from AM github.

# Meta Load Output
undefined symbol: ud_set_mode

**Comment by asherkin** [comment]
If your extension is using the SM copy of CDetour, you need to update your build files with the libudis86 source files: https://mxr.alliedmods.net/sourcemod/source/extensions/tf2/AMBuilder#24.

**Comment by Satanic-Spirit** [comment]
I added the lubudis86 source files, but it gave me another error.

Failed to load plugin addons/l4dtoolz/l4dtoolz_mm (Failed to get API).

BTW this is a Metamod extension. Following is the link to my github, if you want to take a look at source.
https://github.com/Satanic-Spirit/L4DToolz

i haven't updated the AMBuilder file on the repo yet.
