### ISSUE TITLE
Command arguments should support speech marks

### ISSUE THREAD

**Issue by popey456963** [alliedmodders/sourcemod#858]
# Environment
  * Operating System version: Linux
  * Game/AppID (with version if applicable): CSGO
  * Current SourceMod version: 1.9
  * Current SourceMod snapshot: N/A
  * Current Metamod: Source snapshot: N/A

# Description
When calling a command such as `/command "Arg 1" "Arg 2"` it suggests that there are four args instead of two.

# Problematic Code (or Steps to Reproduce)
  ```
  public Action Command_Something(int client, int args) {
    PrintToConsole(client, "Args count: %i", args);
  }
  ```

When calling this command with the above suggestion, it prints 4, in my view the true value should actually be 2.

**Comment by asherkin** [comment]
This is game-specific behaviour, the game you are using strips quotes from chat messages.

**Comment by psychonic** [comment]
To elaborate, commands do support quotation marks, which you can see if you execute the command in the client console.

Some games, notably CS:GO and games on the TF2 branch strip quotes from chat messages as noted above. This means they are not present when chat gets to the server to process for command triggers.

**Comment by popey456963** [comment]
Woah, my bad.  Thanks for the information, really interesting.
