### ISSUE TITLE
Fake clients improperly triggering OnClientDisconnect on server hibernation

### ISSUE THREAD

**Issue by geominorai** [alliedmodders/sourcemod#861]
# Environment
  * Operating System version: Linux
  * Game/AppID (with version if applicable): Team Fortress 2, v4620606 
  * Current SourceMod version: SourceMod v1.8.0
  * Current SourceMod snapshot: 6047
  * Current Metamod: Source snapshot: 961

# Description
I have servers running plugins that spawn and control puppet bots, but after all players leave, hibernation mode automatically kicks the bots and seems to trigger OnClientDisconnect in a weird way that even the clientprefs extension gets passed an invalid client entity and segfaults.

# Steps to Reproduce
1. Start the server
2. Connect to server
3. Leave the server

# Logs
https://crash.limetech.org/efgkq4pieq5u

Additional notes:
- Crash confirmed to not happen if hibernation mode is disabled with `tf_allow_server_hibernation 0`

**Comment by asherkin** [comment]
I'm not able to reproduce this with the latest version of SM and TF2, hopefully it's been fixed over these last many years.
