### ISSUE TITLE
SDKCall crashes on null char pointers

### ISSUE THREAD

**Issue by nosoop** [alliedmodders/sourcemod#874]
# Environment
  * Operating System version: Linux
  * Game/AppID (with version if applicable): Team Fortress 2
  * SourceMod version (tested): 1.9.0.6238

# Description

SDKCalls that expect a char pointer but receive a null pointer instead seems to result in a segfault.  This was observed when calling TF2's `GetTFConditionName()` function on non-existent conditions.  The function itself has bounds checks and returns null on invalid conditions.

# Problematic Code

[Available as a gist here.](https://gist.github.com/nosoop/781c73a9e6583f05ce2bd3a465ad017b)  Prints out addresses by default (breaking out of the loop after cond 127 as expected); uncomment and comment accordingly to get the string returned instead (crashing instead of exiting the loop).

**Comment by peace-maker** [comment]
Returning an empty string is still better than crashing? Throwing an error with no way for the programmer to avoid is bad.

**Comment by dvander** [comment]
It'd be incorrect to return an empty string because the C++ call is not returning an empty string. If the loop is coded to stop on an empty string then it might terminate prematurely.

Instead there should probably be a `SDKType_NullableString`, that fills in a bool parameter with true/false. Or `SDKType_StringEmptyIfNull` if you want to go the other route.

**Comment by asherkin** [comment]
To hit this case, the plugin must explicitly opt-in to getting NULL back with `VDECODE_FLAG_ALLOWNULL`, so I think it would be very reasonable to return an empty string here and avoid the crash.

As for exposing the state properly after fixing the immediate bug, a new type works, but as a trick we could do something like return “\0NULL” (if the buffer is big enough, but 3+ is almost always gonna be the case), then have a stock that checks if `str[0] == 0 && str[1] == 'N'`.

**Comment by dvander** [comment]
Good point - that seems reasonable, though if the string is not NULL, we have to be sure to write out extra zeroes.
