### ISSUE TITLE
Feature request: plugin version

### ISSUE THREAD

**Issue by TiBarification** [alliedmodders/sourcemod#876]
Add please plugin version print on plugin stack trace. It can help developers to support their plugins and quickly found corrupted section in plugin by knewing a version.

Example:
```
L 08/26/2018 - 14:43:21: [SM] Exception reported: Client index 1 is a bot
L 08/26/2018 - 14:43:21: [SM] Blaming: testplugin.smx (Version 1.1.1)
L 08/26/2018 - 14:43:21: [SM] Call stack trace:
L 08/26/2018 - 14:43:21: [SM]   [0] ThrowNativeError
....
```

**Comment by asherkin** [comment]
I'm not a fan of doing this, especially with the changes proposed in #877.

While in some cases the version number here might actually be useful, there are a number of cases that it can not cover (code changes without matching version bumps, natives provided by plugins where the source of the issue might be in the calling plugin) - and I'm not a fan of adding yet more information to error reports that doesn't serve a very clear purpose, users cause enough issues cutting off the "Exception reported:" line with the actual error message half the time.

I can't find it at the moment, but there is an open issue somewhere that talks about adding a new command to generate a package of debug info to use when reporting problems - I'd prefer to go down that route.
