### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by R1KO** [alliedmodders/sourcemod#881]
Hello. I suggest adding exceptions to the SourcePawn language. This would be a very useful mechanism.

**Comment by Headline** [comment]
Very few things fail during runtime. If they do fail and they shouldn't, file a bug. Otherwise, errors will either be user error (invalid client indexes or array out of bounds) or will have a return value to indicate failure (`GetClientAuthId`, for example)

**Comment by asherkin** [comment]
In very exceptional use cases, you can use `Call_StartFunction`/`Call_Finish` to catch plugin exceptions.

**Comment by R1KO** [comment]
For example, I have a code for successive validation of many values. If the value does not match, I want to format the error message, call some function (or more) and return a lie or go to the part of the code at the end of the function.
A bad solution is to use the GOTO operator.
But the ejection of a custom exception here would be what you need

```cpp
bool MyFunc(int param1, int param2, ...)
{
    char szError[256];
    if (!/* validate param1*/)
    {
        func1();
        func2();
        FormatEx(szError, sizeof(szError), "param 1 is invalid");
        return false;
    }
    if (!/* validate param2*/)
    {
        func1();
        func2();
        FormatEx(szError, sizeof(szError), "param 2 is invalid");
        return false;
    }
    if (!/* validate paramN*/)
    {
        func1();
        func2();
        FormatEx(szError, sizeof(szError), "param N is invalid");
        return false;
    }

    // code

    return true;
}
```

This code is cumbersome and many repetitive fragments.
Now you can do this:

```cpp
bool MyFunc(int param1, int param2, ...)
{
        char szError[256];
    bool bResult = true;
    if (!/* validate param1*/)
    {
        FormatEx(szError, sizeof(szError), "param 1 is invalid");
        bResult = false;
    }
    if (bResult && !/* validate param2*/)
    {
        FormatEx(szError, sizeof(szError), "param 2 is invalid");
        bResult = false;
    }
    if (bResult && !/* validate paramN*/)
    {
        FormatEx(szError, sizeof(szError), "param N is invalid");
        bResult = false;
    }
    
    if(!bResult)
    {
        func1();
        func2();
        // code
        return false;
    }

    // code

    return true;
}
```

But with the support of exceptions, he would look like this
```cpp
bool MyFunc(int param1, int param2, ...)
{
    try
    {
        if (!/* validate param1*/)
        {
            throw new Exception("param 1 is invalid");
        }
        if (!/* validate param2*/)
        {
            throw new Exception("param 2 is invalid");
        }
        if (!/* validate paramN*/)
        {
            throw new Exception("param N is invalid");
        }
    } catch (Exception hException)
    {
        char szError[256];
        func1();
        func2();
        FormatEx(szError, sizeof(szError), "param 2 is invalid");
        // code
        return false;
    }


    // code

    return true;
}
```

**Comment by Headline** [comment]
This example of your code should do everything you want
```
bool MyFunc(int param1, int param2, ...)
{
    char szError[256];
    if (!/* validate param1*/)
    {
        FormatEx(szError, sizeof(szError), "param 1 is invalid");
    }
    if (!/* validate param2*/)
    {
        FormatEx(szError, sizeof(szError), "param 2 is invalid");
    }
    if (!/* validate paramN*/)
    {
        FormatEx(szError, sizeof(szError), "param N is invalid");
    }
    
    if(strlen(szError) > 0)
    {
        func1();
        func2();
        // code
        return false;
    }

    // code
    return true;
}
```

There's always a way to handle it without an exception class.

**Comment by R1KO** [comment]
@Headline 

> This example of your code should do everything you want

I just brought it as an example.

> There's always a way to handle it without an exception class.

I do not claim that they are necessary, but it would be convenient to have this in the toolbox. Do not tell me about their usefulness

Well there is no way. Thanks for answering

**Comment by dvander** [comment]
If we add exception handling, it would only be to catch native errors. There are cases where it’s not economical to handle every error. I’d probably also want function granularity and not statement. But it’s a reasonable request, better filed against the sourcepawn project.
