### ISSUE TITLE
Add global forward OnPluginUnload

### ISSUE THREAD

**Issue by R1KO** [alliedmodders/sourcemod#890]
How do you look at adding this?
Maybe I can do it myself and send you a pull request

https://forums.alliedmods.net/showpost.php?p=2091765&postcount=21

**Comment by Headline** [comment]
Thanks for creating an issue!

Can you use `OnLibraryRemoved` instead? Our current dependency system is undefined in terms of load/unload order, but using libraries is much preferred.

**Comment by KyleSanderson** [comment]
I have an entire IPC system that absolutely needed this function 7 years ago... What I ended up doing was a hack in OnPluginEnd in every single plugin to let the memory management plugin know that the user was disappearing. There's another hack that you can do which is a private forward per plugin, and if GetFunctionCount returns 0 you know that user is gone.

Sorry I don't have a better answer for you.
