### ISSUE TITLE
Wrong Sorting Style For Choose Map sm_admin

### ISSUE THREAD

**Issue by CanadianJeff** [alliedmodders/sourcemod#892]
in sourcemod/plugins/basecommands/map.sp could we have it sort properly?

current sort order is ABC
```
c10m1
c10m2
c10m3
c10m4
c10m5
c11m1
```

I need it to be 123
```
c1m1
c1m2
c1m3
c1m4
c2m1
c2m2
```

**Comment by xerox8521** [comment]
Its actually correct considering it doesn't interpret it as 10 but as a whole string.

**Comment by CrazyHackGUT** [comment]
`sm_map` sorts map in order from `addons/sourcemod/configs/adminmenu_maplist.txt`
https://github.com/alliedmodders/sourcemod/blob/4f5764e4a5787eeb3751fa794bb6ca635aadfee0/configs/maplists.cfg#L30-L34
