### ISSUE TITLE
Server crashing due to some TerminateRound issue. Linux

### ISSUE THREAD

**Issue by RussianRonin** [alliedmodders/sourcemod#896]
# Help us help you
  - [:white_check_mark:] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).

# Environment
  * Operating System version: Debian 3.16.51-3
  * Game/AppID (with version if applicable): 740
  * Current SourceMod version: 1.9.0.6247
  * Current SourceMod snapshot: N/A
  * Current Metamod: Source snapshot: 1.10.7-dev

# Description
Server is crashing due to some issue related to fc14e37d0f8d92ee84b2bb051f5ceeef0f82f383 on linux. I would update to the latest dev but there are no linux builds available.

# Logs
https://crash.limetech.org/rsymz3afcikk

**Comment by Headline** [comment]
Thanks for creating this issue! Not sure why the linux & mac builds didn't go through, but I'll go ahead and investigate.

**Comment by awillinger** [comment]
Would it be possible to backport the fix into the stable version (1.9) as well?

**Comment by asherkin** [comment]
Linux 1.10 builds are now up and have these fixes.

> Would it be possible to backport the fix into the stable version (1.9) as well?

Once it is stable, yes.
