### ISSUE TITLE
SourceMod crash on latest SourcePawn pin

### ISSUE THREAD

**Issue by sneak-it** [alliedmodders/sourcemod#901]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows Server 2008 R2
  * Game/AppID (with version if applicable): CS:GO/730 (1.36.5.5)
  * Current SourceMod version: 1.9.0.6256
  * Current SourceMod snapshot: 1.10.6341
  * Current Metamod: Source snapshot: 1.11.0.1116
  - [ ] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [X] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [X] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
*Assuming* after build 6335, Sourcemod has been crashing with said binary when attempting to insert a query, or around there. I was running 6334 successfully without fault, then a breaking CS:GO update came out which required an update to 6338 or later, so I am unable to test if 6335 is indeed the offending build.

I have built my own version of 1.10, reverting https://github.com/alliedmodders/sourcemod/commit/6ad6abd3197b3e14a7da6c67a0eee6cb3bb1b76d which seems to solve the issue, however creates an inexplicable side effect: When players use a fuzzy map name to nominate a new map to play, or even use the /map command, the server crashes. Using an exact map name to nominate does not trigger a crash. https://crash.limetech.org/nveowvujpobc

None of these crashes occur in 1.9.

# Problematic Code (or Steps to Reproduce)
Narrowed down to a binary, which has been sent along to @dvander via @Headline . Regardless of whether this plugin is compiled on the 1.9 compiler or 1.10, the crash persists.

# Logs
https://crash.limetech.org/bx5iup5jc5nd, https://crash.limetech.org/xjmelc3jwbky, no error logs.

**Comment by dvander** [comment]
What exactly is line 21 in this snippet? (Using a paste service like gist.github.com might help)

**Comment by dvander** [comment]
Oh, I see - it's probably the debug print line. Could you attach the entire plugin? It's difficult to compare the disassembly with an isolated snippet.

**Comment by KyleSanderson** [comment]
When you're ready and if this is still an issue feel free to comment back with the STR.
