### ISSUE TITLE
Add registers support to SDKCall (feature)

### ISSUE THREAD

**Issue by Kailo97** [alliedmodders/sourcemod#902]
Good day, i want to make SDKTools work with functions that required registers pass. And i here to ask your opinion first. (I don't want to write new extension every time when function use register to pass or return.)
I make simple test case with raw implementation. https://github.com/Kailo97/sourcemod/commit/449589acc639c5eded618574389c7c07f7d91321

And from it, i got a question: (obviously this type of implementation, external from stack parameters, is not so good)
What model of implementation to choose? :
- [ ] External from stack parameters;
- [ ] Reobject ValveCall to process params that can be stack or register at same time. PrepSDKCall_AddParameter is extend. Params pass in SDKCall.

I'm not asking to do it, i will. Just ask for advice and opinion.
And i'm understand that now i used MSVC inline assembler (windows only) and probably should to conver it into sourcepawn MacroAssembler.

**Comment by Kailo97** [comment]
Implemented in #1020.

**Comment by AnthonyIacono** [comment]
@KyleSanderson Any chance we can re-open this? It doesn't appear it was ever completed.

I submitted this issue: https://github.com/alliedmodders/sourcemod/issues/1850
