### ISSUE TITLE
GeoIP Legacy Discontinuation

### ISSUE THREAD

**Issue by GoD-Tony** [alliedmodders/sourcemod#913]
At some point SourceMod's GeoIP extension should probably be updated to use [GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/).

> We have decided to discontinue our GeoLite Legacy databases effective January 2, 2019. We will stop updating the databases before that date (see “General Information” below), and the databases will no longer be available for download on January 2, 2019.

https://support.maxmind.com/geolite-legacy-discontinuation-notice/

**Comment by psychonic** [comment]
The newer API is a bit more complex, but porting to it wouldn't be too bad. It does look like there's no equivalent for GeoipCode3, the three letter country code.

We're probably best off just replacing the old API with new on the Dev version, and leaving stable alone.

**Comment by GoD-Tony** [comment]
A quick note that the packaging script for the stable branch might need an update to handle the soon-to-be broken URL used to download the legacy database.

**Comment by ambaca** [comment]
psss, any update on this ?

**Comment by Bara** [comment]
@ambaca https://github.com/alliedmodders/sourcemod/pull/914
but not merged yet.

**Comment by asherkin** [comment]
This has been sorted now 🎉
