### ISSUE TITLE
Feature Request: add Voicehook

### ISSUE THREAD

**Issue by Accelerator74** [alliedmodders/sourcemod#919]
Why do not add an event key for the SDKHooks when the player speaks on the microphone?

> SDKHook(client, SDKHook_OnVoiceTransmit, OnVoiceTransmit)

As an example my extension VoiceHook: https://github.com/Accelerator74/VoiceHook
It would be very convenient for it to be in the default build sourcemod.

Gamedata (found only for three games, for the rest I did not try):
```javascript
"Games"
{
	"csgo"
	{		
		"Offsets"
		{
			"OnVoiceTransmit"
			{
				"windows"	"513"
				"linux"		"514"
				"mac"		"514"
			}
		}
	}
	"left4dead"
	{		
		"Offsets"
		{
			"OnVoiceTransmit"
			{
				"windows"	"461"
				"linux"		"462"
				"mac"		"462"
			}
		}
	}
	"left4dead2"
	{		
		"Offsets"
		{
			"OnVoiceTransmit"
			{
				"windows"	"485"
				"linux"		"486"
				"mac"		"486"
			}
		}
	}
}
```

**Comment by psychonic** [comment]
As a tip for your extension, you don't necessarily need to maintain gamedata for it since you're compiling the SDK. You can switch the hook to be on IServerGameClients::ClientVoice, which is in a header we keep up to date and on an interface which we use heavily in SourceMod itself.

That said, I think we should be encouraging people to use DHooks rather than adding more hooks to SDKHooks. It is far more flexible and even allows for fully implementing SDKHooks itself in an SM plugin.

**Comment by Accelerator74** [comment]
If dhooks were in sourcemod assembly, I would have used it a long time ago. :) And since I don’t absolutely need a dhooks for more than one plug-in, I don’t want to use it.
Thanks for the tip, I'll fix it :)

It’s a pity that the hook in the sourcemod build is not yet available, but I will hope :)

**Comment by asherkin** [comment]
Extensions become included in SourceMod by being widely used. SDKHooks was not shipped in SourceMod until it was being used by almost every server.

**Comment by Accelerator74** [comment]
I added IServerGameClients::ClientVoice to my extension. It works well, thanks. Strange that a this function is simply not part of sourcemod, especially since this hook is present at the hl2sdk, but not used anywhere in the sourcemod.

eg:
``` 
#include <sourcemod>

public void OnClientVoice(int client) 
{
        PrintToChatAll("%N speaking" client);
}
```

It would be nice to have this function, also, as we have the OnClientPutInServer or OnClientDisconnected functions...

**Comment by KyleSanderson** [comment]
This absolutely needs an end forward otherwise it's not adding any value (I'd go so far as to call this as-is an anti-feature).

**Comment by Accelerator74** [comment]
Nothing prevents using the timer to turn it off inside the plugin code :)

```
#include <sourcemod>

bool ClientSpeaking[MAXPLAYERS+1];
int iCount;
char SpeakingPlayers[128];

public void OnPluginStart()
{
	CreateTimer(0.7, UpdateSpeaking, _, TIMER_REPEAT);
}

public void OnClientVoice(int client)
{
	ClientSpeaking[client] = true;
}

public Action UpdateSpeaking(Handle timer)
{
	iCount = 0;
	SpeakingPlayers[0] = '\0';
	for (int i = 1; i <= MaxClients; i++)
	{
		if (ClientSpeaking[i])
		{
			if (!IsClientInGame(i)) continue;
			
			Format(SpeakingPlayers, sizeof(SpeakingPlayers), "%s\n%N", SpeakingPlayers, i);
			iCount++;
		}
		ClientSpeaking[i] = false;
	}
	if (iCount > 0)
	{
		for (int i = 1; i <= MaxClients; i++)
		{
			PrintCenterText(i, "Players Speaking:%s", SpeakingPlayers);
		}
	}
}
```

**Comment by psychonic** [comment]
I agree with @KyleSanderson. I think there's more utility in doing something like adding the hook and tracking into SDKTools, firing a forward for start and stop of voice for a client. It does seem likely that most use cases would require that anyway, and saves each consuming plugin from having what amount to extra frame hooks.

That said, I'm only guessing at use cases since it's not a commonly requested feature.

**Comment by Accelerator74** [comment]
> As a tip for your extension, you don't necessarily need to maintain gamedata for it since you're compiling the SDK. You can switch the hook to be on IServerGameClients::ClientVoice, which is in a header we keep up to date and on an interface which we use heavily in SourceMod itself. (ClientVoice calls OnVoiceTransmit).
> 
> That said, I think we should be encouraging people to use DHooks rather than adding more hooks to SDKHooks. It is far more flexible and even allows for fully implementing SDKHooks itself in an SM plugin.

https://store.steampowered.com/news/52675/

After this update IServerGameClients::ClientVoice not work. If replace engine_srv.so from the April update ( http://www.l4d.com/blog/post.php?id=50400 ), then everything works again. Does this feature require updating, or is it Valve problem?

**Comment by Accelerator74** [comment]
> This absolutely needs an end forward otherwise it's not adding any value (I'd go so far as to call this as-is an anti-feature).

I did all the necessary functions, should I create a pool request? :)https://github.com/Accelerator74/VoiceHook

**Comment by Accelerator74** [comment]
This functions part of sourcemod version 1.11.6612 and above.
