### ISSUE TITLE
Mapchooser does not show map voting

### ISSUE THREAD

**Issue by paulocrash** [alliedmodders/sourcemod#920]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Linux
  * Game/AppID (with version if applicable): CS:GO - 1.36.5.8/13658 800/7268 secure  [G:1:2584081] 
  * Current SourceMod version: 1.9.0 - build 6260
  * Current SourceMod snapshot: 1.9.0 - build 6260
  * Current Metamod: Source snapshot: 1.10.7 - build 966
  - [X] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [ ] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
In my servers this plugin activated `mapchooser.smx` it has moments that works everything right, however it has maps that it does not show the voting of the maps and due to this when the map ends it does not change of map and stays in the same, only it changes if some admin change the map manually.

As I mentioned, there are moments that everything works fine, and in the next maps the voting no longer works, nor opens the voting menu.

**_Note: Only map-enabled plugins are `mapchooser.smx` & `nextmap.smx`._**

# Problematic Code (or Steps to Reproduce)
  ```
Just activate the plugin mapchooser.smx along with nextmap.smx and that's it, the BUG happens.

As I said, there are moments that work and others do not.
  ```

# Logs
Server error log: 
[errors_20181105.log](https://github.com/alliedmodders/sourcemod/files/2549947/errors_20181105.log)

**Comment by asherkin** [comment]
Please post on the forum, this is not a complete bug report.
