### ISSUE TITLE
Source SDK 2013 #ifd as not supporting FindMap, but supports it as of 2015

### ISSUE THREAD

**Issue by kzRaptor** [alliedmodders/sourcemod#927]
Hello everyone! I'm the developer for Kreedz Climbing, a SDK2013 based multiplayer mod that implements a workshop (.ugc map files), and I've encountered an issue - the nominate plugin can't fuzzy-match workshop map names (i.e. kz_mymap -> kz_mymap.ugc1234) because the FindMap function in SM intentionally skips calling the engine FindMap function  (due to perceived lack of SDK2013 support) and instead falls back to IsMapValid, which isn't capable of supporting workshop maps.

I tracked the problem down to **master/core/HalfLife2.cpp, line 1269**, where we can find this:

#elif SOURCE_ENGINE == SE_TF2 || SOURCE_ENGINE == SE_BMS
	...
	return (engine->FindMap(pFoundMap, static_cast<int>(nMapNameMax)));

#elif SOURCE_ENGINE == SE_CSS || SOURCE_ENGINE == SE_DODS || SOURCE_ENGINE == SE_HL2DM || SOURCE_ENGINE == SE_SDK2013
	...
	return engine21->IsMapValid(pMapName) 
#else

This shows that SDK2013 is explicitly flagged as not supporting FindMap, but it does as of the 2015 update to the SDK2013 github repo. Is there any chance of having the file amended to enable SDK2013 support? The only issue I can think of is that older mods that haven't merged with the latest source would break from that change, otherwise I'd have considered making a pull request myself.

Thanks for your time!

**Comment by kzRaptor** [comment]
Excellent, thank you psychonic! I'll close the issue once I can confirm things work on my end. Thank you very much again!

**Comment by BotoX** [comment]
This causes a behavior change in IsValidMap
Instead of calling the engine function IsValidMap it now calls FindMap which is not a bug into itself
but it compares the result of FindMap with != NotFound instead of == FindMap so now IsValidMap returns true on pretty much everything.
IsValidMap("a") -> true
IsValidMap("dust") -> true
IsValidMap("dE_DuSt") -> true
IsValidMap("dust3") -> false

I changed CHalfLife2::IsMapValid like so to keep the original and engine behavior of IsValidMap:
```diff
diff --git a/core/HalfLife2.cpp b/core/HalfLife2.cpp
index 9e2bad5b..ddb95abb 100644
--- a/core/HalfLife2.cpp
+++ b/core/HalfLife2.cpp
@@ -1313,7 +1313,7 @@ bool CHalfLife2::IsMapValid(const char *map)
 	if (!map || !map[0])
 		return false;
 	
-	return FindMap(map) != SMFindMapResult::NotFound;
+	return FindMap(map) == SMFindMapResult::Found;
 }
 
 // TODO: Add ep1 support for this. (No IServerTools available there)
```
