### ISSUE TITLE
Feature Request: Check translation files with compiler

### ISSUE THREAD

**Issue by stickz** [alliedmodders/sourcemod#930]
I would like an optional feature added to sourcemod compiler to check phrase files. This would allow plugin developers to detect errors in their phrase formatting early, before they reach servers.

My preferred implementation would be to look for a translation directory in the scripting folder. Then check all the %t and %T formatting in the PrintToChat() functions, against the format specified in the phrase file. 

I would like to know if a) a phrase in missing or b) a phrase does not adhere to proper formatting rules.

**Comment by Headline** [comment]
This couldn't go into `spcomp` itself, however a new tool could be created for this purpose. I'm unsure if such a program should live here alongside sourcemod, but if it did it would have to live in `/tools`. I'm iffy about it

**Comment by Headline** [comment]
Looking back, this tool should definitely be created independently from sourcemod as an ease-of-use helper, rather than be included here.

Thanks for creating this report!
