### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by megoRU** [alliedmodders/sourcemod#941]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: linux idk hosting
  * Game/AppID (with version if applicable): CS:GO/730 (1.36.7.2)
  * Current SourceMod version: 1.9.0.6270
  * Current SourceMod snapshot: ??
  * Current Metamod: Source snapshot: 1.11.0.1116
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
The server sometimes crashes on startup

# Logs
[crash-2018-12-28_12-26-18.log](https://github.com/alliedmodders/sourcemod/files/2714777/crash-2018-12-28_12-26-18.log)
dump
![image](https://user-images.githubusercontent.com/23276305/50514497-982ab100-0aaf-11e9-996d-850fba40781d.png)

**Comment by asherkin** [comment]
This is a bug in one of your installed extensions, something is passing NULL to `CloseGameConfigFile`. Shutdown crashes in general are very low priority, so coupled with the fact this is probably in 3rd party code I’m going to close the issue. You should post on the forum with more information about your setup and the crash dump if you need further assistance.
