### ISSUE TITLE
GeoIP.dat 0 KB, server crashing when using geoip functions.

### ISSUE THREAD

**Issue by joao7yt** [alliedmodders/sourcemod#951]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 10 Pro
  * Game/AppID (with version if applicable): CS:GO/730
  * Current SourceMod version: 1.9.0.6274
  * Current SourceMod snapshot: 
  * Current Metamod: Source snapshot: 
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Server crashes with no log when trying to use geoip functions. It has to do with the 1.9.0.6274 GeoIP.dat file being 0 KB. Using the previous version of GeoIP.dat won't crash the server.

# Problematic Code (or Steps to Reproduce)
This script will crash the server as soon as a player connects.
  ```
  #pragma semicolon 1

#include <sourcemod>
#include <sdktools>
#include <sdkhooks>
#include <geoip>
#include <cstrike>
#undef REQUIRE_PLUGIN
#undef REQUIRE_EXTENSIONS

#pragma newdecls required

public void OnClientPostAdminCheck(int client)
{
	if (client == 0)
	{
		return;
	}
	
	char ip_address[14];
	GetClientIP(client, ip_address, sizeof(ip_address));
	
	char country[3];
	GeoipCode2(ip_address, country);
	PrintToServer("%s", country);
}
  ```

**Comment by asherkin** [comment]
Thanks for the report! I'm going to WontFix this as we're moving away from the legacy GeoLite data in #914, but the builds have been fixed to no longer have the broken data file.

**Comment by joao7yt** [comment]
Wait, now the last release of sourcemod includes a working GeoIP.dat. Is that already GeoLite2? I'm kinda confused... What is suppose to change from the GeoLite to GeoLite2 support? Will sourcemod functions change or will be the same?

Sorry for the lack of knowledge.

**Comment by joao7yt** [comment]
Oh, ok, thanks.
