### ISSUE TITLE
Translations: %% pastes number instead of sign

### ISSUE THREAD

**Issue by metrotyranno** [alliedmodders/sourcemod#958]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Centos 7 3.10.0-957.1.3.el7.x86_64
  * Game/AppID (with version if applicable): Empires 460040
  * Current SourceMod version: Stable 6275
  * Current SourceMod snapshot: Dev 6381
  * Current Metamod: Source snapshot: 1.10 build 968 stable
  - [x] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [x] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [x] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
Translation files %% are incorrectly parsed. They also appear to overwrite some parts of the translation, for example the translation file reads: "... {1}%% of  ..." The actual result however removes the space and the o of "% of"

I have tested the dev and stable builds. both produce this error.

# Problematic Code (or Steps to Reproduce)
Steps performed on a base, clean install.
Issue command !vote 1 2 3

Expected result:
[SM] Initiated a vote: 1
[SM] Vote successful. (Received 1% of 1 votes)

Actual result
[SM] Initiated a vote: 1
[SM] Vote successful. (Received 1004727576730f 1 votes)

# Logs
Console log
L 02/04/2019 - 18:53:52: "Metrotyranno<2><[U:1:28598089]><Spectator>" say "!vote 1 23 3"
L 02/04/2019 - 18:53:52: [basevotes.smx] "Metrotyranno<2><[U:1:28598089]><>" initiated a generic vote.

There is no information logged to /var/log/messages or dmesg

**Comment by Fyren** [comment]
This is probably an ancient bug in Empires.  There's some info here when it came up **ten years ago**: https://bugs.alliedmods.net/show_bug.cgi?id=3557

**Comment by KyleSanderson** [comment]
ack :( please contact the author of the mod.
