### ISSUE TITLE
New Carsh after update today 2019/02/07

### ISSUE THREAD

**Issue by Drmohammad11** [alliedmodders/sourcemod#960]
hi guys!
my servers crashed after update today!

# Version:
i used last version of sm1.9 with mm and windows.

# Logs
https://crash.limetech.org/stats/2a2ea91c95b57040e2eb7df60e3eeee3d3e169b64ce350a2c82d86f9a17f74b1d7213211b7398d70

`sdktools.ext.2.csgo.dll!__SourceHook_MFHCls_PlayerRunCmdHook::Func(CUserCmd *,IMoveHelper *) 
sourcemod.2.csgo.dll!__SourceHook_FHCls_IServerGameDLLGameFramefalse::Func(bool) [sourcemod.cpp:54 + 0xa3]

**Comment by psychonic** [comment]
This crash has nothing to do with SourceMod and occurs on servers without it.

Those mentioned functions will occur in many backtraces just because the functions being hooked are high in the chain of most game logic.
