### ISSUE TITLE
"Host_Error: DLL_Crosshairangle: not a client"

### ISSUE THREAD

**Issue by amphoracheats** [alliedmodders/sourcemod#975]
Well cant provide more info, dont got more, but some people have managed to get it, would using a older build would work too?

**Comment by psychonic** [comment]
This was fixed in the latest build of MM:S and SM. If you still have it when running those, it's from something else.

**Comment by amphoracheats** [comment]
Well i downloaded the new one, from the website and still giving it @psychonic

**Comment by borzaka** [comment]
Update [SourceMod](https://www.sourcemod.net/downloads.php?branch=stable) AND [Metamod](https://www.sourcemm.net/downloads.php?branch=stable) too from the stable builds corresponding to your server operating system.

**Comment by Headline** [comment]
try to remove 3rd party extensions and run the blank SourceMod installation
