### ISSUE TITLE
ProtectMemory called with wrong address in public/CDetour/detourhelpers.h

### ISSUE THREAD

**Issue by wrzwicky** [alliedmodders/sourcemod#984]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
(not applicable)

# Description
This line in detourhelpers.h:
[`ProtectMemory(address, 20, PAGE_EXECUTE_READWRITE);`](https://github.com/alliedmodders/sourcemod/blob/ae00144e84263c934d4df9b3cf0c10204e1a18a3/public/CDetour/detourhelpers.h#L121)
should be changed to this:
`ProtectMemory((void *)addr, 20, PAGE_EXECUTE_READWRITE);`
but this may be even more correct:
`ProtectMemory((void *)addr, patch->bytes, PAGE_EXECUTE_READWRITE);`

_UPD: ProtectMemory also may have bug, see comment._

# Explanation
A friend is coding own mods for his server, and found what appears to be a bug. The first proposed change above has stopped certain segfaults from occurring.

The second proposed change appears more correct to me from simple inspection of the code.

His explanation:

> on mine I've changed it to this:
> 	ProtectMemory((void *)addr, 20, PAGE_EXECUTE_READWRITE);
> and the segfaults went away
> I mean
> it looks like Sourcemod is using it not for generic patches
> but for detouring
> so it hasn't been an issue for them
> detours are installed at the start of functions
> within the first 20 bytes
> the problem only comes when you try to use that ApplyPatch function for general purpose patching in random locations
> and it only protects the first 20 bytes of the function

Note that "on mine" refers to his private copy of `detourhelpers.h`. He's using ApplyPatch to patch functions, not just create detours, and finding that some calls to ApplyPatch cause segfaults. The proposed fix eliminates these segfaults.

Note that neither of us are familiar with how ProtectMemory is meant to be used, but this appears to be correct from inspection and the elimination of crashes.

# Problematic Code (or Steps to Reproduce)
Use ApplyPatch() to change bytes "far" from the start of the function. I assume "far" means "any subsequent memory pages", but again I don't know how it works.

**Comment by wrzwicky** [comment]
UPDATE: ProtectMemory also appears to be **incorrect** on POSIX systems -- the length field is ignored!

According to documentation of mprotect, this should be sufficient:
`mprotect(address, length, prot);`

**Comment by dvander** [comment]
Good catch - probably what happened is your patch crossed a page boundary, and only the first page is getting protected. The real fix is something like this:

1. Calculate the page address for |addr|.
2. Calculate the page address for |addr+length|.
3. Call mprotect() with length = ($2 - $1 + 1) * sysconf(_SC_PAGESIZE)

**Comment by KyleSanderson** [comment]
I thought we've already fixed this like a decade ago in SourceHook, checkout MakePageWritable and SetMemAccess. Think we can re-use those facilities here?

**Comment by wrzwicky** [comment]
> 1. Calculate the page address for |addr|.
> 2. Calculate the page address for |addr+length|.

It looks like both the Windows and POSIX functions do this for you. All you need to do is call protect(start_address, length, type), and they both change protection on all pages covering that byte range.

**Comment by dvander** [comment]
In the manpage for mprotect it says "addr must be aligned to a page boundary."
